### ISSUE TITLE
Deleting a paste didnt delete the folder

### ISSUE THREAD

**Issue by Maik-Thiele** [PrivateBin/PrivateBin#101]
When I delete a paste, the paste was deleted but not the folders (first and sub) the paste was in. 
After hundreds of pastes I have hundred of empty folders.

**Comment by elrido** [comment]
This is correct and so far an expected behaviour.

The reasoning why I didn't implement this is, that the folders can (and eventually will) contain multiple pastes. This is not very frequent when you start, but there will eventually be collisions in the first 4 characters of the paste ID (which is to be considered a pseudo random number for the purpose of this topic).

Hence to be able to delete the folders, we would need to check the lower and upper level folders for other content. This requires at least two more accesses to the filesystem, slowing down the deletion process and significantly increasing the code base, for the benefit that the folder structure looks cleaner and a gain of 1 - 2 inodes on the disk.

On a frequently used system those folders eventually are all required and no folders could be deleted anymore. So those checks would still be performed, but almost never would result in any cleanup.

If this is a concern for you, please consider switching to the [database backend](https://github.com/PrivateBin/PrivateBin/wiki/Installation#using-a-database-instead-of-flat-files). There a delete is completely clean as it will simply delete all comments of that paste in the comments table (if there are any) and the single entry in the paste table, leaving no remnants of the paste on your system (except in your database backups, of course, but that is the same with the filesystem backups for the default filesystem backend).
