### ISSUE TITLE
Problem with guess language - and switching

### ISSUE THREAD

**Issue by bobfh** [PrivateBin/PrivateBin#1032]
Vesion of PrivateBin is 1.5.0

## Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/88323396/207858663-cf2ca3eb-342f-4c8e-8bbc-2135733c546b.png)

2. On english browser - when i open - no changed language - stay Polish

3. If i clean cookies by the hand - it work some time 

### What happens
No changing language normal

### What should happen
Normal detect language and change it 

## Basic information

I can reproduce this issue on <https://privatebin.net>: No

**Comment by bobfh** [comment]
May be problem is - that i use domain like a secret.domain.com ?

**Comment by rugk** [comment]
Hmm I checked the doc on these settings: https://github.com/PrivateBin/PrivateBin/wiki/Configuration#languageselection--languagedefault

And I agree if English is detected, it should choose English there, then.

It should be the last case in the table:
> uses browser language or the one last selected and stored in the cookie and uses "fr" as the fallback for unknown browser languages

**Comment by rugk** [comment]
Note the cookie thing is certainly related, have you opened the website in a fresh browser or after cleaning cookies? Then it should be English, otherwise an older cookie could still say PL e.g.

**Comment by elrido** [comment]
So with the settings as shown, we would expect the page to always be in Polish and never in English. The mechanism used, as @rugk explained, is that the cookie will get (re)set to the configuration value on every request:
https://github.com/PrivateBin/PrivateBin/blob/1128c679eb219dd0f55dff39c93145be160ca615/lib/Controller.php#L169-L177
So the behavior described is exactly as designed, but if I understand correctly, you would prefer to still have it guess the language (it looking up the browsers settings) and only fall back to Polish if no match is possible? If so, you will have to enable the `languageselection` option (set it to "true"), so that, as per the wiki page:

> uses browser language or the one last selected and stored in the cookie and uses "fr" as the fallback for unknown browser languages

**Comment by bobfh** [comment]
> Note the cookie thing is certainly related, have you opened the website in a fresh browser or after cleaning cookies? Then it should be English, otherwise an older cookie could still say PL e.g.

@elrido @rugk 

languagedefault="";
languageselection=false;

As i understand this parameters will on the language guess in browser - correct ?

**Comment by elrido** [comment]
Those are the default settings and when languagedefault is empty, it will default to English. With those settings, no cookie will be set, but if your browser still has a "lang" cookie set, that will apply, at least to the client side code - so you may have to manually delete it to see what other visitors will see.

**Comment by bobfh** [comment]
Ok - i have made defaults setting - and now use only guessed language
