### ISSUE TITLE
Stored XSS in `privatebin.io` Via Upload File ` HTML`

### ISSUE THREAD

**Issue by dzsami03** [PrivateBin/PrivateBin#1047]
Hello Team
I test domain **privatebin.io** is vulnerable to Cross-site Scripting (XSS) via crafted HTML files that contain script XSS,
and are attached to a paste.

POC: HTML file

`<script>confirm(document.domain)</script>`
you can see video POC:

https://user-images.githubusercontent.com/53130188/214590018-858ee1d0-af24-4f91-9a42-4a1453938567.mp4

**Comment by r4sas** [comment]
I think it can't be called XSS because you are opening an element in blob storage which contains an HTML file that will be executed `as is` by the browser if you try to open (not download) it.

**Comment by dzsami03** [comment]
hi
if you share the URL with another user share this or send this to victime
https://privatebin.io/?f615b5400773fea3#FvCbP76rjuea7a5MVYvBmXRHP3zuJujjqcSv6QpTEcEband if victim visit image url xss Will executed
I think like [CVE-2022-24833] 
https://privatebin.info/reports/vulnerability-2022-04-09.html
thanks

**Comment by r4sas** [comment]
`Download attachment` only starts downloading of attachment. What are you doing is opening this link in a new browser tab. This is different.

**Comment by dzsami03** [comment]
thanks
The victim may be deceived.

**Comment by r4sas** [comment]
Anyway, I can't reproduce this on Chromuim 109.0.5414.75.

/cc @rugk @elrido

**Comment by dzsami03** [comment]
I test in chromium **109.0.5414.74 (Official Build) (64-bit)**
![Screenshot from 2023-01-25 16-43-42](https://user-images.githubusercontent.com/53130188/214608451-a6a4d708-13e3-40fa-bd49-78fc9bfc28a9.png)

**Comment by elrido** [comment]
When normally clicking on the "download attachment" link, it will trigger a download of the HTML file, _not_ open it in a new tab (tested in Firefox and Chromium). To get the JS to execute you either have to open the document manually from your download location or right-click the URL, copy the link, paste it into the address bar and hit enter.

- to trigger this behaviour, we require user-interaction, so you'd have to send the user detailed instructions
- the CSP header of the instance in question (as well as others that I used to repro the issue) do set the recommended policy of `default-src 'none'; [...] script-src 'self' 'unsafe-eval'; [...]` - so the CSP is not applied to local files (to be expected) nor to the blob URLs (this is unexpected, to me)
- that raises the question if the HTML would run in the domains context or not (that the CSP isn't applied indicates the latter)

We could consider sanitizing uploaded HTML files, but in the [case of SVGs, we specifically decided not to do that (see "Note" in "Patches"](https://privatebin.info/reports/vulnerability-2022-04-09.html). The reasoning taken was:

> We consider the execution of code from attachments outside of the PrivateBin instance's context to be out of scope to mitigate (i.e. malware in executables, office documents macros, PDF scripts), as all of these require client side mitigations to be applied to all such downloaded file types, independent on where they get downloaded from.

So far I still tend to stand by this and don't consider this to be XSS, as it doesn't seem to let you access any cookies or other domain specific (sensitive) content - it should just run in isolation and therefore not be any more risky than opening any other website.

For opening the file from disk (file:// context) we can be fairly certain that there is no leak of information from the instances context, I'm only wary of the blob-URL, but would argue that if that turned out to be the case, it is a bug in the browsers implementation not to apply the given CSP (which would prevent the JS from running), if they do run in the context of the domain.

For anyone running an instance and coming to a different conclusion in their own risk assessment, you may choose to disable file uploads on your instance or ensure that your instance runs on a dedicated subdomain, to alleviate any risk of exfiltrating sensitive context data from your domain(s).

**Comment by rugk** [comment]
I stand by this.

I tried reproducing this and I can say, yes, by copying that link manually with a right-click _and_ opening it in a new tab, you can get the HTML to show as any other HTML you open in your browser. (reproduced with Firefox)

```html
<script>console.log(window);alert(window.location)</script>
"><b>Bold</b>
'><u>Underlined</u>
```

A quick check with this HTML, however, reveals:
![grafik](https://github.com/PrivateBin/PrivateBin/assets/11966684/f53b40e7-2cbb-493b-ab44-ebb190e2fdc9)

You get a totally different (blob) context and e.g. the URL is lost. There is no data you could extract from that. We also use no sensitive cookies, but even these are not extractable. (Try running `document.cookie` on that domain, on the original PrivateBin website you may get a language cookie there, but that's it.)

For further vulnerability reports, I'd personally also suggest following our security policy and reporting it privately e.g. via GitHub: https://github.com/PrivateBin/PrivateBin

**Comment by rugk** [comment]
Though https://github.com/PrivateBin/PrivateBin/security/advisories/GHSA-cqcc-mm6x-vmvw also used a blob URI, but yeah it's likely also harder to convince someone to use.

What wonders  me is that opening in a new tab has such a different behavior than copying the link manually and opening it in a new tab.

I however, also think it is separated and the cookie test proves it. For the old SVG CVE just opening in a new tab AFAIK may be a different result. As said, try opening the file in a new tab instead:
![grafik](https://github.com/PrivateBin/PrivateBin/assets/11966684/46b117d6-af30-46fd-91a5-035e707969d6)

Though here the CSP applies. However, cookies cannot be read. Interestingly a fetch is possible on the domain, but we again have no sensitive data to fetch hmm:
![grafik](https://github.com/PrivateBin/PrivateBin/assets/11966684/b34907df-2977-49fe-8140-0d2d8776dcc0)
