### ISSUE TITLE
shortenviayourls not working

### ISSUE THREAD

**Issue by VijendraMalhotra** [PrivateBin/PrivateBin#1049]
## Steps to reproduce

1. Upgraded to the new 1.5.1 release
2. changed the configuration to add the shortenviayourls settings

```
        basepath = "https://bin.malhotra.me/paste/"
        urlshortener = "${basepath}shortenviayourls?link="
        
        [yourls]
        signature = "blahblahblah "
        ; (optional) the URL of the YOURLS API, called to shorten a PrivateBin URL
        apiurl = "https://vru.me/yourls-api.php"
```

### What happens
When i click the shorten URL button i get an 404 error complaining that /shortenviayourls is not present. 

### What should happen
A call to my yourls site should be used i presume

## Basic information

**Server address**: bin.malhotra.me/paste

**Server OS:** Ubuntu 22.04.1

**Webserver:** apache

**Browser:** Brave and Safari

**PrivateBin version:** 1.5.1 

I can reproduce this issue on <https://privatebin.net>:  No

**Comment by elrido** [comment]
Please check your webserver's configuration and compare that with the error code it logs. My bet would be that requests to https://bin.malhotra.me/paste/shortenviayourls are not redirected to the index.php file of privatebin.

Here are example configurations for nginx and apache, to compare yours against, if you use one of these two:
- [nginx](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/etc/nginx/http.d/site.conf) - the `location /` (would be /paste/ in your case) is served by the `try_files $uri $uri/ /index.php$is_args$args;` rule and since /paste/shortenviayourls wouldn't exist it would fall back to index.php
- [apache](https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_l) - in apache mod_rewrite can be used to redirect the request for /paste/shortenviayourls to the index.php file.

**Comment by VijendraMalhotra** [comment]
Thank you.
Is there any documentation to say what rules must be added when using this feature. I tried to look at the [configuration document](https://github.com/PrivateBin/PrivateBin/wiki/Configuration).

**Comment by elrido** [comment]
It depends on the webserver you are using, hence we can't provide generic advice. In my previous reply I have linked two examples. It is a very common setup used for any web application that includes a routing mechanism and a single script or (CGI) binary. We do offer a container image that is pre-configured for this (the nginx example was from there).

**Comment by VijendraMalhotra** [comment]
> It depends on the webserver you are using, hence we can't provide generic advice. In my previous reply I have linked two examples. It is a very common setup used for any web application that includes a routing mechanism and a single script or (CGI) binary. We do offer a container image that is pre-configured for this (the nginx example was from there).

I use apache.
 Perhaps an addition to the documentation would help to say that a manual route needs to be added would be helpful?

**Comment by MagnusHL** [comment]
Did the rewrite rule fixed your problem?
I run into the same problem and I don't know how to set the rewrite rule:

get 404: 
https://pastebin.hinzke.de/shortenviayourls?link=https%3A%2F%2Fpastebin.hinzke.de%2F%3Fc75b4e0dc7fa29f4%23HzUKW1fcL8h2sgR5mpY2v3MCoJUU9ynmQaoEb8ZwZYWo

**Comment by elrido** [comment]
Been a while since I've used apache - shouldn't the `RewriteBase` be  just `"/"`? If memory serves, this string is removed from the REQUEST_URI parameter that our code parses to detect the "/shortenviayourls" path.
https://github.com/PrivateBin/PrivateBin/blob/fa8cc59ec03f7c26b4cd9f27b902f2e279507048/lib/Request.php#L146

Aside: Because we evaluate the REQUEST_URI you don't need to inject the path as a "req" GET parameter, so `RewriteRule "^(.*)" "/index.php" [L,PT]` should suffice. Though it shouldn't break anything either.

**Comment by MagnusHL** [comment]
Hi!

Here I get a stupid page: https://pastebin.hinzke.de/
```
        RewriteBase "/shortenviayourls"
        RewriteCond "%{REQUEST_URI}" "!=/index.php"
        RewriteRule "^(.*)" "/index.php" [L,PT]
```

This get me a 404:
```
        RewriteBase "/"
        RewriteCond "%{REQUEST_URI}" "!=/index.php"
        RewriteRule "^(.*)" "/index.php" [L,PT]
```

**Comment by VijendraMalhotra** [comment]
Still struggling with this. anyone has a solution

**Comment by elrido** [comment]
I'm sorry, we need the help of an apache expert here. I'm sure it is possible to set this up, as this is a common design pattern used with PHP apps since at least 15 years and I know I had such setups with apache back then, but I switched to nginx over 10 years ago and have no experience or sample configs that I could share for it.

**Comment by VijendraMalhotra** [comment]
ChatGPT to the rescue!! 


# Redirect /shortenviayourls to /index.php with query string parameters
RewriteRule ^shortenviayourls$ /index.php [L,QSA]

# Serve other requests with try_files directive
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L]

**Comment by MagnusHL** [comment]
Man, I am in love!

Thanks to ChatGPT and your ideal!!!

Can be closed! ;)
