### ISSUE TITLE
How to Migrate to Another Server

### ISSUE THREAD

**Issue by yaseerb** [PrivateBin/PrivateBin#1075]
Hello, last night I decided to migrate all of my files to a new VPS. I only copied the files without doing any modification. I thought it will works just fine but I received this instead in the browser console :

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://www.yasir252.com/links/js/jquery-3.6.0.js' with computed SHA-512 integrity 'QdJMQmq8+RO+WZF1kdkGMYpUdmEoADawmKKxuUi8+f8U8mixQNsQlWcw1kqFemG4EDTYiO1/hXQZ3ua40ydEfA=='. The resource has been blocked.`

**The problem displayed as this:**

Loading…
In case this message never disappears please have a look at [this FAQ for information to troubleshoot](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-the-loading-message-not-go-away).

**Link Example :**
https://www.yasir252.com/links/?0fb67cf85419a685#GKXkA8HW3jx4RRrrhVeYPKyd7yKdLhbrJqZfkXB49Kds

Can you help me to fix this issue? What is the problem?

**Previous VPS**
Plesk, PHP 8.0, Ubuntu 20.04, Apache with Nginx FPM

**New VPS**
Plesk, PHP 8.0, CentOS 7.9, Apache with Nginx FPM

I'm using cloudflare only for DNS, not using their caching system.

**Comment by elrido** [comment]
The JS files (and potentially others) got mangled, they are now [CR LF delimited instead of LF only](https://en.wikipedia.org/wiki/Newline#Issues_with_different_newline_formats). This can happen if you transfer the files to a Windows system in text mode, i.e. using an FTP client. Try copying the data in binary mode or by creating an archive (tar file, for example), transferring that and unpacking it on the destination host.

It may be possible to convert the files back using tr or dos2unix, but there is a risk that other things might have gotten mangled and the SRI hashes still don't match or pastes fail to get parsed.

**Comment by yaseerb** [comment]
Based on your answer, I got an insight. I simply removed all the related html attribute

`integrity="sha512-/F0+9bIbFUC8mKQzrcAjIs2Jg92w1DMcczT2Y/KqHVkFEXH1ZSrqtUX7QjLH6RgVR0YhTxhmWkZ2c8scGCwpkQ==" crossorigin="anonymous`

Inside the page.php and bootstrap.php. Now it works perfectly. Well, at least now it can display the locked content. Thank you!

**Comment by rugk** [comment]
This is actually not a good solution. Possibly, but not good. I'd recommend just re-downloading the original source from GitHub or however you deploy it and just overwrite it (especially the JS files, as these cause the error).

Again, I'd like to point you to the FAQ entry the error message already points to: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-the-loading-message-not-go-away

It explains why this happens and explains how to proceed [if you have _intentional_ changes in your JS files](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-i-have-changed-some-javascript-files).
