### ISSUE TITLE
The private bin deployed by Docker does not have a control to add attachments

### ISSUE THREAD

**Issue by 2227190257** [PrivateBin/PrivateBin#1090]
The private bin deployed by Docker does not have a control to add attachments

**Comment by 2227190257** [comment]
![image](https://github.com/PrivateBin/PrivateBin/assets/28613605/1d0e8a0d-5a67-4917-b199-d24cefc55b49)

**Comment by elrido** [comment]
This is not only the case with the docker deployment, PrivateBin has this feature disabled by default.

This is documented in the [wiki article on the configuration options](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#fileupload), and how you can enable it if you'd like to use this feature.

In order to enable this feature in the container image, please follow the [section on customizing your configuration in the container images README file](https://github.com/PrivateBin/docker-nginx-fpm-alpine#custom-configuration).
