### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Amir-Ahmad** [PrivateBin/PrivateBin#1095]
Would it be possible to have a new release? We would like to use the s3 changes from this PR https://github.com/PrivateBin/PrivateBin/pull/1070

**Comment by elrido** [comment]
At the moment there aren't that many changes in since 1.5.1. But there would be a few library updates that could get added and there are some open PRs that could get merged as well, but currently can't because they lack approval by a second pair of eyes. I can approve and merge other folks PRs, but currently can't get my own work reviewed or merged, including cutting a release, which requires at least some version bumps and changelog updates.

We had enabled the requirement of a second maintainer to approve changes of another one for the obvious security benefits that brings. Unfortunately, right now it would prevent a release, as I have not had any interactions with the other maintainers since several months. We may have to disable that requirement again, temporarily, until the other maintainers can again become more active or we get new maintainers.

It has also demotivated myself to add more PRs, even for simple and quick fixes, as I haven't seen my own work go anywhere in the project due to the above.

I understand that life can get in the way and the last years have been a roller coaster for many of us. Like any project we really need multiple active peeps to keep this up to date and going - the more there are, the lower the load on each maintainer.

Yes, this is also another request for you, dear reader, to help maintain this project - You don't need to be a guru JS-coder and PHP-wizard to apply, a basic familiarity in either of these languages and willingness to review and comment on PRs (even just to ask how a certain piece of code works where it is not clear to a novice) would help a great deal, keeping the project going. If anyone who reads this is interested or has any further questions, please do reach out via email to support@privatebin.org - that alias is distributed to all core maintainers, not just me.

**Comment by elrido** [comment]
We got the all the libraries updated, so I'll try and get that released, this weekend.

**Comment by elrido** [comment]
[PrivateBin 1.5.2](https://privatebin.info/news/v1.5.2-release.html) has now been released, including the mentioned feature.
