### ISSUE TITLE
Mobile: Click on checkboxes closes popups

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#111]
## Steps to reproduce

![checkboxclose](https://cloud.githubusercontent.com/assets/11966684/19213869/0ad3b7d8-8d76-11e6-9bc2-e9132452ab87.gif)

### What happens
Popup closes when checkbox is clicked.

### What should happen
Leave the popup open.

## Basic information

**Browser:** Firefox 49.0.1

**PrivateBin version:** 1.0

**Comment by elrido** [comment]
On one side I personally think this is a good UI design. I never experienced any application that wouldn't close its drop downs when you select a different option.

And on the other side this is the behaviour the bootstrap devs choose for this case. I would not patch this away in our project, because we would need to maintain that fix across all future bootstrap releases.

Please discuss this upstream with the bootstrap devs if this should be changed or not. If they choose to do so, I will not stand in the way of using that when a future bootstrap release introduces such a change as a new default.
