### ISSUE TITLE
An issue with the Syntax highlighting

### ISSUE THREAD

**Issue by Rikitik** [PrivateBin/PrivateBin#1125]
## Steps to reproduce
Go to privatebin.at write up any sentence with a single word like: won't, doesn't I'm can't 

### What happens
pretty much anything after has a string syntax highlghting

### What should happen
It should be able to identy a word over a string

## Additional information
https://i.postimg.cc/YCjspvHt/privbininfintestringbug.png)

## Basic information
https://privatebin.at/?af12e094aa44e280#4TAiM9KYGCnZCjLV4ZSr8aQP3abrBKyE1oKvSFUmb9ZD

**OS
**Windows**

**PrivateBin version:** :1.5.2

I can reproduce this issue on <https://privatebin.net>: Yes

## Possible Fix 

Regex test 
[a-zA-Z]{2,}\\'[a-zA-Z]\s  - Any word character, 2 or more folowed by a literal   '   than any single word character and a white space
and
 \s[a-zA-Z]\\'[a-zA-Z]\s

**Comment by elrido** [comment]
I'm not sure I understand what the problem is exactly. Let me try to break down what I observe:
- privatebin.at (which is not affiliated with the maintainers of this project) has configured new pastes to default to format "Sourcecode"
- other instances, including the demo instance at privatebin.net default to "Plaintext"
- In either case, the format can be changed by the user, if they do not wish to use "Sourcecode" format
- If you host your own instance and don't like "Sourcecode" format, you can also remove it from the configuration entirely
- when in "Sourcecode" format, the single tick will IMHO correctly be identified as the start of a quoted string and over several lines be marked as such and if it is the only occurrence of a single tick, yes, everything till the rest of the paste is highlighted as a quoted string - as a software developer, that is what I expect to see for most programming languages, though there are some that don't support multi-line quoted strings
- If there is something that needs to be improved in the prettify library, that would need to be raised upstream - unfortunately the library seems abandoned, and we are looking for someone to replace it, see #835

So to me the feature seems to work as intended, but you may have been surprised that this instance (.at) choose to set it as the default formatter, and could just manually select plain text or use a [different instance](https://privatebin.info/directory/) with defaults that align with your preferences?

**Comment by Rikitik** [comment]
The issue is in the syntax highlighting for the"Sourcecode" format when a word is encountered that has a single tick: '
It asumes everything after it is a string a simple regular expresion test that is done after an occurance of an uneven number of ticks should prevent this behavior and should stil retain Multi-line string notation support as a developer myself i can make a sugeston i dont have time to look through your codebase at this moment if you dont want to fix it. That is fine as well
Since this feature is provided by an external dependancy that you can not fix, you can close it but It Multi-line string support and word abreviation are not mutually exclusive features

**Comment by elrido** [comment]
IMHO the Source Code formatter works correctly for this case - there are programming languages that have multi-line single quoted strings and these get correctly recognized:

![Sample paste with multi-line, single quoted strings, including escaping](https://github.com/PrivateBin/PrivateBin/assets/1017622/3cffc07f-2f3b-4c91-92fc-04da843a3cba)
[sample paste](https://snip.dssr.ch/?14cdea739c3416e9#EhGmdK1QRHnoioCeF2yr8N3hiVw8AHxaa3oJB7duQpWD)

If you added a snippet of source code, where the ending single tick is missing, then it would recognize the remainder as belonging to that string. But that is a fault with that the source code snippet and would also get rejected by the compiler or lead to funny results in an interpreted language.

**Comment by Rikitik** [comment]
I don't think you understand what i said yes it works for sourcode, but not for normal formated text while sourcecode syntax highlighting is enabled these two things are not mutally exclusive. you can support in the sourceode format. This is the best i can do to make it clear to you, i'm sorry if my explaination is insuficient

**Comment by ppfeufer** [comment]
Use this for plain text …

![image](https://github.com/PrivateBin/PrivateBin/assets/2989985/128676e7-1066-49b3-96b7-7e42078a1738)

**Comment by Rikitik** [comment]
I know how to use this. I reported a bug. It REALLY is a bug but feel free to ignore it

**Comment by rugk** [comment]
Your initial issue shows this image:
![grafik](https://github.com/PrivateBin/PrivateBin/assets/11966684/b5f51c97-02a0-4612-98e2-d74935093835)

The code is:
```
This string notation wil never end!, it really won't.
Look im a string on a new line
and a new line and a new line

To fix the lexicon
solution regex test [a-zA-Z]{2,}[a-zA-Z]\s 
and a new line should end a string notation
```

As you can see GitHub does not highlight anything when you have no language tag set – we don't have that option unfortunately as we have no language selector, we need to rely on a "common syntax highlighter" that is common enough to work for most languages and/or autp-detects the language.

If you e.g. select PHP this also does not go well on GitHub:

```php
This string notation wil never end!, it really won't.
Look im a string on a new line
and a new line and a new line

To fix the lexicon
solution regex test [a-zA-Z]{2,}[a-zA-Z]\s 
and a new line should end a string notation
```

> not for normal formated text while sourcecode syntax highlighting is enabled these two things are not mutally exclusiv

So you want it to detect "normal formatted text" when being in source code mode? Theoretically this may be possible, but I don't know any syntax highlighter that does that.
After all, what is your use case? If you have "normal text", just select "Plain text", there is no need to select the source code formatter and this really seems like an edge case – note we have [bigger issues with the current syntax highlighter](https://github.com/PrivateBin/PrivateBin/issues?q=is%3Aissue+is%3Aopen+syntax+highlighting).

Anyway, as it has been said, it is an upstream library that does syntax highlighting, so even if we were to change that, this would not really be in our hands.
However, if the RegEx solution you indicated in your paste is a real solution, feel free to contribute this to a highlighting library: https://github.com/PrivateBin/PrivateBin/issues/835

**Comment by ririko5834** [comment]
@elrido What theme are you using? I would like that too

**Comment by ririko5834** [comment]
<img width="2552" height="611" alt="Image" src="https://github.com/user-attachments/assets/f63ed89e-b207-4fae-865b-9c70223b7dae" />
highlighting doesnt work for me as well, i have latest version and using bootstrap-page theme

**Comment by elrido** [comment]
> [@elrido](https://github.com/elrido) What theme are you using? I would like that too

That snip instance I shared uses the `bootstrap5` template, which will automatically select the appropriate `syntaxhighlightingtheme` depending on the dark mode. On the other templates that setting has to match the templates look, for example for your `bootstrap-page` template you'd want to leave syntaxhighlightingtheme commented or at least NOT set to `sons-of-obsidian` which is better suited for dark mode.
