### ISSUE TITLE
Privatebin using an S3 bucket keeps slowing down the more files I add

### ISSUE THREAD

**Issue by maxisalamone** [PrivateBin/PrivateBin#1158]
<-- Describe the bug: A clear and concise description of what the bug is. -->
With more than 200 files in an S3 bucket, privatebin slows down dramatically at giving back a link. This however happens the 1st time it is used, since a 2nd one will go very fast. After some hours (I guess some cache is cleared on the server side), the effect repeats.
## Steps to reproduce

1. Set up a privatebin pod in an AWS kubernetes cluster, configured for S3 bucket
2. Set up a bucket for it.
3. Add many files (200+). Just lightweight files are enough, mostly below 1kb

### What happens

Privatebin takes from 15 to 20 seconds to give back a link

### What should happen

Give back a link after 1 or 2 seconds, since this effect doesn't happen with fewer files.

## Basic information

**Server address**:
privatebin.zebrands.mx

**Server OS:**
kubernetes 1.24

**Webserver:**

**Browser:**
Chrome, Firefox for desktop, Firefox for mobile.

**PrivateBin version:**
0.19.0 and latest 1.5.2. Both with same issue.
I can reproduce this issue on <https://privatebin.net>: Yes / No
No

**Comment by elrido** [comment]
Thank you for reporting this finding. As far as I am aware, none of the maintainers of the project have access to or are using AWS or ceph-based S3 storage, so we wont be able to replicate or test this ourselves. The S3 backend was community-provided and we will need to rely on members of the community to investigate and address this. I can and will of course help with my knowledge of the code internals and support anyone raising a PR with code changes for this, should they be necessary.

That said, I could imagine that this is a similar phenomenon as with the file backend, where a similar issue starts to occur when you have several thousands of pastes (less with slower disks). There it is caused by the automatic purge being triggered  - the purge tries to find expired pastes, but on non-database-backends it must fully parse each randomly picked paste to check it's meta data.

You can try and change the purge settings (temporarily) to see if this S3 issue might be related to that, for example reducing the batchsize, to reduce the time spent on this, or tweaking the time limit so it occurs less frequently:
https://github.com/PrivateBin/PrivateBin/wiki/Configuration#purge

On the demo instance, where we have around 36000 pastes ATM, we have disabled the automatic purge and instead use the administration script's `--purge` option, triggered via cronjob once a day - it will do a full purge, reading and checking all pastes. That setting is:

```
[purge]
batchsize = 0
```

The cronjob is set up as:
```
45 2 * * * /usr/bin/docker exec -t privatebin-demo administration --purge
```
