### ISSUE TITLE
Server error when uploading files > 1MB with GCS backend

### ISSUE THREAD

**Issue by Pigment-RomainLoisel** [PrivateBin/PrivateBin#1165]
When deploying privatebin/gcs to cloud run with GCS backend, you can create paste of the size you want, but you cannot access paste when you upload file > 1MB in size.

## Steps to reproduce
1. Deploy PrivateBin on cloud run with GCS storage
2. Create new paste and upload file > 1MB
3. Paste is created OK
4. Access Paste

### What happens
"Could not get paste data: server error or not responding"

<img width="738" alt="SCR-20230911-oeqq" src="https://github.com/PrivateBin/PrivateBin/assets/138567804/973dd948-948c-4f27-810d-1b00d9e94253">

### What should happen
Access the paste and download the file

## Additional information
Error log

`upstream timed out (110: Operation timed out) while reading upstream, client: ******, server: , request: "GET /?pasteid=********** HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock`

I also encountered this error, but it is weird because I can see pastes are created in GCS: 
```
GuzzleHttp\Exception\ClientException: Thrown GuzzleHttp\Exception\ClientException: Client error: `GET https://storage.googleapis.com/storage/v1/b/*****-privatebin-data/o/pastes%2F**********?fields=name&prettyPrint=false` resulted in a `404 Not Found` response:
{"error":{"code":404,"message":"No such object: ******-privatebin-data/pastes/***********","errors":[{"message":"No such object: *********-privatebin-data/pastes/***********","domain":"global","reaso (truncated...)
 in /srv/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
```

## Basic information

**PrivateBin version:** 1.5.2

I can reproduce this issue on <https://privatebin.net>:  No

**Comment by rugk** [comment]
Please add your config details. Did you adjust the size limit? https://github.com/PrivateBin/PrivateBin/wiki/Configuration#sizelimit

Also see https://github.com/PrivateBin/PrivateBin/issues/858 for general issues on uploading (larger) files.

Can you try temporarily disabling the GCS backend and use another storage option? Does that fix the issue?
If so, you have confirmed the issue is in the GCS backend integration.

Note that google Cloud Storage was a community-contribution (ref https://github.com/PrivateBin/PrivateBin/pull/795 /cc @mvanholsteijn) and we do not have the capacity to maintain that part except for critical issues.

**Comment by elrido** [comment]
Thank you for helping others in sharing your findings!
