### ISSUE TITLE
Password field gets prepopulated with saved passwords from Firefox' password manager

### ISSUE THREAD

**Issue by Wikinaut** [PrivateBin/PrivateBin#118]
When I start PrivateBin, I see a field on top (apparently, it is a password field), but there are dots in it.
Why ? I did not fill in a password yet, this puzzles me.

I suggest to simply show a text "Please enter a password. This is recommended."

**Comment by rugk** [comment]
It might happen when you use a password manager and there you've saved a password (for another service) on the same domain.
You may use some unhide-password plugins or just use the browser console to view/edit the HTML code to make the password, which is actually entered there, visible. Maybe you know it, or can compare it. :wink: 

Please tell us your browser and version. (and what password manager you use)

**Comment by Wikinaut** [comment]
Firefox + FF Password manager (standard)

**Comment by Wikinaut** [comment]
Current behaviour of the password field should *not* happen.

**Comment by rugk** [comment]
Can you say us which domain you use? Are there other services running on this domain? Do you have a password saved in FF password manager?

**Comment by Wikinaut** [comment]
Yes, there are other services on the domain, and I do have password/s saved for the other services.

**Comment by rugk** [comment]
Then this is the reason. You may try to use [this password editor](https://addons.mozilla.org/de/firefox/addon/saved-password-editor) to edit the saved entries (e.g. edit the submit prefix or so), so that they won't show up in PrivateBin.
Firefox just sees a password field in PrivateBin and fills in your password.
However AFAIK currently there is no good workaround or solution for this. The only thing we could do is to use a usual text field instead of a password field in PrivateBin, so the password field is not recognized. We could imitate the behaviour of a password field through.

**Comment by Wikinaut** [comment]
@rugk wrote
> to use a usual text field instead of a password field in PrivateBin, so the password field is not recognized. We could imitate the behaviour of a password field through.

This is what I suggest. (Later I would be able to participate actively to the project, currently I cannot.)

**Comment by rugk** [comment]
It is certainly possible, but it is a not-so-nice (& kinda hackish) workaround. Anyway PRs are of course very much appreciated.

**Comment by Wikinaut** [comment]
But I hope you agree that a prefilled-with-a-really-secret-login-password-for-that-domain is a NOGO.

**Comment by rugk** [comment]
It is certainly not nice and a fix would be appreciated, but it is also not directly our responsibility. A proper way to fix this, would be to fix Firefox' password manager, so you could maybe open a bug report on Bugzilla or so.

For now this issue is a rare case scenario. If the server you use is self-hosted, you can e.g. also avoid it by installing PrivateBin in a subdomain (`privatebin.mydomain.example`) instead of `mydomain.example/privatebin` e.g. Then your saved passwords should only be valid (& therefore autofilled) for `mydomain.example` (and not `mydomain.example/privatebin`).

**Comment by Wikinaut** [comment]
(title is perfect, ty)

**Comment by Wikinaut** [comment]
Domain tip is nice, but too complicated, because it requires a new (amended) Let's Encryp certificate.

I will try to find a better solution and then present a PR.

**Comment by rugk** [comment]
Nice, that you look into creating a PR for it. :+1: 

As for LE: You can include new domains in your LE certificate at any time (you just have to be able to verify them), so this is actually quite easy.

**Comment by Wikinaut** [comment]
@rugk ty regarding LE. I _do_ know this, and regularly add new and new subdomains to my LE certs. For PrivateBin I don't want to add a new subdomain, we need to find a simple solution for the password field. Perhaps it is as simple as running a jquery live event which simply empties this field onload()

**Comment by Wikinaut** [comment]
Something onload() will be fine, I am sure.

**Comment by rugk** [comment]
Good idea! I would accept this workaround as it is really small.
Maybe we might test it with other password managers through.

**Comment by elrido** [comment]
Guys, sorry, but this is clearly an issue with your client setup, not something we need to solve in PB at all. Please don't introduce needless JS complexity for corner cases like this. That only introduces risks that it will fail for other types of clients.

There once was the autocomplete attribute that could be set to "off" for input fields that should not be filled up automatically. This would be a clean(ish) workaround except that most browsers started to ignore it for safety concerns. Here is Mozillas thoughts on the case, note the last few paragraphs explaining why they started to ignore it:
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by rugk** [comment]
In MDN site, there is at least a thing explained, which might work:
> If an author would like to prevent the autofilling of password fields in user management pages where a user can specify a new password for someone other than themself, autocomplete="new-password" should be specified, though support for this has not been implemented in all browsers yet.

@elrido Do you really think a simple `onload()`, which cleans the input (if it is filled) would be bad?

**Comment by Wikinaut** [comment]
@elrido @rugk here's something (not yet tested, but will do so)

https://stackoverflow.com/a/26114274/731798

and below

```
You can use JQuery, select the item by id:
$("input#Password").attr("autocomplete","off");

Or select the item by type:
$("input[type='password']").attr("autocomplete","off");

Or also:
You can use pure Javascript:
document.getElementById('Password').autocomplete = 'off';
```

**Comment by rugk** [comment]
Instead of adding the autocomplete field via JS, why not just add it to the HTML code? As mentioned before you may also try `autocomplete="new-password"`.

In any case, feel free to create a PR. We can then discuss whether/how we can accept this change in practise. A practical implementation always allows for better trade-offs between "bad workaround" and "this fixes an issue".

**Comment by Wikinaut** [comment]
Indeed I added `autocomplete="new-password"`in /privatebin/tld/bootstrap.php (and I do see the changed html) but this does **not** work with FF ESR 45.4.0 (current debian8 version).

**Comment by Wikinaut** [comment]
(By the way, I found https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion quite interesting, and can understand their reasons, but don't know if this was a correct decision.)

**Comment by mathroc** [comment]
> However AFAIK currently there is no good workaround or solution for this. The only thing we could do is to use a usual text field instead of a password field in PrivateBin, so the password field is not recognized. We could imitate the behaviour of a password field through.

what about [not even imitating the behavior of a password field](https://www.nngroup.com/articles/stop-password-masking/) ?

**Comment by elrido** [comment]
That's a really old flame war your threatening to open there... :wink: 

Security wise it would be better to have an invisible input without feedback. This way the guy looking over your shoulder really has to look at the actual keys typed in and can't even deduct how many characters you typed in (see password inputs in many UNIX systems for example).

On the other hand you have the usability advocates who propose to eradicate hidden inputs entirely (as in the example you pointed to).

This is not our battle. We provide the HTML standard type form element that carries the semantic for security related credential information (aka input field of type password). How a specific client chooses to interpret and display this to the user should not be our concern. It is legitimate for a user to modify his browser in both ways, hide the keyboard input completely or display it without obfuscation. This should be the users choice (via selection of a specific browser or use of a plugin) and not something we need to force on all users because we know better.

**Comment by rugk** [comment]
Indeed this battle is quite out of scope of PrivateBin. There are add-ons and stuff you might use to unhide passwords if such a "guy looking over your shoulder" is not in your threat model.

So let's just come back to the original issue, which is not opinion-based, as it is a UX bug happening under specific conditions. @Wikinaut Did you found any reasonable workaround, except of [just using usual text input fields](https://github.com/PrivateBin/PrivateBin/issues/69#issuecomment-255531303) - which is semantically ugly?

In general as https://github.com/PrivateBin/PrivateBin/issues/69 shows we are inconsistent with this thing anyway. I don't know if the JavaScript popup is/can be a special password popup (and the password is just not hidden there). If not we would semantically violate the "password input" there as we do not specify it as a password input.

**Comment by Wikinaut** [comment]
@rugk Today I git pulled the latest HEAD from the master branch, which did not work, so I am currently disappointed about the code quality. Well, this is off-topic for this issue.

I failed to find a fix in the HTML, so I have to use some jQuery tricks, but I have to learn how to change the js files for PB. Give me some time. My current view is, that the best method will be "emptying when the page is fully loaded" (much better than to use text input instead of password input).

I know how to submit PRs.

**Comment by rugk** [comment]
What exactly did fail when git pulling? Currently the latest head is not signed, which is a problem as we used GitHubs web interface for merging pull requests. I'll sign it soon.

Also this has nothing to do with the code quality.

For how to change the JS files, please see https://github.com/PrivateBin/PrivateBin/wiki/Development#subresource-integrity-for-javascript-resources.
For developing/debugging you can also just remove the hashes in the HTML files.

**Comment by Wikinaut** [comment]
@rugk I installed https://github.com/PrivateBin/PrivateBin/commit/b80665cc45bb8b86e7ad2b8e8a9b3eb3a3acdfbb . The PB page started, but only a few elements were shown, all form elements (checkboxes, password and text inputs) were missing. I went back to https://github.com/PrivateBin/PrivateBin/commit/bc9bb7eeca34c24486ae74fa4e062587ed1c8504

**Comment by rugk** [comment]
You're absolutely, right. In https://github.com/PrivateBin/PrivateBin/commit/b80665cc45bb8b86e7ad2b8e8a9b3eb3a3acdfbb the JS file was changed and therefore the SRI hashes were invalid. I've fixed this in https://github.com/PrivateBin/PrivateBin/commit/5d822af5b10f4c78bda7da9e76eb62d8d3a79e0f. Also the latest commit is now signed.

Sorry for the inconvenience, but such things can happen in `master` as this is the development branch. In production systems, you might rather use a stable [release](https://github.com/PrivateBin/PrivateBin/releases).

BTW until we either get a solution (as some have been proposed already) or we can assure that none of the proposed solutions work, I'll reopen this issue.

**Comment by rugk** [comment]
BTW a very easy workaround is to add another account for the same domain to Firefox password store. Then Firefox cannot autofill the password there as it does not know, which account to use.

**Comment by Wikinaut** [comment]
@rugk in case of wrong SRI hashes: can we please show an error messge then ?

**Comment by rugk** [comment]
That's not easily possible. SRI is a browser-security feature and blocks any JavaScript before it is executed, so it would be difficult to do so. Please post any ideas and further discussion for this, to https://github.com/PrivateBin/PrivateBin/issues/103.

**Comment by Wikinaut** [comment]
This is my recommended fix for the issue:

https://github.com/Wikinaut/PrivateBin/commit/deec561cc0d4961616596e34e5f178f55b1e6dd2

**Comment by rugk** [comment]
Just FYI:  The implementation of `new-password` in Firefox is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1119063
One may vote for this issue when you want it to be completed.
