### ISSUE TITLE
Burn after reading triggered on URL preview in third party applications and spam filters/virus scanners

### ISSUE THREAD

**Issue by wzoet** [PrivateBin/PrivateBin#1185]
## The problem
More and more email clients like MS Outlook and also applications like MS Teams etc. check the URL to perform a sort of preview of the contents to the user in their UI. Also systems like Microsoft Defender open the url to check it for malicious content. This preview triggers the burn after reading mechanism, even with a password specified, causing the link to already be useless after pasting it in one of these applications.

## The solution
Although a lot of possible solutions are possible, my guess a simple button to click for the user to show his/her intent to reading the contents would suffice. 

## Alternatives
The current alternative is to not use burn after reading, but a short lived timespan in which the content can be opened more than once. This is ofcourse a security risk when sending sensitive data.

**Comment by rugk** [comment]
> This preview triggers the burn after reading mechanism, even with a password specified, causing the link to already be useless after pasting it in one of these applications.

It should not do that. They need to execute JS and we do have a block list included for such bots.
In addition we have an Apache blocking template:
https://github.com/PrivateBin/PrivateBin/blob/master/.htaccess.disabled

https://github.com/PrivateBin/PrivateBin/blob/master/js/legacy.js#L55-L65

So if you have a concrete evidence of a bot we do not block/that causes pastes to be burnt, please let us know.
Otherwise, for now I close it as a duplicate, as it is already implemented.

See https://github.com/PrivateBin/PrivateBin/issues/982#issuecomment-1261742320
https://github.com/PrivateBin/PrivateBin/issues/547

**Comment by rugk** [comment]
> a simple button to click for the user to show his/her intent to reading the contents would suffice.

As an optional feature a nice idea. This is tracked in https://github.com/PrivateBin/PrivateBin/issues/541.
