### ISSUE TITLE
Changing language invalidates URL of existing paste in browser

### ISSUE THREAD

**Issue by rric** [PrivateBin/PrivateBin#1191]
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Create a new paste; "English" is selected in the combo at top right of the page
2. Press "Send", get a link: https://privatebin.net/?2a7bea9817c47814#A3WdsTpYXocSAKMdFahpsDyKMmGvzQWUw5tEDaFhe2Mu
3. Re-start browser, enter link above; everything works fine
4. Change language to another one, e.g. "Deutsch" (or, just press "English" again)

### What happens

The URL in the address bar gets shortened to https://privatebin.net/?2a7bea9817c47814# (i.e. the part after `#` is skipped), and a message is displayed:

Cannot decrypt paste: Decryption key missing in URL (Did you use a redirector or an URL shortener which strips part of the URL?)

### What should happen

I am not sure whether this behaviour is intended; but imho it should be possible to read an existing paste eben if one changes the language of the ui.

## Basic information

**Server address**:

https://privatebin.net/

**Browser:**
Firefox 119.0, Edge 118.0.2088.76

**PrivateBin version:** 1.6.0

**Comment by rugk** [comment]
Oh I can confirm there is definitively a bug in the language selector that it misses the encryption key.

However, _be aware_ that in case you have a self-destroy paste, it _still_ will be deleted as currently the site is reloaded when you click the language picker.

So the short-term bug should be fixable quite easily. Long-term would be a good idea to make it possible to change the language without reloading (but maybe that is also not _that_ important).

**Comment by elrido** [comment]
> A feature I liked about d-note [...] is that when you go to the secret URL, it will ask whether you want to read the note, warning that it will destroy the note.

I dig this idea, independent of fixing the issue caused by language selection.

Trying to iterate on it: How about only applying this to self destroying notes? We could have the client display that question only if there is a parameter appended to the hash to ask for loading the paste. This would allow us to add that param to burn-after-reading notes by default, while regular notes would still get instantly displayed. And you could also manually add it to existing paste-URLs.

You could then run an instance that asks even for regular pastes/discussions, allowing you to display some TOS like "by clicking yes, read note, you agree to follow our community guidelines and understand that topics like x, y & z may get discussed" via our notice option.

**Comment by rugk** [comment]
Yeah this has been tracked in https://github.com/PrivateBin/PrivateBin/issues/541 and technically kind of depends on https://github.com/PrivateBin/PrivateBin/issues/245 or az least that would make a good fit.

**Comment by antreos** [comment]
Hi, not sure if this is related but I suspect it is. I have deactivated the language selection in conf.php and use English as the language, also stored in conf.php. 
```
; by default PrivateBin will guess the visitors language based on the browsers
; settings. Optionally you can enable the language selection menu, which uses
; a session cookie to store the choice until the browser is closed.
languageselection = false

; set the language your installs defaults to, defaults to English
; if this is set and language selection is disabled, this will be the only language
languagedefault = "en"
```
If a German user now opens the link with the key, it seems like _(sometimes? it's not always the case not sure why)_ an automatic language selection is carried out, the user is led from the English to the German page and the paste can no longer be read (presumably because of the missing key in the redirect?). The error message is identical to the one in this report. I probably got around it by setting the language in conf.php to German (languageselection is still false) and thus triggering a "lang"-cookie that bypasses the behavior.

 If it is to be treated as a separate bug, I would take a closer look from mid-February and create a more detailed report with reproduction steps etc. It was quite tedious to find a workaround as I have thought my installation was faulty. 

Using version 1.6.0 / 1.6.2
