### ISSUE TITLE
FAQ "Why is it named" link broken

### ISSUE THREAD

**Issue by akshaybharwani** [PrivateBin/PrivateBin#1195]
Both links under [Why is it named PrivateBin?](https://github.com/PrivateBin/PrivateBin/wiki/FAQ/#why-is-it-named-privatebin) are broken. I tried to look for the concerned issue in this repo and original [Zerobin repo](https://github.com/sebsauvage/ZeroBin), but couldn't find anything related to it.
The link mentioned refers to this [repo](https://github.com/elrido/ZeroBin) but they don't have their issues visible publicly.

**Comment by rugk** [comment]
Ah yeah links are broken because @elrido disabled issues in the fork that was the base for this repository.. We could re-enable issues there (which I would have nothing against it) and then [archiving it](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories), so issues are no longer writable.

But to not get started on that discussion again what about quickly enabling it, saving it in archive.org and then updating the links?

I tried finding an existing capture in https://web.archive.org/web/20210119224035/https://github.com/elrido/ZeroBin/issues/79 and https://web.archive.org/web/20210223200729/https://github.com/elrido/ZeroBin/issues/79, but it is all 404.

**Comment by elrido** [comment]
All right, I give up on that[0]. I re-enable the issues (I wasn't happy disabling them in the first place, only to avoid anyone creating new issues ) _and_ archived the repo, so that we can keep these links read-only, preserving the public history of our fork.

Thank you @akshaybharwani for bringing this to our attention.

[0] [that](https://github.com/elrido/ZeroBin/issues/111#issuecomment-392347782) being to a) retain a link between ZeroBin and our fork for discoverability and b) me keeping an online backup of the project in case this repo ever gets vandalized or I otherwise loose control of it.
