### ISSUE TITLE
SRI error after upgrading due to caching

### ISSUE THREAD

**Issue by jason-weiser** [PrivateBin/PrivateBin#1207]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Update PrivateBin from 1.6.0 to 1.6.1 or 1.6.2:
```
sudo cp -R PrivateBin-1.6.1/* /var/www/privatebin/
sudo chown -R www-data:www-data /var/www/privatebin
```
3. Visit domain and find the text box unavailable

### What happens

The area to input text is gone.

### What should happen

You should be able to input text and submit a paste.

## Additional information

Screenshot:
<img width="971" alt="Screenshot 2023-12-06 at 12 43 53 PM" src="https://github.com/PrivateBin/PrivateBin/assets/59340427/3c87d7e0-d94a-48ad-937b-f7b633b7242c">

## Basic information

**Server address**: It's for personal use, so I'd rather not publish it.

**Server OS:** Debian 11

**Webserver:** Apache 2.4.56

**Browser:** Firefox 120.0.1. Of note, it *does* work normally in both Safari and Edge, just not Firefox.

**PrivateBin version:** 1.6.1 and 1.6.2. Reverting to 1.6.0 fixes the issue.

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment]
Hmm, what can we do in the future about that? Use [cache breakers in the file name](https://stackoverflow.com/questions/18323520/cache-breaker-as-query-parameter-vs-cache-breaker-in-filename) or somehow adjust the nginx caching?

**Comment by elrido** [comment]
> Hmm, what can we do in the future about that? Use [cache breakers in the file name](https://stackoverflow.com/questions/18323520/cache-breaker-as-query-parameter-vs-cache-breaker-in-filename) 

We already do that, the file is called zlib-1.2.13.js for that reason. I had not considered changing the name when I did the change in it, should have renamed it to zlib-1.2.13**-1**.js or something. Please help me remember this and comment on the merge requests.

> or somehow adjust the nginx caching?

We don't control the webservers of our users. We got affected due to having, purposefully, turned caching on in the nginx in our container image for the static site in front of the demo instance: https://github.com/PrivateBin/privatebin.info-pelican/blob/master/nginx.conf#L34-L36

For the demo image we now use the [unit one](https://github.com/PrivateBin/docker-unit-alpine), anyway, that doesn't contain a full fledged webserver anymore.

**Comment by rugk** [comment]
> should have renamed it to zlib-1.2.13**-1**.js or something.

Ah makes sense yeah, distros do that naming hm…

Then i see nothing we can do here, indeed.
