### ISSUE TITLE
Break the glass - get notified if someone uses the link

### ISSUE THREAD

**Issue by joachimdeboer** [PrivateBin/PrivateBin#1226]
## I want to know if someone uses the secret created

The idea is to store confidential information that only should be used in highly exceptional situations. Let's say getting some privileged access and the person who should give access is unavailable while the situation needs resolving now.
I then want someone to access the data, but we want to know the data was accessed to prevent abuse. Is this something that can be added to the system?

**Comment by elrido** [comment]
This would require introducing different user roles (creator, auditor, normal and privileged reader) and a permission system to enforce these, as well as managing this and the related sensitive data on the server side. The tool is currently designed to require as little knowledge (about contents and users) as possible on the server side, so introducing this would require some fundamental changes, both in server logic, paste format and protocols.

I don't think such a use case is compatible with the stated goal of this project. I would recommend you look at extending a "traditional" pastebin solution which stores the documents unencrypted and includes an online administration, which means that it already uses a permission system that you might be able to extend.

**Comment by rugk** [comment]
Actually, if we simplify the model, we already have two user roles: paste creator and paste consumer.

And your use case is solved in the following way:
1. As a paste creator also save the link you send to the paste consumer. (or just keep the browser window open as it is _that_ link)
2. Later, to check whether it has burnt, access _that same_ link again. If you can access it, it has _not_ been opened/burnt. If _not_ it has been burnt either due to being expired or being accessed.

Similarly, we could create a third link (paste access link + paste deletion link we already have) that just checks whether aa paste has been burnt and shows you that information – but without burning the paste itself.
(Could also probably be shown on the page itself or maybe even with a WebSocket connection as soon as it has been burnt. This would however, introduce some new technologies, but be quite a good UX IMHO.)

Would that satisfy your use case?
