### ISSUE TITLE
Add multiple SRI hashes

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#123]
I think we should also add the SHA-256 and SHA-384 hashes.
AFAIK browser will automatically use the "best" one they support, but in case a browser does not support particular algorithm it should fall back to a supported one.

See https://scotthelme.co.uk/subresource-integrity/#comment-2539733060

**Comment by elrido** [comment]
Why would you want to weaken the security and increase the HTML size so much? We already use sha512 hashes. Are there any SRI supporting browsers around that can't handle that?

**Comment by rugk** [comment]
It does not weaken the security and the few bytes seriously won't matter.
Also keep in mind SHA-256 is secure and if it would be broken we would have much more serious issues than SRI (TLS, ...).

> Are there any SRI supporting browsers around that can't handle that?

That's the question to ask. [So I did so](https://scotthelme.co.uk/subresource-integrity/#comment-2970091955).

**Comment by elrido** [comment]
These are not just a few bytes but 54 + 74 additional bytes per resource of which we have currently load 9. That 1152 additional bytes and you have so far advocated for increasing page load speed.

**Comment by rugk** [comment]
> you have so far advocated for increasing page load speed.

:laughing: Yes, but increasing compatibility is not bad either. We clearly need to weight them up, but for this we need some statistics.

**Comment by elrido** [comment]
I predict that there will be no browser with more then 5% market share that supports SRI, but not SHA-512 hashes. Why? Because all three hash types, SHA-256, SHA-384 and SHA-512 are based on the [SHA-2 algorithm](https://en.wikipedia.org/wiki/SHA-2).

Any library supporting SHA-256 will also provide SHA-512. If a browser would support SRI without SHA-512, the programmer responsible for this would have to deliberately disable the support for it in the code (or use very crude parsing looking only for a fixed string pattern).

Hence my arguments against this:

1. It will not improve any compatibility.
2. It actively reduces security as it introduces the risk for a downgrade due to erroneous SRI implementations.
3. It increases the size of the response, slowing down the site.
4. Oh, and it introduces the risk, that for some reason the hashes for a resource get out of sync which then could potentially cause odd problems as some browsers might start to check multiple hashes (processing power is cheap).

**Comment by rugk** [comment]
You might be right, but I'd still interested in facts. Only hard facts are good facts.

**Comment by elrido** [comment]
Then please check the facts, investigate the sources of at least Chrome and Firefox and run the tests against Edge and report your results back here, please. Thanks.

**Comment by rugk** [comment]
So as [stated here](https://github.com/mozilla/srihash.org/issues/155#issuecomment-259800503):
> >Do not all browsers support SHA-512 or SHA-256 e.g.?
>
> They all do, it's required by the spec. The support for multiple hashes is in the spec for backward-compatibility once we introduce new hash algorithms (e.g. SHA3).

Therefore I think we can close this PR.
