### ISSUE TITLE
1.7.2 / valid to / paste lifetime / lease time / always 23 hours

### ISSUE THREAD

**Issue by un99known99** [PrivateBin/PrivateBin#1309]
the valid to is not kept, despite set lifetime to 5mins it will always say "vaild to 23hours", checked with 1.7.1 - here it is working

**Comment by elrido** [comment]
This affects the bootstrap (3) template - I had a similar issue while working on the bootstrap5 one and in fixing that must have introduced this regression. I'll have a public holiday coming up, so hope to have something ready for the weekend.

**Comment by rugk** [comment]
Hmm could we somehow push back the release/stop it from deployment for now?

**Comment by rugk** [comment]
Added a note on github for now.

**Comment by rugk** [comment]
Hmm tried a quick look through the code to maybe spot an issue [but the diff is huge](https://github.com/PrivateBin/PrivateBin/compare/1.7.1...1.7.2) and the only change related to paste self-deletion/expiration/lifetime that comes to my mind is https://github.com/PrivateBin/PrivateBin/pull/1295 – maybe the creation date (`postdate`) somehow was used to calculate the expiration date and this is somehow broken now? (Because it is removed too early?)

Of course if curious people wanted to contribute [a git bisect](https://stackoverflow.com/questions/4713088/how-do-i-use-git-bisect#4714297) finding/telling the bad commit would be very much appreciated. We know good=v1.7.1 and bad=1.7.2 for sure. Anyway, needs manual testing _and_ probably even with git bisect some steps hmm…

**Comment by elrido** [comment]
I'm pretty sure that this is due to the bootstrap5 template, because I had this exact issue in the new template, then "fixed" the drop-down update mechanism and it now works for bootstrap5 and page, but no longer for bootstrap (3). I'll work on it today and would like to release a hotfix by the weekend. If I can find the time I'd also like to apply a first round of improvements that got suggested for the bootstrap 5 template (OT, sorry).

**Comment by Ozwel** [comment]
Shouldn't 1.7.2 release be removed? It's currently spreading. Admins may not notice the bug and may not check updates for a while.

**Comment by elrido** [comment]
> Shouldn't 1.7.2 release be removed?

We have never considered the process of removal of a release. In the past, under such circumstances, we simply released a fix-release (if necessary even with backports) but stuff is always already out there.

It is unfortunate that we only got this reviewed too late for me to do the release yesterday afternoon. Our spare time to work on these passion projects is, unfortunately, limited. I now have a busy work week in front of me and don't know if I can find the time to release some evening, I'll try but can't promise - worst case, the release occurs next Saturday.

I'm also not quite clear what counts as sufficient for "removing": Just put the release page back to draft? Also untag? Hide the master branch? Also delete the container images that already got downloaded and are on peoples machines? What about the next release number: 1.7.2 (again) or 1.7.3? In the first case, how to distinguish between buggy and fixed release? In the second case, how to account for the "missing" release?

In light of such questions and their complex answers, and especially in light of all the maintainers' very limited time to spend on this project, I'd prefer focusing on fixing issues than coming up with more processes.

**Comment by Ozwel** [comment]
I do completely understand. That was a bad suggestion.
And thanks for your time.

**Comment by rugk** [comment]
It's not inherently a bad suggestion, but as @elrido said, it's just a process we never thought/discussed about and had no procedure. As such, I have opened https://github.com/orgs/PrivateBin/discussions/1334 for a lessons learned. I tried to describe the whole history of that bug, from how it got introduced until how it got fixed…

**Comment by un99known99** [comment]
test with version 1.7.3 was fine, working as expected, many thanks for the quick fix!

**Comment by Ozwel** [comment]
1.7.3 works fine for me, also tried with custom retention times.
Thanks for the responsiveness.
