### ISSUE TITLE
Feature Request: Rephrase the WebAssembly error on unsupported browsers

### ISSUE THREAD

**Issue by Sommerwiesel** [PrivateBin/PrivateBin#1310]
## The problem
On unsupported browsers privatebin shows:
"Error decompressing paste, due to missing WebAssembly support".
This could be more clearer, currently people trying to view pastes might think the server is broken or something.

## The solution
Rephrase to:
"Error decompressing paste, your browser doesn't support WebAssembly. Please use another browser to view this paste."
Much better UX as it provides the user with a clear call to action that will lead to him being able to open the paste.

Note: Made a stupid typo in the first PR, have closed and opened a new PR, sorry.

**Comment by rugk** [comment]
> Note: Made a stupid typo in the first PR, have closed and opened a new PR, sorry.

Note that you do _not_ need to open a new pull request (PR), when you push new changes. You can just push it into [the same branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches) of your PR (in your [fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks)). The pull request will then be updated.

And BTW: Next time, try to avoid doing a pull request from the main branch, because you can run into problems when you have a "non-clean" main that does not follow this repo here (i.e. "upstream"). [See this article for details](https://help.github.com/en/articles/proposing-changes-to-your-work-with-pull-requests). Anyway, this is only a tip for the next time. :smiley:
