### ISSUE TITLE
bs5 text wrapping in menu bar instead of collapsing

### ISSUE THREAD

**Issue by abulgatz** [PrivateBin/PrivateBin#1317]
**Did you use the FAQ section?**
- [X] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Load PrivateBin with Bootstrap 5 theme in Firefox
2. Resize the window width so it is narrow but the menubar doesn't collapse into a hamburger

### What happens

The text in the buttons and inputs wraps onto multiple lines, making the menubar taller.

### What should happen

The menubar should collapse

## Additional information

I recommend adding the css class `.text-nowrap` either to the top-level `<nav>` element or to each of the the inputs in the `<nav>` to fix this issue.

Current menubar:

<img width="982" alt="image" src="https://github.com/PrivateBin/PrivateBin/assets/1438193/dddc95fb-b032-45fb-a6d1-8974950ab799">

After adding `.text-nowrap` to the `<nav>`: `<nav class="navbar navbar-expand-lg bg-body-tertiary text-nowrap">`:

<img width="983" alt="image" src="https://github.com/PrivateBin/PrivateBin/assets/1438193/775ba984-99db-4fc0-b48f-405c7fd8c180">

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:** Firefox 125.0.3

**PrivateBin version:** 1.7.2

I can reproduce this issue on <https://privatebin.net>: No, as it is not using the new preview bootstrap 5 theme

**Comment by elrido** [comment]
Thanks, I've noticed it during development, but didn't figure out how to solve it. Assumed thats what they (bootstrap) had decided it is supposed to look like. The nowrap class probably got provided for good reasons.

**Comment by Ilav1** [comment]
Sorry for reopen the issue. There is more potential in bootstrap5 template. I recognised that the buttons are much bigger in bootstrap 5 theme so there are less informstion than before.

Here is an example of bootstrap 5 vs old designe taken on 10'' tablet.

![Screenshot_20240518-223938_Fennec_1_1](https://github.com/PrivateBin/PrivateBin/assets/102852954/13660e53-8204-4aec-b3dc-a6f069b61cd8)

![Screenshot_20240518-223923_Fennec_1](https://github.com/PrivateBin/PrivateBin/assets/102852954/f8fd6caf-95f6-4131-952d-94539f982e34)


At first, the checkboxes are not good to see, they should be darker in ligtheme.

You cant read or even see the password box or what kind of formate the paste is. The burningtime also isnt readable.
Maybe some options can go to a sidebar like in mobile view when the display gets smaller so that more and more options are switching to a dropdown menue. I dont know if its possible...

I think there should be an symbol in the grey new button shouldnt it?

**Comment by elrido** [comment]
Reg. the missing symbols, check the CSP setting of your instance. I left a comment in the con.sample.php on needing to relax the rule to get the symbols to display correctly:

https://github.com/PrivateBin/PrivateBin/blob/a0e42aae9e0935187c043acd5c16a4ec966aebdb/cfg/conf.sample.php#L98-L99

For the display of the buttons, these do look quite different, space-wise, in bootstrap 5. I personally also don't like the "flat" look. I'm more than happy to change them using the bootstrap CSS provided classes, but want to avoid introducing too much custom CSS, which will be on us to maintain.

And just to check - Are you really looking at a 1.7.3 instance, which contains the above discussed improvements? It should now look like this:

![1.7.3 improvements](https://private-user-images.githubusercontent.com/1017622/329314313-6f2bf3ee-5555-428c-b021-0ec52cc6d384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwOTI0OTUsIm5iZiI6MTcxNjA5MjE5NSwicGF0aCI6Ii8xMDE3NjIyLzMyOTMxNDMxMy02ZjJiZjNlZS01NTU1LTQyOGMtYjAyMS0wZWM1MmNjNmQzODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMDQxNjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzk4NDE4YTFhMmFkNWI0ZTU3NDE5MDllNzdlMjE4NmRmOTdiNGZjMzdjZTMyMjI0YjI4YjlmOTExMjQ5ZWJhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iyUAOGysRydNKDur8lkYxvYW5AQTdWQ-gVTElMQLy4E)

What is also weird in your screenshot is that it looks like you enabled dark-mode, but it is clearly the light-mode that it displays.

**Comment by Ilav1** [comment]
Ok I don't read the info about the icons. Thanks for the informations works fine now.

The other screenshot was not 1.7.3 it was 1.7.1.

At least I like the bootstrap 5 designt because you can switch from light to dark mode but I don't like the look on medi / small displays.

Even on a laptop, when you open privatebin 1.7.3  the input field is so big you have to scroll down to see the footer. When I open the old theme I see everything without scrolling. Isn't it possible to set the input field with footer as big as the screen? When you have longer paste you may expane the input field.

**Comment by elrido** [comment]
Reg. the textarea height, we seem to have gotten some tools in bootstrap 5.3 that help with sizing relative to the viewport: https://getbootstrap.com/docs/5.3/utilities/sizing/#relative-to-the-viewport - we probably needed something like 75% or 80% or such and maybe only set these for larger screen heights? Anyhow we should probably move that into a new issue. Could you create a new issue with subject "bs5 textarea height" so we don't forget? I'll try and experiment with it over the weekend.
