### ISSUE TITLE
Could not create paste: Error saving paste. Sorry. (1.7.2 and later)

### ISSUE THREAD

**Issue by bikmaek** [PrivateBin/PrivateBin#1337]
**Did you use the FAQ section?**
- [x ] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce
Open the PrivateBin web UI
Click on the blue "Send" button

### What happens
Error occurs: Could not create paste: Error saving paste. Sorry.

### What should happen
Paste should be created

## Additional information
![Unbenannt](https://github.com/PrivateBin/PrivateBin/assets/70565176/2bcf7221-9a71-44a1-8d8a-da4a62f0afe5)

## Basic information

**Server address**: https://devpb.pc-sam.net (1.7.3) - same installation but working: https://pb.pc-sam.net (1.7.1)

**Server OS:** Rocky Linux 8.9

**Webserver:** Apache

**Browser:** Chrome/Edge/Firefox

**PrivateBin version:** 1.7.3

I can reproduce this issue on <https://privatebin.net>: No

**Comment by brunob** [comment]
Same on https://bin.infini.fr/ tested also with bootstrap & bootstrap5 themes. I don't get any error in php logs with `error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT` same with `error_reporting = E_ALL`

We use MySQL to store pastes. I've checked folder permissions and also made a clean of corrupted pastes found by `bin/administration - s`.

Bug seems also present on https://pbinka.duckdns.org/

**Comment by rugk** [comment]
Did you check the (file system) permissions are correct? Also was this a fresh installation or an update, given you mention a different older instance?
See also previous similar issues: https://github.com/PrivateBin/PrivateBin/issues?q=is%3Aissue+Error+saving+paste+is%3Aclosed It's usually a permission problem.

**Comment by bikmaek** [comment]
> Did you check the (file system) permissions are correct? Also was this a fresh installation or an update, given you mention a different older instance? See also previous similar issues: https://github.com/PrivateBin/PrivateBin/issues?q=is%3Aissue+Error+saving+paste+is%3Aclosed It's usually a permission problem.
> 
> In general what is the setup? Docker?

Hi rugk,

thanks for your information - but I don't think that it's a permission problem. - as soon as I copy the old files it's working (same file/data-owner - 4 sure!!!) - as soon as I put the 1.7.3 files - the error occurs. Therefore I created a dev-subdomain to test a lot. 

- 1.7.1 - working -> replace by 1.7.3 files: not working
- 1.7.3 new installation - not working -> replace by 1.7.1 files: working again
- 1.7.1 new installation - working -> replacing files by 1.7.3 files: not working

if you have any other ideas - I'm ready to check it!

unfortunately there are **no** entries in the logfiles - it's like searching in the dark without any light...

It's installed in a "classic" environment - server configured with plesk - nginx proxy -> apache - with php 8.3.7 and MariaDB database

**Comment by brunob** [comment]
Same here, no docker, permissions and owners checked, and also a config with nginx proxy / apache with php-fpm 8.1 and a mariadb database.

**Comment by elrido** [comment]
Since you guys mention using a database backend: Have you seen [this topic in the 1.7.2 release discussion](https://github.com/orgs/PrivateBin/discussions/1308#discussioncomment-9328673)? In short, either:
- ensure your database user has permissions to upgrade the schema
- or perform the schema & version upgrade manually (this is the safer choice, but more tedious)

We do rarely change the schema, but the 1.7.2 release contained a cleanup of an unused column in one of the tables. The last time a release contained a schema change was with 1.3. Therefore I would not necessarily advise you to add a GRANT to your user, just be aware of this and check the [doc/Installation.md](https://github.com/PrivateBin/PrivateBin/blob/master/doc/Installation.md#using-a-database-instead-of-flat-files) for any changes in the database area upon upgrades.

You should have gotten a PDO exception thrown, though, and logged somewhere. If it didn't end up in your usual webserver or PHP error logs, maybe it bubbled up into journalctl or primary syslog file?

**Comment by bikmaek** [comment]
hi @elrido - this solved my issue!

I changed the title - for other ones that doesn't read the 1.7.2 release discussion 👍 

thanks!

**Comment by RedAISkye** [comment]
> Since you guys mention using a database backend: Have you seen [this topic in the 1.7.2 release discussion](https://github.com/orgs/PrivateBin/discussions/1308#discussioncomment-9328673)? In short, either:
> 
>     * ensure your database user has permissions to upgrade the schema
> 
>     * or perform the schema & version upgrade manually (this is the safer choice, but more tedious)

Hi, I have ensured it has all privileges but I'm still getting the same error, this wasn't an issue before the upgrade.
