### ISSUE TITLE
Error saving paste. Sorry. since 1.7.3 (database storage) - don't forget to reset your table paste

### ISSUE THREAD

**Issue by touchweb-vincent** [PrivateBin/PrivateBin#1348]
Hello,

It's not a bug report, it's just an information for those who will face this lovely error : Error saving paste. Sorry. with the database storage.

If you upgrade your PrivateBin since years, without reseting your database, the upgrade 1.7.3 will break your PrivateBin because of (probably - do not have time to check) this : https://github.com/PrivateBin/PrivateBin/commit/99a3e087ed9737e237ad8d93184c9c0c15a10748

You just have to delete the table "paste", then it will be auto-recreated by PrivateBin.

You can see what happens by editing lib/Data/Database.php - line 189 : 

        } catch (Exception $e) {
            var_dump($e->getMessage()); // To make it verbose.
            return false;
        }

SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn&#39;t match value count at row 1

Hope this will help some folks in the wild.

Have a good day

Vincent

PS : A debug mode would be awesome

**Comment by elrido** [comment]
The commit 99a3e087ed9737e237ad8d93184c9c0c15a10748 is not part of the release 1.7.3.

The error you got, "Column count doesn't match value count at row 1", is because your database did not get upgraded (automatically) after you upgraded to 1.7.**2**.

The commit you mention will resolve the problem that upgrades will get performed even when skipping versions. For example, if you upgraded from 1.7.1 directly to 1.7.3, the auto-upgrade would not get triggered and you would get the error.

The manual upgrade procedure can be found discussed in:
https://github.com/orgs/PrivateBin/discussions/1308#discussioncomment-9328673
