### ISSUE TITLE
Bootstrap-dark has ugly style for 'source code' format

### ISSUE THREAD

**Issue by smktpd** [PrivateBin/PrivateBin#1359]
<img src="https://i.imgur.com/jQYPYc0.png">

1. https://github.com/PrivateBin/PrivateBin/blob/master/css/prettify/prettify.css ends with `li.L1,li.L3,li.L5,li.L7,li.L9{background:#eee}`
which is used to make background striped (making odd and even lines distinct from each other)
But #eee is too whitish, hurting eyes. IMO it needs to be changed to asphalt color.

2. text color for classes `.kwd`, `.pln` and `.typ` (words `class`, `Test` and `println`) is barely readable on dark background.

**Comment by elrido** [comment]
Is this by any chance the flip side of the issue described in #1354? Could you try the configuration change from: https://github.com/PrivateBin/PrivateBin/issues/1354#issuecomment-2158000535 , please?

For reference, here is how it should look like, if you have no `syntaxhighlightingtheme` set:

![PrivateBin, bootstrap5 template, no syntaxhighlightingtheme set](https://github.com/PrivateBin/PrivateBin/assets/1017622/06b6888e-9a70-4eef-89e0-7d4d6cd972b8)

**Comment by smktpd** [comment]
I use `template = "bootstrap-dark"`.
Thanks for providing a solution, with `syntaxhighlightingtheme = "sons-of-obsidian"` it looks better:
<img src="https://i.imgur.com/izwXE5X.png">

I think there either needs a better note in the config file that `template` and `syntaxhighlightingtheme` need to be changed in pairs and provide some compatible pairs.

**Comment by elrido** [comment]
Well, we do want/need to replace the current syntax-highlighting solution sooner or later, as the current one has been unmaintained for years (though we have no evidence that there is any problem with it), so I would rather not invest into changes of the current one, especially not for the bootstrap(3) template that we want to deprecate within a year or so.

For the bootstrap5 one I had to set up an automatic solution, because the dark-mode toggle allows to switch without reloading the page, so we can't wait till the page gets reloaded and new css injected.
