### ISSUE TITLE
Bug: Plain Text with xml

### ISSUE THREAD

**Issue by Pofilo** [PrivateBin/PrivateBin#137]
## Steps to reproduce

1. Create a new paste, sometimes xml content will not appear using the plain text mode
2. Using [this paste](https://privatebin.net/?7529cb5818dc4c79#CGr6pUAQ5PyJrtIrROc8LVdVTwgCf42gcsrib+PiBFs=), if you click on `Plain Text`, you will only see 1 word

### What happens

The text doesn't appear.

* I can reproduce this issue on <https://privatebin.net>: **Yes**

**Comment by elrido** [comment]
Hi and thanks for tracking this.

Originally when clicking the "Raw" button, the document was returned as plain text (mime type text/plain), but this was [changed due to a bug](https://github.com/PrivateBin/PrivateBin/commit/daf5522b1ec164abde735f15cb8874f1027a9466) in the Chrome browser that would execute JS if you would hit "refresh". We now return a set of `<pre>` tags containing the string as HTML (mime type text/html) which avoids this. I had also [added a comment](https://github.com/PrivateBin/PrivateBin/blob/3f2de319f38070bd3e8a409a099104a0940494c6/js/privatebin.js#L1274) to explain the reason we are doing this and why it happens:

            // we use text/html instead of text/plain to avoid a bug when
            // reloading the raw text view (it reverts to type text/html)

We need to make sure HTML entities are properly converted. Maybe we could use [jQuery .text()](http://api.jquery.com/text/) for this? Or would something like this be enough?

  String(paste).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

**Comment by rugk** [comment]
> String(paste).replace(/&/g, '&').replace(/</g, '<').replace(/>/g, '>').replace(/"/g, '"');

Oh, oh, oh. Please don't do such tinkling here. HTML escaping is much more complex and this should be done by well-tested implementations to avoid XSS issues. So jQuery would certainly be fine.

Has anyone tested whether the original bug in Chrome/ium is still valid? Because I think that this is certainly a bad bug in Chrome and not in PrivateBin, so maybe it is already fixed and we could switch back to text/plain.

**Comment by elrido** [comment]
I remembered that we already have a function in there for this case and applied it. Thanks again for reporting!
