### ISSUE TITLE
[idea] Browser extension

### ISSUE THREAD

**Issue by gjedeer** [PrivateBin/PrivateBin#138]
Feel free to close this as a WONTFIX, I don't have the time to implement it myself and it's likely out of the scope of this project. But here it comes.

I've been wondering what to do about the "But JavaScript encryption is not secure!" part of the FAQ. I believe the biggest issue is the integrity of Javascript files, partially solved with SRI. The remaining part of this problem is placing trust in the server operator.

This could be mitigated by creating a browser extension checking hashes of JS files, if PrivateBin is detected. The extension would:

1. Check the "integrity" attribute of script tags and compare them to official PrivateBin releases
2. Warn about unknown scripts included in index.js

The official list of file hashes could eg. be published in the Github repo as a signed JSON file and the extension would periodically refresh that file.

-------

A second - less elegant solution - might be to serve all scripts from a CDN and ask the [Decentraleyes](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/) developer to include them.

**Comment by rugk** [comment]
Both are nice ideas - in theory.
Actually the browser extension idea has already been proposed in https://github.com/elrido/ZeroBin/issues/8.

In theory it should be doable, but the add-on also must be updated *before* the PrivateBin instance is updated. We could of course do so by delaying the PrivateBin update a bit and first updating the hashes in the add-on.
Of course it would be no solution if the add-on auto-updates the hashes e.g. from privatebin.info. (maybe unless we sign the hashes with a gpg key)

Another thing which the add-on has to check is the CSP header. Because if it does not validate it too, JS could just be added as inline-code. And the add-on has to make sure that all script tags have an integrity attribute (could be done with https://github.com/PrivateBin/PrivateBin/issues/82 if implemented).

I think it would be a nice contributor task to create such an add-on. If anyone is interested in this, please comment in this issue.

**Comment by gjedeer** [comment]
The addon could re-download the hashes if the visited site fails the check. This would eliminate the "just updated" issue.

And yeah, the hashes need to be signed - i proposed that.

CSP would be a nice addition, but wouldn't just checking all <script> tags be enough? unknown src or no src (inline code) = warning.

**Comment by gjedeer** [comment]
I just made a working proof-of-concept. It has found all the tampering attempts I could think of.

https://github.com/gjedeer/PrivateBin-webextension/tree/master

It has hard-coded list of hashes because I could not make it download a file. Also no signature checking mechanism for the same reason.

Personally it was a good reminder on why I hate Javascript programming :) But if somebody wants to develop it into an usable product, they're welcome to fork it.

**Comment by rugk** [comment]
Nice, I'll look into it later.
@elrido can we move/fork it to the PrivateBin repo?

BTW nice you're using web extensions as this will work in both Firefox and chrome.

**Comment by gjedeer** [comment]
Actually I just implemented refreshing and PGP sig checking.

**Comment by elrido** [comment]
Hello @gjedeer and thanks for you work. I've [created the repo](https://github.com/PrivateBin/WebExtension) and invited you as admin to it.

**Comment by rugk** [comment]
I've imported your repo.
I think we should track the process in the new repo now, thus I am closing this issue here.

**Comment by gjedeer** [comment]
Thanks!

**Comment by rugk** [comment]
BTW there is something, which we could sue instead of inventing our own wheel here. This is based on PGP-signing the whole page: https://github.com/tasn/webext-signed-pages

However, (I have not looked into it exactly), but it seems to verify the whole HTML. That would make changing the page template impossible…

**Comment by elrido** [comment]
That would not just be a problem with the page template. All our templates change their content depending on the configuration settings or what features the paste was created with.

**Comment by rugk** [comment]
Currently, yes. At least the paste stuff is going to change, see https://github.com/PrivateBin/PrivateBin/pull/216. In such a way the homepage could be changed, too, for the other configuration options.
Created https://github.com/tasn/webext-signed-pages/issues/7 for the basic issue, BTW.

**Comment by rugk** [comment]
BTW the result of https://github.com/tasn/webext-signed-pages/issues/7 was: CSS is dangerous too. It makes no sense to only verify JS, but not CSS.

At most we could support two or three templates and maybe add options for customizing the colors…
Or we would need a way for other's to submit their changed CSS/templates to us, we verify them and sign them… :laughing: 

Actually that last thing would be possible. Actually we could have a public repo for this, so everyone can verify it and we have a log at what we signed and what we did not.
We could require a documented process (i.e. you need a public test instance, submit the source code, …)

It's just cumbersome for the template modifiers, but they could always host an "unofficial" version of PrivateBin, which is not signed. Of course, updating PrivateBin then can get bad, but maybe we need proper pre-release versions then. (and keep care we stay as compatible as we can)

**Comment by rugk** [comment]
So I finally abandon the idea of our own browser extension. Supporting https://github.com/tasn/webext-signed-pages will likely be better…

**Comment by gjedeer** [comment]
Yeeah! Glad that someone made a generalized solution. This extension + SRI = win.

**Comment by MurzNN** [comment]
@gjedeer Does current version of your extension https://github.com/gjedeer/PrivateBin-webextension works and ready to use, or still in proof-of-concept?

**Comment by gjedeer** [comment]
@MurzNN it's not developed, although there's no reason why it shouldn't work if you update https://github.com/gjedeer/PrivateBin-webextension/blob/master/hashes.json (PR welcome)
