### ISSUE TITLE
Pasted snippets show a bunch of code and are not very attractive - needs a placeholder

### ISSUE THREAD

**Issue by ajvsol** [PrivateBin/PrivateBin#139]
### What happens
Sending the link for a paste via apps like Slack results in a bunch of code being displayed 

### What should happen
Perhaps some placeholder text as the paste was password-protected, also needs a thumbnail image

## Additional information
Screenshot http://i.imgur.com/fRXVsfL.png

* I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment]
Your screenshot is from slack or so?

I think to solve this issue we could implement Twitter cards including some text explanation.

**Comment by elrido** [comment]
Do we maybe need an [og:description meta tag](https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254) to avoid this?

**Comment by paulcmal** [comment]
Both [og:](http://ogp.me/) and [twitter:](https://dev.twitter.com/cards/types/summary) tags are needed, depending on what service the link gets posted on. As for libre metadata, there's [microformats2](https://indieweb.org/microformats).

I have a problem with sharing links to a Privatebin on social media (or any platform inspecting the link), though, because:

* The service transporting the URL has access to the decryption key (in the URL itself)
* If there is a default template for links to Privatebin, it will be easy to get lost in identically-looking links

I think to address both issues, several measures could be taken:

* add an optional "title" field for new pastes ; if empty, the title could default to "Encrypted note on PrivateBin"
* have a summary (og:description, twitter:description, class="p-summary") explicitely discouraging sharing encrypted pastes on social media, such as "This content is encrypted, but giving the URL to any one/service means they get access to the encrypted as well."
* generate an identicon of sorts for each paste, using the pad name as an input

Specifically regarding the microformats2 implementation, the closest post-type there is to a paste at the moment is a note, that is a bunch of text, optionally with a title, a date, an author, a picture... If a text 

In current microformats2, the closest to a paste is a note: plaintext without a title. Yet, as with og: and twitter:, if people do chose to share their pads on a social media platform of any kind, then 

In microformats2, the closest content type to a paste is a note, that is an article without a title. Yet it would be interesting to create a new

**Comment by paulcmal** [comment]
Both [og:](http://ogp.me/) and [twitter:](https://dev.twitter.com/cards/types/summary) tags are needed, depending on what service the link gets posted on. As for libre metadata, there's [microformats2](https://indieweb.org/microformats).

I have a problem with sharing links to a Privatebin on social media, because:

* The service transporting the URL has access to the decryption key (in the URL itself)
* If there is a default template for links to Privatebin, it will be easy to get lost in identically-looking links

Here's a few ideas to address both issues:

* add an optional "title" field for new pastes ; if empty, the title could default to "Encrypted note on PrivateBin"
* add a summary explicitely discouraging sharing encrypted pastes on social media, such as "This content is encrypted, but giving the URL to any one/service means they get access to the encrypted as well."
* add an identicon of sorts for each paste, using the pad name as an input, for easier retrieval in a feed

Specifically regarding the microformats2 implementation, the closest [post-type](https://indieweb.org/posts) there is to a paste at the moment is a [note](https://indieweb.org/note), that is a bunch of text, optionally with a title, a date, an author, a picture... If an optional title is indeed added to pastes, then it's more of an [article](https://indieweb.org/article).

**Comment by rugk** [comment]
The sharing issue is already documented in the FAQ: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#if-i-use-privatebin-and-post-the-link-in-a-forum-in-social-media-etc-is-my-content-secure
