### ISSUE TITLE
Fatal TypeError if paste ID all numeric

### ISSUE THREAD

**Issue by xrat** [PrivateBin/PrivateBin#1435]
By chance, the paste ID PrivateBin generates can be all numeric, a 16 digit integer. Apparently, this throws a fatal TypeError at https://github.com/PrivateBin/PrivateBin/blob/b077fb77499674ae162f83a63498baeb60772795/lib/Request.php#L86

## Steps to reproduce

1. Generate pastes until the generated paste ID is all numeric, i.e. no [a-z].
2. Access (open) the paste.

### What happens

```
error GET /privatebin/ HTTP/2.0 mod_proxy_fcgi.c(911)
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError:
strlen() expects parameter 1 to be string, int given in /web/privatebin/lib/Request.php:86
Stack trace:
#0 /web/privatebin/lib/Request.php(86): strlen()
#1 /web/privatebin/lib/Request.php(135): PrivateBin\\Request->getPasteId()
#2 /web/privatebin/lib/Controller.php(171): PrivateBin\\Request->__construct()
#3 /web/privatebin/lib/Controller.php(122): PrivateBin\\Controller->_init()
#4 /web/privatebin/index.php(17): PrivateBin\\Controller->__construct()
#5 {main}\n  thrown in /web/privatebin/lib/Request.php on line 86'
```

**Server OS:** Debian 11 Bullseye

**Webserver:** Apache 2.4.62 PHP 7.4 FPM

**PrivateBin version:** 1.7.4

I can reproduce this issue on <https://privatebin.net>: No (it would take very long) ;-)

**Comment by elrido** [comment]
I had recently encountered and resolved an issue in a unit test in a36d72e9149da1b271ba956cc2be081776a210d8, where the problem, too, was that the randomly generated ID happened to get interpreted by PHP as an int instead of a string. This is now an issue, because we have enabled strict types in #1350.

The cause seems to be that [array keys do get cast to numbers automatically](https://www.php.net/manual/en/language.types.array.php) under some circumstances:

> The _key_ can either be an [int](https://www.php.net/manual/en/language.types.integer.php) or a [string](https://www.php.net/manual/en/language.types.string.php). [...]
> 
> Additionally the following key casts will occur:
> - [String](https://www.php.net/manual/en/language.types.string.php)s containing valid decimal [int](https://www.php.net/manual/en/language.types.integer.php)s, unless the number is preceded by a + sign, will be cast to the [int](https://www.php.net/manual/en/language.types.integer.php) type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.
> [...]

Your issue would match the error I encountered in the test: The paste ID happens to get retrieved from an array, so we must cast it back to a string, if necessary, before we do those checks and return it.

**Comment by rugk** [comment]
Okay so the checks here cause the problem? I cause `ctype_xdigit` is then an issue?

https://github.com/PrivateBin/PrivateBin/blob/b077fb77499674ae162f83a63498baeb60772795/lib/Request.php#L82-L92

According to https://www.php.net/manual/en/function.ctype-xdigit.php it should, however, as far as I see, accept integer-only strings, _but_ note indeed the two big warnings:
> [!NOTE]
>  If an [int](https://www.php.net/manual/en/language.types.integer.php) between -128 and 255 inclusive is provided, it is interpreted as the ASCII value of a single character (negative values have 256 added in order to allow characters in the Extended ASCII range). Any other integer is interpreted as a string containing the decimal digits of the integer.

> [!WARNING]
>As of PHP 8.1.0, passing a non-string argument is deprecated. In the future, the argument will be interpreted as a string instead of an ASCII codepoint. Depending on the intended behavior, the argument should either be cast to [string](https://www.php.net/manual/en/language.types.string.php) or an explicit call to [chr()](https://www.php.net/manual/en/function.chr.php) should be made.

**Comment by xrat** [comment]
I found a much easier way to reproduce the error: Just try to access a 16 digit all numeric paste ID, e.g. https://privatebin.net/?1234567890123456

**Comment by xrat** [comment]
Inserting `$key = (string) $key;` before

    if (($value === '') && strlen($key) === 16 && ctype_xdigit($key)) {

works for me.

**Comment by elrido** [comment]
Yes, that is the solution I also applied in the unit test.

@rugk: not quite, the issue is not with strlen or the ctype function, both require strings in strict mode, but that even in strict mode array keys automatically get cast to int of they look numeric. $_GET always is an array, so the only way to avoid this would be to extract the key from the raw URL string from $_SERVER or such. That sounds sketchy, though, so better do the explicit cast.

I'll try and write a test that triggers this, look for other places in the code that might run afoul of the same issue (loops on arrays that may contain numeric keys) and in any case will provide a fix, soon.
