### ISSUE TITLE
file upload deduplication

### ISSUE THREAD

**Issue by parisni** [PrivateBin/PrivateBin#1451]
## The problem

Pbin supports file upload. [One interesting feature from upload tools is file dedup](https://gitlab.com/jirafeau/Jirafeau#what-about-this-file-deduplication-thing). It can be based on both file hash, file size and/or file name. Could be optionaly activated on instance.

**Comment by elrido** [comment]
I don't think we can implement your requested feature of file deduplication, as in letting multiple pastes share the same file but only store that once. The reason is the client-side encryption: Each paste contains an encrypted payload, the key of which is salted and randomly generated. The server doesn't know that key (by design) and therefore can't peak into these messages to compare contents.

In the doc you linked, this feature is primarily described as a mechanism to prevent storage from being wasted by re-uploads. We do have the following mechanisms that prevent obsessive duplicate content:
- The server calculates the paste ID, using a (Fowler–Noll–Vo) hash of the paste - a malicious client that tried uploading the same message over over and over again (same key, etc.) would get a key collision and only the first one would get stored
- The server enforces a [traffic limit](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#trafficlimit) which defaults to 10s - every sender IP can only upload one paste or comment every 10s. That prevents simple DDoS attempts.
- The [message size is limited](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#sizelimit), on the webserver (depending on it's max POST size configuration), the PHP process (configurable) and the application. This further prevents resource exhaustion.
- You can simply aggressively reduce the expiration times and prevent forever-pastes being created. This effectively limits for how long your resources are in used by any paste and even if lots of duplicates get created, these will expire again.

With these mechanisms combined, you have a lot of options to limit the amount of disk space used in average and during peaks and the growth can also be flattened so you would have time to respond to monitoring alerts when network or disk I/O gets congested or the partition runs full. See also this [comment with some numbers on the total size used on a decently sized instance](https://github.com/orgs/PrivateBin/discussions/1259#discussioncomment-8610612).

**Comment by parisni** [comment]
thanks a lot @elrido that's a very informative answer :+1:
