### ISSUE TITLE
[s3 storage] scaleway s3 provider fails after first privatebin

### ISSUE THREAD

**Issue by parisni** [PrivateBin/PrivateBin#1455]
**Did you use the FAQ section?**
- [X] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

configure s3Storage with scaleway provider configs:
```php
[model]
class = S3Storage
[model_options]
endpoint = "https://s3.fr-par.scw.cloud:443"
region = "fr-par"
version = "latest"
bucket = "my-privatebin"
prefix = "privatebin"
accesskey = "access key"
use_path_style_endpoint = true
secretkey = "secret key"
```

1. setup s3 storage
2. create a paste
3. create a second paste

### What happens

After first paste, I get the following files on s3:
```
aws s3 ls my-privatebin --rec
2024-11-12 22:18:23        726 privatebin/a5d008a8259a1184
2024-11-12 22:18:21         10 privatebin/config/purge_limiter
2024-11-12 22:18:19        512 privatebin/config/salt
2024-11-12 22:18:20         10 privatebin/config/traffic_limiter/e365f621171d3d60a8da82b60648d55b226bed2f1c35c341ea671166de6b5838
```

When I try to create a second paste, it fails with error:
```
privatebin-1  | 2024/11/12 21:11:29 [error] 24#24: *8 FastCGI sent in stderr: "PHP message: Error purging pastes: Stream is not seekable
```

Same happens when I try to delete the first paste. After purging the s3 bucket, I can re-create the first paste but again it fails for the second attempt. 

### What should happen

well any paste attempt should succeed.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

1.7.4

I can reproduce this issue on <https://privatebin.net>: N/A

**Comment by elrido** [comment]
Unfortunately I cannot help debug or replicate this issue, since AFAIK none of the projects maintainers has access to any kind of S3 storage - the community member contributing this code used it with a ceph storage.

The only place the message "Error purging pastes" can come from is weirdly the administration script, not the server side code, so I wonder if that is actually related to the problem of not being able to create more than one paste:
https://github.com/PrivateBin/PrivateBin/blob/3460f20e40241f5c5ac54de3343710166bc6ceb8/bin/administration#L319

But staying on that error for now, since it is the only clue you found, here is what the purge code does:
https://github.com/PrivateBin/PrivateBin/blob/3460f20e40241f5c5ac54de3343710166bc6ceb8/lib/Data/AbstractData.php#L152-L163

When looking at the method logic to get the list of expired pastes, it seems nicely guarded to catch any exceptions by the S3 library:
https://github.com/PrivateBin/PrivateBin/blob/3460f20e40241f5c5ac54de3343710166bc6ceb8/lib/Data/S3Storage.php#L419-L449

But other exceptions are not caught, so something under the hood in the S3 library seems to trigger this. I could [find a number of issues in the used AWS SDK that refer to errors seeking in streams](https://github.com/aws/aws-sdk-php/issues?q=is%3Aissue+Stream+is+not+seekable+is%3Aclosed) but when reading up on these, [it seems to relate to using the library to access S3 blobs in streaming fashion (fopen, etc.)](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html#opening-seekable-streams), but I didn't spot any such calls in our implementation.

Can any folks with AWS SDK know-how take a look at our code and enlighten us? Has something in the SDK changed and we needed to update how the library is used on our end?

**Comment by parisni** [comment]
thanks for you investigation. 

>  none of the projects maintainers has access to any kind of S3 storage 

Sounds valuable to add some integration tests with a [local s3 such as minio](https://github.com/minio/minio/blob/master/docs/docker/README.md#run-standalone-minio-on-docker) to validate the feature.

S3 is so cheap compared to any other form of storage that is makes a good feat for such a project.

**Comment by parisni** [comment]
@lconsuegra thanks you so much. I confirm this also fixes my instance

**Comment by rugk** [comment]
> Sounds valuable to add some integration tests with a [local s3 such as minio](https://github.com/minio/minio/blob/master/docs/docker/README.md#run-standalone-minio-on-docker) to validate the feature.

Feel free to do so and contribute it or at least create a separate issue for it and outline how that could be done. @parisni

Great to hear the issue could be solved though. As said, this feature is 99% community supported, so if you want to improve it, go ahead!
