### ISSUE TITLE
[Issue]: Not working with base64-2.1.9.js

### ISSUE THREAD

**Issue by boudjellamahmoud** [PrivateBin/PrivateBin#152]
Hi everybody,
## Steps to reproduce

1. Install PrivateBin
2. Go to the interface of PrivateBin in a browser
3. Put some text in the text area and click on Send button.

### What happens
Nothing.

### What should happen
Should give me the link to the pasted text (in the green box).

## Additional information
![privatebin_issue](https://cloud.githubusercontent.com/assets/17899197/21470954/d80b6222-ca9e-11e6-9562-127e788749b7.png)

* I can reproduce this issue on <https://privatebin.net>: Yes / No
No

* The issue disappear if i enable zerobin compatibility (usage of base64.js 1.7). I mean PrivateBin works fine in this case.

## Basic information

**Server address**:

**Server OS:**
Debian 8

**Webserver:**
Apache 2.4.10

**Browser version:**
Firefox ESR 45.6.0

**PrivateBin version:**
1.0

**Comment by elrido** [comment]
Thank you for reporting this issue.

Unfortunately I failed to reproduce it with Firefox 45 in both the 1.0 release and the latest master version of the code. The error happens in this part of the base64 library:

  var re_btou=new RegExp(["[À-ß][-¿]","[à-ï][-¿]{2}","[ð-÷][-¿]{3}"].join("|"),"g");

The error message "SyntaxError: invalid range in character class" indicates that for some reason Firefox fails to parse the characters at the beginning or end of the character ranges in the regex correctly.

As this only happens on your install, it might be that your webserver is not configured to return the JS files using UTF-8 character set.

Or the character set got mangled due to setting of your FTP client if you used such to upload the files to your webspace. If you are using FTP, try forcing your client to use "binary transfer mode" when uploading your files for the PrivateBin install.

Is there any way you can verify if the problem is your browser or your webserver by using other browsers/devices to access your install?

**Comment by boudjellamahmoud** [comment]
Hi,

Thank you for your answer, i tried with opera, and firefox 50.0.2 on mobile and i have the same issue.

For the FTP, i cloned PrivateBin from git and it didn't change anything.

So, it seems that it is related to my webserver. How or where can i check and fix the trouble with my webserver? Can it be a missed library?

**Comment by elrido** [comment]
You could check for the "Content-Type" header in the network tab of your browsers developer tools for that file. You would expect to see something like:

  Content-Type: "application/javascript"

If there is a charset added at the end that isn't utf-8, that would explain the problem. The solution would depend on your webserver and the particular setup.

Otherwise you could do a `diff` of the s/base64-2.1.9.js downloaded from your webserver and eg. https://privatebin.net/js/base64-2.1.9.js to confirm if there actually are differences in the file which would indicate a problem with how the file got stored on your server.

**Comment by boudjellamahmoud** [comment]
Hi,

Problem solved, i had to reset UTF-8 in php.ini file, it was set to ISO-8859-1.

Thank you for your help.
