### ISSUE TITLE
The "Loading…" message does not go away!

### ISSUE THREAD

**Issue by c0by85** [PrivateBin/PrivateBin#181]
With Chrome Version 56.0.2924.87 & FireFox 50.1.0

Sorry for the german.

Keine der "sha512"-Hashes im "integrity"-Attribut stimmen mit dem Inhalt der Subressource überein.

Failed to find a valid digest in the 'integrity' attribute for resource 'https://localhost/paste/js/privatebin.js?1.1' with computed SHA-256 integrity '0c8ExAIDFccyH9dN4+r/m15LplXPu0Svypqg1Gfak1Q='. The resource has been blocked.

Last pull, today...

I didn't changed anything...

**Comment by rugk** [comment]
Thanks for notifying us. It's fixed.

**Comment by jangrewe** [comment]
@rugk This seems to have happened again. Maybe automate the process?

```
 grep jquery tpl/page.php
                <script type="text/javascript" data-cfasync="false" src="js/jquery-3.3.1.js" integrity="sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg==" crossorigin="anonymous"></script>
```

```
openssl dgst -sha384 -binary js/jquery-3.3.1.js | openssl base64 -A
Q4GEli30r5Awgb/ITt925nE8buHKjVWM/x3DX8t5JwRLT9P/C2r7u7XzNwvpTTGw
```

**Comment by elrido** [comment]
This is [fully automated in the phpunit initialization](https://github.com/PrivateBin/PrivateBin/blob/master/tst/Bootstrap.php#L294). We expect anyone committing changes to the JS files to rerun both mocha and phpunit before committing, hence updating the hashes in both templates automatically.

Note that this file has not been updated since f92330443 and the hash is still sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg== in the latest development branches.

Are you sure that your version of that file didn't get changed on the system that you are testing this? I.e. if you run this on a git repo on Windows or upload this using certain FTP modes the line ending characters will be different, which leads to a different SHA512 hash, while we only consider the UNIX version of that file.

**Comment by jangrewe** [comment]
You are absolutely right, @elrido. I was pretty convinced i did the clone on the host itself, but looks like i did it via a Samba share, via Windows, with CRLF... everything's fine after a reset. Thanks for the hint!
