### ISSUE TITLE
Title is URL in raw mode

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#187]
When a paste is viewed in the RAW mode, the title of the window is the URL, which might not be preferably…

Possibly it should stay "PrivateBin".

**Comment by elrido** [comment]
I bet this due to the pushState:
https://github.com/PrivateBin/PrivateBin/blob/dd721c651b216fd334d985a5f282a079f37ab86d/js/privatebin.js#L1408

According to [docs](https://developer.mozilla.org/de/docs/Web/Guide/DOM/Manipulating_the_browser_history#The_pushState%28%29_method), the second param should be the title. Maybe we need to set an empty state object for the first parameter instead of `null`?

**Comment by rugk** [comment]
And according to the docs "Firefox currently ignores this parameter". The title parameter does not matter at all. Also we do not use the object.

I think the reason is just that we replace the whole content on the site and thereby also remove the header title information.
When you save the site after clicking on the RAW button, this is what you get:
```html
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"></head><body><pre>fsdf</pre></body></html>
```

Obviously no title-information here, so browsers show the URL.

We maybe should just replace `body` instead of the whole document. I'll try it out…
