### ISSUE TITLE
Unit tests fail locally

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#218]
When I locally execute `phpunit` in `tst` I get this:
``` 
$ phpunit
PHPUnit 4.2.6 by Sebastian Bergmann.

Configuration read from /…/PrivateBin/tst/phpunit.xml

PHP Fatal error:  Class 'PHP_Token_Stream' not found in /usr/share/php/PHP/CodeCoverage.php on line 692
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:42
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/TextUI/TestRunner.php:423
PHP   6. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:703
PHP   7. PHPUnit_Framework_TestCase->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:703
PHP   8. PHPUnit_Framework_TestResult->run() /usr/share/php/PHPUnit/Framework/TestCase.php:771
PHP   9. PHP_CodeCoverage->stop() /usr/share/php/PHPUnit/Framework/TestResult.php:689
PHP  10. PHP_CodeCoverage->append() /usr/share/php/PHP/CodeCoverage.php:295
PHP  11. PHP_CodeCoverage->applyIgnoredLinesFilter() /usr/share/php/PHP/CodeCoverage.php:323
PHP  12. PHP_CodeCoverage->getLinesToBeIgnored() /usr/share/php/PHP/CodeCoverage.php:571
```

Debian 8

**Comment by rugk** [comment]
```shell
$ apt-cache show php-token-stream
Package: php-token-stream
Version: 1.3.0-1
Installed-Size: 97
Maintainer: Debian PHP PEAR Maintainers <pkg-php-pear@lists.alioth.debian.org>
```

**Comment by elrido** [comment]
From what I can gather from [phpunit #353](https://github.com/sebastianbergmann/phpunit/issues/353) it is either an incompatibility with PHP Token Stream 1.3 (revert to the older version using `pear install --force phpunit/PHP_TokenStream-1.0.1`) or a missing phpunit autoloader (only if you installed phpunit using composer instead of using apt).

**Comment by rugk** [comment]
I've installed everything from apt, so it should also be compatible.
However I'll try the thing with uninstalling xdebug.

**Comment by rugk** [comment]
Without xdebug:
```shell
$ phpunit   
PHPUnit 4.2.6 by Sebastian Bergmann.

Configuration read from …/PrivateBin/tst/phpunit.xml

The Xdebug extension is not loaded. No code coverage will be generated.

F..........EEEEEEEEEEEEEEEE......................PHP Fatal error:  Class 'Text_Template' not found in /usr/share/php/PHPUnit/Framework/TestCase.php on line 698
```

**Comment by elrido** [comment]
Ok, so that seems to indicate that in Debian 8 the phpunit package is not depending on all required libraries or these other packages are incompatible to it. :-(

How about another way around this: Due to breaking changes in the phpunit in Travis' php 7 environment, I had to include phpunit into our development environment dependencies for composer. You can use the composer installed phpunit via running [../vendor/bin/phpunit from within the tst folder](https://github.com/PrivateBin/PrivateBin/blob/master/.travis.yml#L22). This one should have all the correct dependencies.

**Comment by elrido** [comment]
We now offer a docker container and support our testing inside Janitor.
