### ISSUE TITLE
Simple token (=number) instead of hash in paste URL

### ISSUE THREAD

**Issue by RastaTaz** [PrivateBin/PrivateBin#235]
Hi !
First, thanks for PrivateBin ;o)

I'd like to use PrivateBin in a professional environment, but without the hassle to copy a complex URL between my corporate network and business network.
=> It would be simpler just to have to remind a simple number to get data from an environment to another or to shout it to a colleague through the corridors of my company for him to have a look...

This feature may dramatically reduce the number of pastes that could be hosted (depending on the number of tokens that would be available, maybe via a configurable range); but we actually already use such a tool (but it is quite outdated and can't be maintained) having a "number range" from 0 to 100 randomly selected, and we never had the bad luck of overwriting another needed/active content (we're a small team) and it it proved so to be so useful and faster than USB keys...
I guess it may put security at risk as well as we don't have the hash and keys sent anymore via the URL, but data not being ciphered would not be an issue here.

I was wondering if you could add such a feature to PrivateBin ?

**Comment by rugk** [comment]
Thanks for your request.
The security of the whole system depends on the URL (the ID and the hash with the encryption key). Thus, we cannot shorten it and also can't just assign some numbers, which could easily be guessed.

You can, however, just use an (internal-hosted) URL shortener to shorten the links. See [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#the-url-is-so-long-cant-i-just-use-an-url-shortener) for more details.

Encryption is mandatory and the whole purpose of PrivateBin. So using an URL shortener should satisfy your use-case, otherwise you may want to use a different paste tool.
Thus, we unfortunately cannot solve this issue, so I am closing it.

Also for sharing files you may have better ways (WebDAV servers, Windows network services, …) in cooperate environments.

**Comment by everschen** [comment]
this could be good feature, since we may don't care about the content, just to send the content to someone else to just tell him the number if no im tools there.
as far as i know there's some kind of tools support this.
