### ISSUE TITLE
New code analyser

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#236]
We could add/try out a [new code analyser](https://codebeat.co/).

But it only seems to support JavaScript, not PHP.

**Comment by kyodev** [comment]
in another project on github, they use [codacy.com](https://www.codacy.com/features), free for open-source. perhaps, you can see it?

**Comment by rugk** [comment]
Yeah, this is not only happening in another project. It is even used [here too](https://www.codacy.com/app/PrivateBin/PrivateBin/dashboard). :smile: 
See the Readme for a complete list.

This is just the issue for adding yet another one… :laughing: 
BTW CodeBeat is also free for FLOSS, of course.

**Comment by rugk** [comment]
Yet another new one: https://lgtm.com/
(Don't know if it supports PHP or JS though.)

**Comment by marsjaninzmarsa** [comment]
Again - [looks like only JS](https://lgtm.com/docs/lgtm/tech/analysis-faq#which-languages-are-supported).

**Comment by elrido** [comment]
Hey @rugk,

As you know on your request I had integrated many such code analysers last year and it took a few weeks of our time to get them all working and reduce the false positives caused by them to get meaningful reports out of them. We then spent a few weeks implementing the suggested best practices and handled the few actual issues detected by them.

Before we spend yet more time to add more such tools, may I ask us all to consider what goal we want to achieve in adding them?

From our previous experience adding them I learned that some of them give conflicting advice and when certain things were changed to adhere to one analysers standard, others started to complain about these exact things and we then had to choose one standard for ourselves and reconfigure some of the analysers to avoid calling out these issues as (by our definition) false positives.

I personally would rather, for the moment, take time for the project to continue on the JS unit testing front (property based (aka fuzzing), not purely static). I believe that this will help the project more in the long run, then adding more analysis tools that do purely static code analysis and implementing such suggestions without understanding the benefits.

But if anyone can show a benefit in any of these new analysers, compared to the ones we have, and that maybe these can even replace the existing ones, I will certainly not be against any pull request.

**Comment by rugk** [comment]
> may I ask us all to consider what goal we want to achieve in adding them?

More nice badges in the Readme showing how good or bad our code is. :laughing: 
But seriously they are really not that important and I mostly opened the issue here, because I found some, whcih looked nice, but I can certainly agree that we have enough/a lot already.

> But if anyone can show a benefit in any of these new analysers, compared to the ones we have, and that maybe these can even replace the existing ones, I will certainly not be against any pull request.

That's a good closing sentence and so I'll close this issue.
