### ISSUE TITLE
Minify assets

### ISSUE THREAD

**Issue by hogze94** [PrivateBin/PrivateBin#240]
Just had a quick look at the js files, is it possible to have them minified?

Stats: 84.13% compression, saving 44.32 kb
Stats: 73.5% compression, saving 14.2 kb
Stats: 78.93% compression, saving 95.05 kb

Haven't looked at anything else but that alone is a huge saving.

**Comment by elrido** [comment]
A while back we did have minified JS in the project, but then started to remove it, since:

1. servers should just gzip or zopfli the content and will achieve better compression than with minification alone would offer
2. since the whole trust in the encryption relies on the server not manipulating the JS code it would be counter productive to obfuscate the code and make it less human readable

That said, you may of course minify them on your installation. You just need to [update the SRI hashes in the templates](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#user-content-how-to-make-privatebin-work-when-i-have-changed-some-javascript-files) afterwards.
