### ISSUE TITLE
Unrecognized Content-Security-Policy directive 'referrer'.

### ISSUE THREAD

**Issue by akroii** [PrivateBin/PrivateBin#262]
## Steps to reproduce

1. Create a fresh installation
2. enable cspheader in your config.ini on line 72

### What happens
Output in Console: Unrecognized Content-Security-Policy directive 'referrer'. 

### What should happen
header('Referrer-Policy: no-referrer');

## Basic information

**Server address**:

**Server OS: Apache**

**Webserver: **

**Browser: Chrome 63**

**PrivateBin version: 1.1.1**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment]
Yes, this is a known "issue". Actually the `referrer` directive is valid, or better: has been valid. Because Firefox still seems to support it and displays a more accurate message:
> Content Security Policy: Referrer Directive ‘no-referrer’ has been deprecated. Please use the Referrer-Policy header instead.

So just FYI: We already use `Referrer-Policy` (in the [HTML source](https://github.com/PrivateBin/PrivateBin/blob/master/tpl/bootstrap.php#L13)). So we just use the CSP directive as a fallback.

Also, BTW, this is a duplicate of https://github.com/PrivateBin/PrivateBin/issues/196.
