### ISSUE TITLE
Unknown problem by uploading a large file

### ISSUE THREAD

**Issue by DorKeinath** [PrivateBin/PrivateBin#263]
## Steps to reproduce
1. Try to upload a large file to https://xcosx.de/paste/index.php for example a file with 860 MB.
2. Wait for the URL.
3. Call the URL.

### What happens
An Error

### What should happen
Because the time in the 2. step is too short I think the upload isn't working.

## Additional information
In paste/cfg/confg.php I set
`fileupload = true`
`sizelimit = 1610612736`

## Basic information

**Server address**: https://xcosx.de/paste/index.php

**Server OS:** I don't know

**Webserver:** I don't know

**Browser:** Firefox Quantum or Chromium

**PrivateBin version:** 1.1.1

I can reproduce this issue on <https://privatebin.net>: No, their is no option to upload a file.

**Comment by rugk** [comment]
> An Error

Which error?

Generally, I think this could be related to limitations of your hosting provider/Apache (or whatever webserver you use) configuration. They may just limit the upload size.
Pleas check whether such a limit is in place.

**Comment by elrido** [comment]
Hi @DorKeinath,

Uploading such large files is non-trivial. Since the file needs to be encrypted in the browser, it is first loaded into your ram, a copy of this data is then compressed, encrypted and finally base64 encoded (making it it up to 30% larger again, all because JSON doesn't handle binary data too well). So at that point you will have up to 1.5 GiB of RAM used.

Assuming the above worked, your paste will then be sent to the server, where it needs to pass the following limitations: Most webservers have an upper limit of how much data they may receive per request (`LimitRequestBody` in Apache, `client_max_body_size` in nginx). If your server uses PHP via FCGI, then there may be additional settings (`FcgidMaxRequestLen` and `FcgidConnectTimeout` in Apache) that need to be large enough. Then there are PHPs settings like `post_max_size` and `memory_limit` (the server loads that stuff into RAM, too). Finally PrivateBins [`sizelimit`](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#sizelimit) needs to be large enough, too.

You may not want to increase these values too much, since this opens your server up for easy denial of service with just a few simultaneous uploads consuming the servers resources. Hence the default of just 2 MiB. In a non-public environment (in a company LAN for example) it may be an acceptable risk to just increase these limits.

Side note: When accessing such a large paste, every request to that pastes URL will download the full file **in page** (= in the HTML itself, before CSS and JS is loaded), so it may take a long time until the page completes to load and becomes responsive.

To circumvent all these limitations we would need to implement a chunking upload API (writing into a /tmp file until the upload is complete, maybe handling base64 encoding server side) and find compression, encryption and base64 libraries that offer streaming, so that we can avoid doing those steps in RAM. The libraries we currently use don't support streaming.

**Comment by rugk** [comment]
> When accessing such a large paste, every request to that pastes URL will download the full file in page (= in the HTML itself, before CSS and JS is loaded),

At least this will be fixed, when #216 is merged.

So in any case, I think this issue can be closed. If you have further questions, feel free to ask.
