### ISSUE TITLE
Empty paste - 2

### ISSUE THREAD

**Issue by ukcb** [PrivateBin/PrivateBin#269]
In version PrivateBin-1.1.1.tar.gz the paste (plaintext) `<!-- test -->` works.
In the current master at git the preview of this text is empty. The saved paste is also empty.

For example, `<h1>hola</h1>` formats the HTML into a nice header in the textplain preview.

**Comment by simonrupf** [comment]
I suspect this is because we recently introduced the DOMPurify library to prevent HTML to be interpreted. So I fear I have to answer that this is actually intended by us, that in the plain text format, HTML isn't interpreted. You can use Markdown format and use either of these:

```markdown
# H1 header

or

H1 header
=========
```

What we certainly do need to fix is that these tags get interpreted as HTML (which is why the `<!-- test -->` gets hidden). In plain text this needs to be left as is and get properly escaped, as back in 1.1.1. So this is a regression introduced by #183.

**Comment by elrido** [comment]
I suspect this is because we recently introduced the DOMPurify library to prevent HTML to be interpreted. So I fear I have to answer that this is actually intended by us, that in the plain text format, HTML isn't interpreted. You can use Markdown format and use either of these:

```markdown
# H1 header

or

H1 header
=========
```

What we certainly do need to fix is that these tags get interpreted as HTML (which is why the `<!-- test -->` gets hidden). In plain text this needs to be left as is and get properly escaped, as back in 1.1.1. So this is a regression introduced by #183.

**Comment by elrido** [comment]
With that commit HTML again gets escaped like in 1.1.1, not just purified.

There is one catch: Before we did allow HTML in the Markdown formatter, which is in accordance to Markdown standards. This now gets escaped, for example breaking the first line of our own project file. We can solve that of course, but I wanted a short feedback before doing that:

@rugk Do you think we should allow (purified) HTML again in the Markdown format or do you see a risk in that?

Other opinions and arguments are welcome, too.

**Comment by rugk** [comment]
AFAIK DOMPurify should not break "safe HTML", which is not a security issue at all. You can test it on https://cure53.de/purify. When I paste the first line of our Readme there, it is of course broken (as Markdown is not interpreted), but the image (which is a HTML `img` tag) is shown.

> Do you think we should allow (purified) HTML again in the Markdown format or do you see a risk in that?

Is is nowhere disalllowed. we let showdown do it's job and then ran that though DOMPurify:

https://github.com/PrivateBin/PrivateBin/blob/bb54d46c7ed18881d1ce8d8afc46162121f85d59/js/privatebin.js#L1716

I don't get what you want to change there?
Is there any full example of HTML code not being interpreted/shown correctly?

**Comment by elrido** [comment]
My change did change this behaviour for all formats, not just markdown. Do I understand you correctly that you'd prefer markdown to interpret HTML instead of escaping it, contrary to what one would expect for plain text? You can test my fix [here](https://zerobin-test.dssr.ch/).

**Comment by ukcb** [comment]
@elrido I think the behavior is now correct for all formats, it's ok if the HTML-tags are not interpreted in the Markdown format. It is the behavior that I would expect.

**Comment by rugk** [comment]
No, I certainly prefer if HTML is interpreted if pasted in Markdown…

I tried your test with this text:
```
great & good <!--  comment --> invisible
```

Actually, the comment is not rendered. That's bad, because you e.g. do have any comment feature in Markdown. Note that if it would be rendered, you can still access the source through the "raw text" button.

---

HTML usage is a feature of Markdown. Just see it on GitHub e.g. There you can also use HTML comments to hide stuff and so on. I see this is a feature and it is certainly not bad considering that the output is properly sanitized now.

**Comment by rugk** [comment]
Plain text is plain text, Markdown is markdown/HTML.

**Comment by elrido** [comment]
Ok, I'll look for another solution that allows (purified) HTML for markdown and escapes it in all other cases.

**Comment by elrido** [comment]
Sorry, forgot to mark that commit as resolving.
