### ISSUE TITLE
Change the Encryption to a higher standart or switch to RSA

### ISSUE THREAD

**Issue by well0nez** [PrivateBin/PrivateBin#286]
Hey, was far as i can see, the crypting based calculations are done in the browser.
is there a way to set a higher standard?

**Comment by rugk** [comment]
It's done using AES-GCM in the browser using [scjl](https://crypto.stanford.edu/sjcl/), yes. See https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format for details.

RSA is an asymmetric crypto system, so one would need to deliver the public key and do stuff like that. That is not automatically a "higher standard" (often it is even more problematic due to key distribution) and generally not useful for PrivateBin.

As for "in the browser", yes, of course. How would you otherwise do it?
