### ISSUE TITLE
Improve random number generation

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#29]
See https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php

So I would propose the following order:
* `Sodium::randombytes_uniform()`
* `random_bytes()`
* [`random_compat`](https://github.com/paragonie/random_compat)? (or current `mcrypt_create_iv` implementation?)

Maybe we'll switch the first two - probably depending on which is faster.

**Comment by rugk** [comment]
BTW if we use `random_compat` this automatically ueses libsodium, so we may change the order to this:
* `random_bytes()`
* [`random_compat`](https://github.com/paragonie/random_compat)? (or current `mcrypt_create_iv` implementation?)

As both functions have the same name, it would basically a drop-in.

**Comment by rugk** [comment]
It looks as if this library would be quite powerful...

**Comment by elrido** [comment]
Please don't get this the wrong way. I do very much appreciate that you look into all these corners of the project and come up with many good suggestions.

On this particular topic I don't quite see the point of the effort. Here is why:

1. Pseudo random numbers in general: What ever software implementation we use, it's only really a _pseudo_ random number. This includes /dev/random on most systems, even if this is fed by hardware noise, as long as there is no actual hardware random number generator feeding it.
2. Currently we depend on the mcrypt module, which is quite common on most PHP servers. It's packaged in most distros since many years. I have not yet seen any major distro ship libsodium in their stable branch. So we would develop a solution which can only be used by a tiny minority of our user base.
3. Types of attack that a bad random number could cause: We generate the server salt for use in hashing the IPs in the traffic limiter. To circumvent the traffic limiter, knowledge of that salt does not help, you still would need to change the IP of your machine. More severe would be if you could predict the salt for the deletion link. So you could (maybe) generate a deletion token for another paste, which ID you guess (paste IDs are generated client side), by creating a lot of new pastes around the same time as the attacked paste is created. I consider this to be an unlikely scenario.
4. Finally: Both libsodium and mcrypt_random_iv use /dev/urandom as randomness source. Maybe the NaCl implementation is more robust, but the source of randomness is the same.

Here is some further reading on the topic of random number usage in PHP:
http://timoh6.github.io/2013/11/05/Secure-random-numbers-for-PHP-developers.html

**Comment by rugk** [comment]
>  I have not yet seen any major distro ship libsodium in their stable branch. So we would develop a solution which can only be used by a tiny minority of our user base.

As I explained we do not need to implement libsodium support if we use the library I mentioned.

So I leave this issue open as a idea for later. I think using `random_compat` would be a good and relatively easy thing to implement.

**Comment by Sobak** [comment]
Especially when #46 will be fixed and we'll be able to just use Composer package.

**Comment by rugk** [comment]
Yeah, then we can just include the lib via Composer.
