### ISSUE TITLE
name is missing from conf.sample.php and is being ignored

### ISSUE THREAD

**Issue by abulgatz** [PrivateBin/PrivateBin#303]
## Steps to reproduce

1. Add line `name = "My Name"` under section `[main]` in `conf.php`
2. Visit privatebin site and view site name

### What happens

Cannot set custom site name

### What should happen

Name directive in `conf.php` should allow setting a custom site name

**Comment by rugk** [comment]
Cannot reproduce, which version do you use and which template?

**Comment by haywardgb** [comment]
Same issue. 
Using Bootstrap-Compact.

**Comment by abulgatz** [comment]
Using v1.1.1 with the default theme.

**Comment by haywardgb** [comment]
There doesn't seem to be a name value being checked for...

` /**
     * default configuration
     *
     * @var array
     */
    private static $_defaults = array(
        'main' => array(
            'discussion'               => true,
            'opendiscussion'           => false,
            'password'                 => true,
            'fileupload'               => false,
            'burnafterreadingselected' => false,
            'defaultformatter'         => 'plaintext',
            'syntaxhighlightingtheme'  => null,
            'sizelimit'                => 2097152,
            'template'                 => `'bootstrap',

**Comment by haywardgb** [comment]
Open /tpl/bootstrap.php , look for this line: 

`<h4 class="col-md-5 col-xs-8"><?php echo I18n::_('PrivateBin'); ?> <small>- <?php echo I18n::_('Because ignorance is bliss'); ?></small></h4>`

Change PrivateBin, to whatever you like. It's worked for me. Easy workaround for now.

**Comment by rugk** [comment]
In the current code base the name is there:

https://github.com/PrivateBin/PrivateBin/blob/3b9002055933e570e55add041c90c2db5d620c55/lib/Configuration.php#L40

Actually it seems I got the error. The option has been introduced in the code for some time (https://github.com/PrivateBin/PrivateBin/issues/154), but when we backported the fix for 1.1.1, we accidentally used the new config file, which already mentions this option.

I am sorry for this mistake, but as it is in the release now, there is nothing we can do. In the next release the feature will work as expected. :smiley: 

So if you want to use this now you could switch to the master version.
