### ISSUE TITLE
Yourls (URL Shortner) Easy Method ?

### ISSUE THREAD

**Issue by haywardgb** [PrivateBin/PrivateBin#305]
I want to use the Yourls url shortner. But I only want it to work with api requests from my privatebin url. What is the simplest (if at all) method of doing this , without opening the api up to potential spam abuse etc.. I've already added a plugin that restricts url shortening to my privatebin url only. But I still don't fully see where to make this "seemless" for the end user.

Thanks in advance.

**Comment by rugk** [comment]
First, this is rather a question for YOURLs instead of PrivateBin.

> I've already added a plugin that restricts url shortening to my privatebin url only.

So you seem to have solved the problem already. There is likely no other way to prevent users from using your URL shorter. If they know the URL of your YOURLs instance, they know the URL, so you cannot prevent them from using it and PrivateBin just opens the URL publicly.
Also PrivateBin prevents the referrer from being sent, so you also cannot use this.

In any case, I think, however, that only allowing users to use the URL shorter for only your domain seems to be enough. The only bad thing users can then do would be to create more short URLs for some PrivateBin stuff.

The only other idea I had would be to run YOURLs behind an URL, which nobody knows (`/yoursurl-shorter-secret7836432`) or so. However, of course, everybody who uses your PrivateBin instance will know the URL of that instance.

To make it seamless, you know that an URL shorter can be [integrated](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#urlshortener) into PrivateBin, don't you?

**Comment by haywardgb** [comment]
Kind of you to reply, even though I've obviously posted in the wrong place. All the same, thank you. 

I do know about the url shortner function, I was just trying to find out if (as you have cleared up for me) there is a way to integrate it easily, assuming maybe that others had done it before.

Have a great weekend and thanks again.
