### ISSUE TITLE
UI doesn't removes attachment

### ISSUE THREAD

**Issue by r4sas** [PrivateBin/PrivateBin#315]
According to changes in https://github.com/PrivateBin/PrivateBin/pull/298, reporting that `Remove attachment` doesn't works when image or file attached from clipboard.

Browser: Firefox ESR 52.5.4.

Reproducable on https://paste.i2pd.xyz/

**Comment by rugk** [comment]
We don't even support adding attachments from the clipboard, but anyway I can reproduce the "remove attachment" issue.

1. Add a attachment.
2. Click "New" button.
3. Look at the attachment button again: It still lists the file name, there.

**Comment by r4sas** [comment]
I find it in other way:

1. Click 'New' button.
2. Paste attachment (file from clipboard or picture, like screenshot).
3. Try remove attachment.
4, Upload paste.

File will be uploaded anyway.

**Comment by rugk** [comment]
BTW

> Paste attachment (file from clipboard or picture, like screenshot).

How do you do so?

**Comment by r4sas** [comment]
@rugk if you about screenshot, simply using `PrtScr` key on keyboard. After that I pasted (ctrl+V) image in buffer to field where you must write text. Same way for files, by coping file in system.

**Comment by rugk** [comment]
https://paste.i2pd.xyz/ shows some NextCloud site BTW currently.

Ah okay yeah, the latest master seems to have that feature.

Anyway, i tried it by just using the file selector and it is essentially the same. The worst thing is, you don't see the image in the preview. You only see it when it is uploaded.

**Comment by r4sas** [comment]
> shows some NextCloud site BTW currently.
Aha, Thats because i reconfigure my DNS records now ;)

> The worst thing is, you don't see the image in the preview.
Yes, same until I follow paste link,

**Comment by rugk** [comment]
https://paste.i2pd.xyz/ shows some NextCloud site BTW currently.

Ah okay yeah, the latest master seems to have that feature.

Anyway, i tried it by just using the file selector and it is essentially the same. The worst thing is, you don't see the image in the preview. You only see it when it is uploaded.

**Comment by rugk** [comment]
So I fixed that, BTW the base confusion was that the attachment viewer is also used for storing to be uploaded attachments, which caused some confusion in handling them.
However, that's also very nice in order to easily re-upload attachments. But generally some refactoring here would be good, especially as some methods are not really clearly named "hasAttachmentData" BTW does _not_ check, whether there is data to be uploaded, but whether there is data that needs to be decrypted (which is stored somewhere). It has actually nothing to do with the `attachmentData`  variable, which is actually the "real" data of the attachment and also set when you create a new paste and add the file via the file selector.
@elrido, any idea? May a refactoring be useful/should I open an issue, at least?

**Comment by r4sas** [comment]
Updated to latest version, got same issue.

Step-by-step what I do:
1. Copy image to buffer.
2. Paste (Ctrl+V) on new paste page.
![default](https://user-images.githubusercontent.com/7023612/40322396-e6f90a5c-5d3a-11e8-90eb-6111b8a0befd.png)
3. Try remove attachment using `Remove attachment` button.

Attachment stay here (pic above) anyway.

**Comment by rugk** [comment]
Okay wait, maybe it is just the display. At least in my tests it was not uploaded anymore when I clicked "Send".

**Comment by r4sas** [comment]
Let me pull repo again... maybe last commit downloaded not correctly. Will update that message soon.

**Comment by rugk** [comment]
I'll have a look into the first display issue. As for what you wrote below: I am sorry, but I did not quite what the problem there is. It's best when you write "steps to reproduce", so I know what to do to get the problem.

**Comment by rugk** [comment]
So I found some things…

However there is one issue:
* the files selected via file picker are shown at one place
* the files via drag and drop below (as this is what you propbably wanted to show with your second screenshot)

As far as I see, this is hard to fix, because we cannot manualyl modify the file picker value from the outside for security reasons.

I've opened a new issue for that:
