### ISSUE TITLE
Do not sanitize text-only content, but display text

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#330]
In https://github.com/PrivateBin/PrivateBin/issues/328 we hit a problem and there may be more of these.

Why not?
* Sanitize only when it is shown as Markdown/HTML.
* And when it is shown as text-only (i.e. added to the DOM via jQuery text() respectively [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) or [innerText](https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText)), we can avoid all XSS attacks (as it is not added as HTML text) and just display the text as text.

That would avoid sanitisation or so for text-only content, which saves some processing power (doubt it is much, but well…) and makes text-only pastes a bit more robust (https://github.com/PrivateBin/PrivateBin/issues/328).

**Comment by elrido** [comment]
I absolutely agree, that it makes more sense to sanitize on viewing then on creating a paste (resource wise). Reg. security, we can't guarantee that only PrivateBin is used to create pastes, an attacker could use his own non-sanitizing client to paste malicious pastes.

We did originally introduce DOMpurify to sanitize Markdown, but discovered that we may have similar issues in text only and source code pastes, hence we wan't to sanitize everything that may be used to inject malicious code into the pastes.

Yes, this does mean that we can't reproduce any byte sequence. There will be some that get truncated, because they can't be properly escaped. The alternative is to risk security issues due to not properly escaped code.

**Comment by rugk** [comment]
I had to edit the original post, as we of course already do sanitize on viewing, not on saving. Everything wide would be a security issue.

HTML and markdown need to be sanitised, but text does not if we just do not insert it via "HTML" or so. See the docs I have linked.

**Comment by rugk** [comment]
There is:
> HTML and markdown need to be sanitised, but text does not if we just do not insert it via "HTML" or so. See the docs I have linked.

So this issue is about **removing** unnecessary sanitation.

>  but discovered that we may have similar issues in text only and source code pastes

Because we inserted it as HTML, not as text-only.

**Comment by rugk** [comment]
So adding as text would break links though. Maybe that linkify lib can be used on text already added to the Dom?

**Comment by elrido** [comment]
Or we could use the already existing function, inserting links into the DOM, but then you had to use DOMverify again to be sure no malicious links gets inserted.

So... leave it as it is, to stay on the safe side and close this issue, please?

**Comment by rugk** [comment]
Hmm, [actually markdown-it seems to do it in a safe way](https://github.com/markdown-it/markdown-it/blob/master/docs/security.md) and the also use a [linkify lib](https://github.com/markdown-it/markdown-it/blob/master/docs/security.md). But I see in the demo website that they still use escaping.
