### ISSUE TITLE
Force password entry during decryption

### ISSUE THREAD

**Issue by ukcb** [PrivateBin/PrivateBin#341]
Should you force the entry of a password while decrypting? If I do not enter anything the screen stays black.

A small change in `tpl/bootstrap.php` should suffice.

**-** `<input id="passworddecrypt" type="password" class="form-control" placeholder="<?php echo I18n::_('Enter password') ?>">`
**+** `<input id="passworddecrypt" type="password" class="form-control"` **required** `placeholder="<?php echo I18n::_('Enter password') ?>">`

I use the current git-master.

**Comment by rugk** [comment]
Hmm, yeah, good idea. No password will cause no additional encryption, so yes. Feel free to send a PR. 😄

**Comment by ukcb** [comment]
In version 1.1.1. there is no problem with a blank password. The password prompt will reappear there without the browser displaying nothing at all.

It was just an idea. Maybe the problem is elsewhere. A PR is just a bit complicated with my old fork.

**Comment by elrido** [comment]
Could be a regression from the JS refactoring. We should then probably fix it before the release. I'll give your proposed solution a try, @ukcb Thanks for reporting!

**Comment by rugk** [comment]
As far as I see it is totally solvable with HTML-only. So it does not even have anything to do with JS.

**Comment by elrido** [comment]
It's definitely a JS issue. In the page template the password decryption doesn't work at all, no dialog shown and errors in the console. Both templates worked fine in 1.1.1 for password protection.

**Comment by elrido** [comment]
Turned out to be a collection of issues, the UI change alone didn't fix it, but was still required. Weirdly enough it had to be solved by removing code.

The page template issues were due to added CSP rules that prevented the prompt dialog and a missing call to decryption in that branch of the logic.

Basically both of these issue were related to the logic that should handle a retry in case the password entered is not correct or empty or the dialog is canceled. The prompt returns a result immediatly, while the modal in bootstrap works via a callback, so both scenarios have to be handled differently, but have to end up in the same result: Offering a retry or properly decrypting the paste when the password matches.

Also found a missing translation and two superfluous calls to source maps in the recently updated JS libraries while debugging this issue. So over all it's very good that this was found before the release.

**Comment by rugk** [comment]
So it seems you changed the whole stuff of things… :smile: 

I just tested it and it seems to work fine. I did not knew there even was a re-try button! (Maybe that's why the logic before just autro-retried.)

**Comment by elrido** [comment]
?! That is odd, since you introduced it in d53207e4043351706734e924512fa9f399d040f4 for #216? You must have forgotten since, was a year ago... ;-)

**Comment by rugk** [comment]
`clickRetryButton` – Oh, yes, seems I've totally forgotten. :laughing: In https://github.com/PrivateBin/PrivateBin/commit/d53207e4043351706734e924512fa9f399d040f4 I just did not change the code you touched for auto-retrying. Well… anyway, now it's fixed. That's what matters. :smiley:
