### ISSUE TITLE
secret: pre-display page before showing the content

### ISSUE THREAD

**Issue by megabert** [PrivateBin/PrivateBin#347]
What I like very much about a competing, non-oss software (www.read2burn.com) is that this software has a page that is displayed before showing the secret content with this message, when you open the url:

"click here for the content. But be advised. This can only be done once!"

And a button name "show secret".

In this way you can verify the content is still there without consuming and destroying the secret message. I'd like to verify a link now and then to make sure it really works before I send it out.

**Comment by rugk** [comment]
I was thinking about implications as for https://github.com/PrivateBin/PrivateBin/issues/174, but actually this here seems save to me. Basically, thanks to https://github.com/PrivateBin/PrivateBin/issues/174, it is just "delaying" the JSON download of a paste.

However, we cannot verify the existance of a paste like that. For this we'd need a new API endpoint that just checks for the existance.

---

In any case though, I would want to make it configurable. Question is, configurable for the user, or for the server admin?

**Comment by megabert** [comment]
I have to read #174 carefully before commenting on that.

For me it seems to be a very simple change. For the feature requested, only a gate-page is needed. So before the paste is displayed: "Do you really want to open the secret now?". Is it that what you mean with "delaying" the JSON download? 

So if this is not possible, the API is that way, that a secret information can only be requested, and when such request is sent, the API-function directly clears out the information automatically(if burn-after-reading is set)?

**Comment by megabert** [comment]
Another comment for this feature request:

I think it's only useful to "delay" if burn-after-reading is active.

> In any case though, I would want to make it configurable. 
> Question is, configurable for the user, or for the server admin?

I think to make it configurable for the admin would suffice because I would spare the user for any additional configuration if possible. (Just my opinion). I myself as a user like the most simplistic
an cleanest interface. (My use for privatebin is always the same: burn-after-reading, 1 month, submit,
so count of the current available options in the interface are already too much for me ;-) )

**Comment by elrido** [comment]
Thinking about this, I can see the risk that introducing such an "exists" API call introduces a security risk in the form of an information leak.

Let's assume a burn-after-reading is created. The URL gets sent by the creator to the recipient. The creator can now poll the "exists" API to check if the URL was opened, without the recipient learning about this.

I would rather support a challenge/response approach, like you outlined in #245. The paste is only sent, when the token sent by the client matches and in the case of burn-after reading, the paste is then destroyed.

With this, one could implement the above "delay" as follows:
1. visitor opens URL of paste
2. Gets asked for the optional password (regardless if the paste has one or even exists, no server communication)
3. visitor enters a password or leaves it blank, clicks "Ok"
4. the JS calls the "read" API call, sending the generated token along (HMAC of paste ID + key + password)
5. the server responds, depending on the circumstances in one of four ways:
   1. the paste doesn't exist (anymore) or has expired: the server response with the ambiguous "paste was deleted or doesn't exist" message, deletes the paste if it has expired
   2. the paste has an old format without HMAC in its metadata: Return the paste regardless, deleting it, if it is burn-after-reading
   3. the paste has an HMAC and it is matches: Return the paste regardless, deleting it, if it is burn-after-reading
   4. the paste has an HMAC and it is wrong:  the server "lies" with the ambiguous "paste was deleted or doesn't exist" message, ensuring the no-one can deduce if the paste was already opened.

Case 5.4 is a problem if the password was mistyped, so in this case we would need to offer the option in the UI to try it again, even though the API told us the paste was already deleted.

Given that the "delay" introduces an extra step I would definitely recommend to make this an option for admins to choose. The HMAC would need to be stored in the paste metadata, so it requires a format change and we should do it with the other format changes in the upcoming release.

**Comment by rugk** [comment]
> Gets asked for the optional password (regardless if the paste has one or even exists, no server communication)

Sorry, but that UX is not acceptable. When you ask users to enter a password, they will. You hardly can make sure they can "optionally" enter one.

So technically it is a great solution. But we have to find a way without asking the user for anything. First step is find out if it is auto-deleting and press a button, then download paste.

> Case 5.4 is a problem if the password was mistyped, so in this case we would need to offer the option in the UI to try it again

We could of course just not lie. :smile: 

----

So it all centers around the question:
* Is it a risk to PB when attackers know that a paste exists? (What does our thread model say? :smile:)

Okay, attackers may know they can 

----

However, I think I found a solution:
* We have to have an API that returns `pasteExists` and `pasteIsBurnAfterReading` (maybe also `isPasswordProtected`). access-protected.
* This API is access-protected with the HMAC, as discussed, but _only_ the hash (not password, even if there is one). This way, we protect the API, but do not require users to enter a password, if they don't need to do so.

The "pre-display page" is shown, when:
* `pasteExists AND pasteIsBurnAfterReading AND not isPasswordProtected (and if admin has not disabled it)`
* because, if it is password protected, we may just directly show the password input. Dismissing it can also just be used to prevent the paste from getting deleted. Or, as we have to change our logic (as for https://github.com/PrivateBin/PrivateBin/issues/245) anyway: This is just a special "pre-display page" that has a "password input field" instead of a simple button.

**Comment by elrido** [comment]
Yes, I think that the there is an information leak here and it is an issue:
* The server may not know if the paste is password protected or not. It has to behave the same, regardless if the paste is password protected or not.
* If the server acts differently on burn-after-reading pastes when the paste gets viewed or just checked, then you introduce a side-channel that reverts all the work you did for #216.

So yes, UX with always delay and ask user password or not is super annoying, so don't make it the default, please.

I would accept a solution where the user can prove to the server that he knows if the paste was password protected or not with some challenge, as long as the server can't deduce if the paste was password protected or not. I.e. that could be appended to the URL after the hash, and only then is the UI shown asking for the password right away. If that gets removed from the URL, the HMAC check fails without password, the server responds with the generic error and the UX suppresses it and instead asks the user for a password (similar to now). This is one idea of the top of my head, surely you can think of better ways.

The server has to lie in the view request with incorrect HMAC, so that we don't have to introduce an "exists" API which poses a risk for burn-after-reading pastes.

Given that in #174 you reacted very sensitive on learning that the paste wasn't deleted until an API call was sent and your scenario was that you and your communication partner were under surveillance and you wanted to be sure that just the recipient got the paste or that you could at least notice if the paste had disappeared when you as the recipient opened it for the first time.

Ask yourself: If someone sends you a link to a burn-after-reading paste, can't you think of any case were you would like to avoid the fact that with the "exists" API (or the view with HMAC that doesn't "lie") a third party or the paste creator can check if you have opened the paste or not and when you did that? It would be as simple as polling the API every few seconds and record the time the status changes...

**Comment by rugk** [comment]
> The server may not know if the paste is password protected or not. It has to behave the same, regardless if the paste is password protected or not.

Good point, but that can be saved as additional meta data. But I see, that we may not want that… ugh… too bad.

> If the server acts differently on burn-after-reading pastes when the paste gets viewed or just checked, then you introduce a side-channel that reverts all the work you did for #216.

Let me think, no, it acts the same. These are always to JSON requests, just the timing is different and you could always find out when the user clicked the button.
So this would be an argument against this whole feature in this issue. And, of course, an argument for an admin config option for this.

Two requests (if "landing page/pre-display page" is enabled):
* 

>  a third party or the paste creator can check if you have opened the paste or not and when you did that?

Ah, that was the scenario. Okay, yes, that's a good argument.
(Next question: Is this mentioned in our thread model?)

---

So we could just ignore the password-protected difference and always display a button (when API-protected with hash returns "exists AND isBurnAfterReading"). Thus,w e do not need to save password state on the server.
And we do not expose the exists or so property to anyone.

**Comment by elrido** [comment]
Is it in the threat model: How could it, as this is a completely new scenario. If you introduce a new API for "exists", then suddenly you would have a new data flow and a new risk to assess. So I am trying to model the new risks for this API with you here and argue that there is a risk of information leak.

How about this very simple solution: In newly created burn-after-reading pastes you append a "&ask" or other such marker at the end of the hash part of the URL (those normally get stripped away as they might have been appended for tracking). If that little marker is present, you present the user with the delay dialog. The user clicks and you do the usual view request to the server. The password protection is handled just as now and if the user navigates away at that point the paste already got deleted, keeping it a secret (the user was warned and consented to this on the delay message display).

Such a change would be independent of the HMAC idea and moves all information about the "delay" onto the user side, the server doesn't need to leak any information and doesn't need to store any new metadata. Could even be done with the older paste formats.

**Comment by rugk** [comment]
Okay, yeah as for TM, yes, no risk is currently attached there. Just thought it should mention that this can be an aim of an attacker and it is currently not possible for an attacker to get this kind of information. Just to describe it's value.

As for your idea it is the simplest one, but it would anyway always ask the user, even if the paste does not exist. This is not the best UX.
And I think the way I described it in https://github.com/PrivateBin/PrivateBin/issues/347#issuecomment-410853142, is totally a good solution, allowing us to get a nice UX for that, but also not lead data to third-parties.

**Comment by elrido** [comment]
So, let me aggregate our findings so we are on the same page with all of this:
* We threat modeled adding any kind of explicit or implicit "exists" API and found that:
   1. It poses no additional risks for regular pastes (but is not needed there anyway)
   2. It does introduce an information leak in the case of burn-after-reading pastes, in large parts reverting your efforts for #216.
* We agree that the "delay" is clunky UX, so it would be an optional feature that server admins could enable in the configuration (disabled by default)
* I assume that we agree that if we have to choose between bad UX or a security risk, then we certainly have to choose the UX issue (its optional anyway).

So, could the UX be improved with my proposal. Sure it can:
1. Server admin enables option for the added dialog on burn-after reading paste (or someone manually adds the parameter at the end of an existing burn-after-reading paste URL)
2. A visitor opens a URL of such a _marked_ burn-after-reading paste.
3. User gets "you can only view this once"-disclaimer and two options:
   1. Open the paste without password. If it was protected it gets deleted regardless, as not to risk that this attempt of opening the paste goes unnoticed be the real recipient.
   2. Open the paste with password. If the password is wrong, the paste gets deleted regardless.

Deleting the paste regardless when opened is due to your concerns for #216, thats not my idea. If you don't like that, then the server has to "lie" claiming the paste doesn't exist (otherwise we have the implicit exists API), not deleting the paste and the UI may offer the user another attempt. The problem is, that in this scenario you don't know if you mistyped the password or the paste already was opened.

Given the fuzz regarding #216, I assume that it would be preferable to you to keep deleting the paste if the password is entered wrongly in the burn-after-reading scenario. Or we make the not deleting the burn-after-reading with generic error a disabled by default option for admins, with warning that enabling this poses a risk that the user can't know if he typed in the password incorrectly and the paste remains on the server unread.

I think the above proposal gives the user a sufficient UX experience, covering the OPs request while keeping the one shot nature of a burn-after-reading intact. It's a compromise for securities sake.

I am of course open to other suggestions, as long as they don't introduce an "exists" API call, direct or implicit, and of course you may have better ideas how to handle this UX wise.

**Comment by rugk** [comment]
The 3 points you conclude are correct. 👍 

Now just 3.:

3. User gets "you can only view this once"-disclaimer and two options: 
  i) Get's option: "Open paste". Everything afterwards works just like the "usual" way a paste is opened currently.

That requires not much changes. 
Just when combined with https://github.com/PrivateBin/PrivateBin/issues/245, I think the password-unlocking will change a bit. But let's discuss that there.

> Deleting the paste regardless when opened is due to your concerns for #216, thats not my idea.

Not when opened, but _when encrypted content is downloaded_. Only slightly different, but a huge technical/security-specific difference.

And yes, we need to lie.

---

In any case, I think we also agree on that this issue and https://github.com/PrivateBin/PrivateBin/issues/245 must be combined. It's such a deep connection that is partly technically required.

**Comment by elrido** [comment]
If the lie is a concern: We already do that. To be able to read the metadata and find out that a paste is expired, it is loaded by the server. If it is expired, it gets deleted and the client gets the generic error, although the paste technically still existed.

So, how about we introduce the HMAC-thing during 1.3 format change and then cover this here in 1.4 with the other UX stuff?

**Comment by rugk** [comment]
No, it needs to be done together, and we need to talk about that stuff. I'll let you know later…

**Comment by elrido** [comment]
I'll close this one and suggest we conclude the discussion over in #245 as it should resolve this as well.

**Comment by rugk** [comment]
Uhm, I am actually not sure anymore why #245 would require such a "ore-display" page. (if no password is set obviously). Everything can be automated…

**Comment by elrido** [comment]
It was for the case of burn-after-reading pastes: add a warning before the client pulls the paste, as it is destroyed that moment.
