### ISSUE TITLE
PHP Fatal error:  Call to a member function prepare() on null

### ISSUE THREAD

**Issue by captainark** [PrivateBin/PrivateBin#37]
Hi,

I'm running PrivateBin on nginx 1.9.10, php5-fpm (5.6.22) and a MariaDB database running on a remote server.

I'm getting the following error message with the latest commit : 

```
2016/07/12 22:19:45 [error] 9048#9048: *379197 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function prepare() on null in /var/www/paste/lib/privatebin/db.php on line 423" while reading response header from upstream, client: 1.1.1.1, server: mydomain.net, request: "POST /paste/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mydomain.net", referrer: "https://mydomain.net/paste/"
```

I've pinpointed the origin of the issue to [this commit](https://github.com/PrivateBin/PrivateBin/commit/3b3b5277eb887f672547288a7f723c67bef9b4e3).

**Comment by elrido** [comment]
Thank you for reporting this!

I was able to reproduce this issue by having the configuration option `class` in the section `[model]` being set to `zerobin_db` instead of `privatebin_db`.

It's an issue introduced by the project renaming for users upgrading from the ZeroBin fork (not the original 0.19 version) to PrivateBin.

I am writing some new unit tests, a way to handle this case without being forced to change the configuration file and will soon provide a patch.

**Comment by captainark** [comment]
The issue is indeed fixed with the latest commit.

Thanks @elrido !
