### ISSUE TITLE
[Feature] Add I2p URL

### ISSUE THREAD

**Issue by asddsaz** [PrivateBin/PrivateBin#379]
**Feature**: Add [Eepsite](https://en.wikipedia.org/wiki/I2P#Terminology)

**Comment by rugk** [comment]
For the markdown auto-linking or what?

**Comment by elrido** [comment]
I tested some of the links at http://nekhbet.com/i2p_links.shtml and they all seem to work fine in either plain text or markdown mode. They look no different then other URLs, just an unofficial TLD, like onion (TOR network) sites, which also work perfectly well.

Closing this, for now. If we misunderstood, please feel free to provide an example, showing that it doesn't work, so that we can investigate.
