### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by zjagust** [PrivateBin/PrivateBin#384]
This is more a feature request than an issue. Also I apologize if this is already requested somewhere in previous issues; I would like the receiver of paste URL to see only the message sent to him/her, without PrivateBin UI being shown, or at least without an option to create a new message. I hope this will be possible. 

Thank you!

**Comment by rugk** [comment]
The receiver could just click on the "RAW text" button. However your use case seems to be different:
> without PrivateBin UI being shown, or at least without an option to create a new message.

So what is your use case here? Do you effectively just want the receiver to be prevented from creating new pastes?
If so https://github.com/PrivateBin/PrivateBin/issues/136 should cover that use case. Does that look good for you?

**Comment by zjagust** [comment]
Heh, this will only work if I allow access to everyone on my instance of PrivateBin, and then set the following:

<LimitExcept GET>
    Require user Administrator
</LimitExcept>

But then if I create a password, and send a link to my user, he/she will need to enter a password which is POST, and then again it will not work as user will get Forbidden from the server.

**Comment by rugk** [comment]
In https://github.com/PrivateBin/PrivateBin/issues/136#issuecomment-262990288, the user says:
> So the external user can only see shared links and cannot submit links himself

It just works with redirects, without passwords. Is not that, what you want?
So you need to filter by POST requests or so. You could also just limit POST or so, then you can be certain no data is created by that user. However, also self-destroying may not work then. Passwords in PB are entered and decrypted client-side, so that should work.

**Comment by zjagust** [comment]
Look, I believe this can be solved with redirects and rewrites on server side, yes, but I also see that a few people beside me asked for a same thing and it would be quite nice to have it as an option inside the application itself. We didn't ask for a workaround you are suggesting but an option of displaying only a message when paste link is created without any other options PB is offering. If this is to much to ask, than please say so and close this ticket. It's OK, we will understand.

**Comment by rugk** [comment]
It may be possible to do, I just don't know what exactly you'd like to see, and why.

So this feature requests needs a little more details:
* are you the server admin? Or should this be client-side only?
* no new pastes should be possible to create?
* what about comments? disallow these, too?
* is this about security (i.e. "no one should create a paste on my server") or something about usability (i.e. "users should not be distracted, because […]")?
* …

Also, what is your actual use case, i.e. *why* do you want that user interface you propose?

**Comment by zjagust** [comment]
I am a hosting provider running a dedicated WordPress hosting and one of the use cases I have is sending login credentials to end users. Since passwords are in question I would like to avoid sending these data over email and use your PB for that purpose.

Now I as server admin I would like to be the only one to have an access to a complete PB UI, and when I generate a message containing username and password for a new WP installation and PB generates a link which I then send to my user I would like that user can only see the content of the message, nothing else. Also I have no need for comments, I have disabled them anyway. 

So to make it even clearer, when end user clicks on a provided link generated by PB, I'd like him/her to see only content of my paste (username and password for WP login) and nothing else. 

I apologize if I didn't clarify it enough in the first place, but you have a great product and I would really like to continue using it, but I just need that option if possible. Thank you in advance.

**Comment by rugk** [comment]
> see only content of my paste (username and password for WP login) and nothing else

Unfortunately without any PrivateBin UI indication this is a potential security risk, as we also allow HTML/Markdown in the pastes. E.g. think of phishing by faking the PrivateBin UI or something like that. Thus, with _no_ UI it is not possible.

However, in other ways it may be possible. Maybe some kind of "slim/light" view mode for PrivateBin?

Note one thing is still not clear to me: Do you want to technically prevent users from creating pastes or just hide the UI that is shown for that? I.e. would it bad if they could still change the URL (to the `privatebin/` or so) and thus create a paste on your server?

**Comment by zjagust** [comment]
I see your point, it makes a lot of sense regarding security risks. And yes, other than me and my staff, I'd like to prevent all other users (our customers) to create pastes, yes, that is the ultimate goal. If it's too much trouble for you I can live with it as is, and set up server side redirects/rewrites and enforce usage policy with which users will have to agree.

**Comment by rugk** [comment]
So as this has come up for some times, I guess it's okay to take it as an "enhancement". Implementation details still have to be discussed though…

For now, I think, using server redirects etc. would be the easiest for you to setup.

**Comment by zjagust** [comment]
Thank you very much, it is much appreciated!

**Comment by johnwmail** [comment]
> The receiver could just click on the "RAW text" button. However your use case seems to be different:
> 
> > without PrivateBin UI being shown, or at least without an option to create a new message.
> 
> So what is your use case here? Do you effectively just want the receiver to be prevented from creating new pastes?
> If so #136 should cover that use case. Does that look good for you?

Hi, I want my privatebin only allow login user to create new paste,
guest (non login)user only can read the paste,
How to do that, if possible, thank.

**Comment by rugk** [comment]
@johnwmail Currently the only way is to use htaccess or so to restrict access to `/` without any parameters or so, similar to how it is done in https://github.com/PrivateBin/PrivateBin/issues/136#issuecomment-261571017.

**Comment by johnwmail** [comment]
Hi @elrido, your explanation is very clear, I understand and agree (privacy is this project goal), thanks.

**Comment by rugk** [comment]
Ref admin panel: https://github.com/PrivateBin/PrivateBin/issues/274

So okay, no login mode. However, what @zjagust's use case actually was: You want to hide the visible "Create paste" buttons etc. This is possible if you adjust the templates on the server.
This has also been requested in https://github.com/PrivateBin/PrivateBin/issues/386, so I've put it into the FAQ: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-link-to-a-real-rawread-only-mode-that-strips-create-paste-buttons-etc

Thus, this should satisfy your use cases.

**Comment by elrido** [comment]
To me, your message does read a bit like a demand. Sorry if I am interpreting this wrongly.

I have no intention working on this, as every server I know of (apache, nginx, lighttpd, etc.) can very easily be configured to provide such a functionality (I do actually run most of my webapplications behind webservers configured to enforce basic authentication protection for certain paths). I also don't think this is a "feature [...] in high demand", as we only had 3 such requests in the 5 years that I have been involved in this project.

Regardless: If you or anyone would like to implement this, pull requests are always very welcome.

Please do understand that this is free and open source software, we are not paid and usually every one works on what matters most to them. Yes, you can suggest a feature, but please don't expect that we all feel compelled to drop [whatever other features we are working on](https://github.com/PrivateBin/PrivateBin/projects/3), just on a whim. If you really do want this feature, please do consider contributing a solution to this project. Any contribution is appreciated very much.

**Comment by alxpettit** [comment]
1. I'm sorry I made you feel like I was making demands. That was not my intention. :(

2. Good to know that you accept pull requests. I might make a pull request if I continue using this. I was actually in the middle of brushing up on my PHP to see if I could come up with a half-decent implementation. (I'm more of a Python gal, so this is outside of my comfort zone.) Of course, if my code is bad then it's of use to no one. But it's good to hear that if I can manage something decent, it might be accepted and extend the abilities of the project. I'm totally open to doing that.

3. You seem very certain that functionality can be implemented in every major server. I don't know about that -- I have seen some very primitive ones, but I freely admit the only ones I'm remotely familiar with are Apache, Nginx, and an obscure Python-based one (more on the side of Apache, as I just started making full use of Nginx a week ago). Is there a sample configuration for Nginx that has been tested to be able to secure this app? Because... maybe it's just one of Nginx's many parsing quirks -- but `limit_except GET { deny all; }` is somehow blocking read access to the app, even when I put it in a limiting `location` block. So... that's pretty weird. But it wouldn't be the first time Nginx has done something to baffle me.

4. I personally don't see requests being duplicated that often (ideally, they should not -- obviously people should try to funnel everything into one issue thread to keep stuff organized) but the fact that this was duplicated three separate times kind of signaled to me that it was at the very least not an unheard-of use case -- especially since a limited portion of people actually bother to interact on these forums, I imagine. But fair enough -- perhaps I am overestimating the number of people interested in this.

5. I am aware of how FOSS operates -- I'm not new to this world. But I get that you must get a lot of people demanding things, and that must be frustrating. I don't intend to add to that. :(

**Comment by atmgnd** [comment]
with nginx, you can do use following configure, note I palce priveabin in a subdirectory

        location /pastebin
        {
                root /var/www/PrivateBin/;
                client_max_body_size 512M;
                try_files $uri $uri/ =404;

                location = /pastebin/
                {
                        set $realm off;

                        if ($is_args = '') {
                                set $realm "xxx";
                                # return 404;
                        }

                        auth_basic_user_file /etc/nginx/.htpasswd;
                        auth_basic $realm;
                }

                location ~ \.php$
                {
                        set $realm off;

                        if ($is_args = '') {
                                set $realm "xxx";
                                # return 404;
                        }

                        auth_basic_user_file /etc/nginx/.htpasswd;
                        auth_basic $realm;

                        try_files $uri =404;
                        # fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        fastcgi_pass unix:/run/php/php-fpm-www.sock;
                        include fastcgi_params;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        # fastcgi_param  SCRIPT_FILENAME  $request_filename;
                        fastcgi_param HTTPS on;
                        fastcgi_index index.php;
                        # fastcgi_param SERVER_NAME $host;
                }
}
