### ISSUE TITLE
Real raw/"direct download" mode

### ISSUE THREAD

**Issue by seblu** [PrivateBin/PrivateBin#386]
## Rationale

The current raw mode is not sending raw data, but rewriting the html document with &lt;pre&gt; tag over the content. Saving a raw document is in fact an html one. This is even worse when the document is not text at all, like pdf or pictures.

## Steps to reproduce

1.Upload a picture
2.Click on raw.

### What happens
Blank page

### What should happen
My picture should be downloaded.

## Basic information

**Server address**: https://paste.84.tech/

**Server OS:**:  official docker image

**Webserver:** 

**Browser:**firefox

**PrivateBin version:** 1.2.1

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment]
The raw mode is indeed source code.
Pictures are more or less "attachments" to pastes and thus the raw mode only refers to the actual paste itself.

So what is your actual use case? Why do you want a HTML-only document e.g.? Note for a view-only mode https://github.com/PrivateBin/PrivateBin/issues/384 tracks that. 

As explained in https://github.com/PrivateBin/PrivateBin/issues/270 I also doubt that raw mode is useful as it is. There is a preview, which renders everything and there should be a "source code" mode.

**Comment by seblu** [comment]
A typical use case is to send a pdf with credentials information inside to new users.
The link should make the pdf to be downloaded (or handled by the browser user preferences).

Another use case is to send text, like markdown file or every other format you can imagine, and saves (File->Save Page As) it in the correct format. Currently we get a html document.

This implies that the content or the file is sent directly to the client without html at all. I don't understand what's wrong in term of security with that, traditional pastes tools do that.

**Comment by rugk** [comment]
So okay, I get the use case.

The only thing you need to understand is: We need to open a browser tab and run JS to download & decrypt the paste actually. Thus, a thing like "File->Save Page As" will never work.
Also "traditional paste tools", where you can e.g. curl won't be possible. (unless you have a specialized CLI client, but that's another matter)

That said, is it really so bad if users still have to click on one link or so?

The thing why I care about security is just that when you serve an arbitrary file from the user in an URL they can choose, this can easily lead to security issues, e.g.:
* first, we cannot assure no other sensitive stuff is hosted at the domain PrivateBin is running from
* obviously I think phishing: What if one sends you a link that looks to be the login page from the domain you are looking at? What if there is a – hypothetical – `mybank.com/privatebin` instance, where you now get the fake login for `mybank.com`? The URL is the same.
  Or, even if it is a totally different URL, what are the legal implications when you as a PrivateBin admin are now probably hosting phishing pages? Obviously you could "save" "bad things" before, but if 
* XSS – I am not sure it would be possible, but given we e.g. allow users to serve HTML? One could probably embed it in an iframe even if iframes from foreign sites are not allowed?

---

So what I just meant that this has to be handled very carefully. 
Probably it could go fine with a whitelist, i.e. only some image types and PDF?

---

However, now comes the technical part: As said, we need to serve a HTML page first. We could probably trigger an automatic download, no problem. If so, the question of what we have succeeded just arises, as we cannot automatically close the tab and users would still see something like "Thanks for your download" or so, afterwards.

We cannot just serve it from the webserver, so that you can e.g. just direct-link to an image. We may be able to "redirect" to a blob, but also that poses a risk as [in WhatsApp](https://blog.checkpoint.com/2017/03/15/check-point-discloses-vulnerability-whatsapp-telegram/), where this exact behavior essentially let to the compromise of the local storage (again this is potentially a type of XSS).

> I don't understand what's wrong in term of security with that, traditional pastes tools do that.

Maybe give some examples. That may help, as it really matters what type of content (HTML; images, ?) they allow and in what way they serve it.

**Comment by rugk** [comment]
BTW, @elrido, what's your opinion on that?

**Comment by r4sas** [comment]
`/?raw=true&id#pass`

Handle page but without formatting of page, only scripts. Use some raw text while loading, like "Please wait...".
After decrypting replace HTML with paste content and base32 links to files. If file is picture (MIME detection) - print it before paste text and add link to save.
Don't forget to add `download` attribute to that links to prevent opening in browser.

**Comment by elrido** [comment]
@rugk I personally consider such a pure raw mode as rather risky. As you may remember, we already had security issues at least twice in the raw mode. This also seems to go counter to your plans of turning the raw mode into a tab of the full UI.

As a pragmatic workaround for @seblu I can recommend these two options:
1. In your PB instance, create a new template based on either the bootstrap or the page one, then strip it down as to only show the paste but no menu bar, logos, etc. - either strip out the HTML or introduce CSS to hide the elements that bother you. You can then use the [CLI client](https://github.com/PrivateBin/PrivateBin-Cli) to create paste on your instance and share the links it creates.
2. Create a second PB instance on a different URL, by symlinking all folders of the first, except the cfg directory. You can also just copy the folders, but the data folder needs to be shared between the two instances. One instance you set up with the stripped down template as described in 1., the other may be protected with basic authentication (or just an obscure URL) and can be used to create the pastes. The created URLs then are just changed to point to the instance with the stripped down template and will work, if the data folders are shared.

We could include such a stripped down template in our project, to support this special use case.

**Comment by rugk** [comment]
Oh, that template workaround is a good idea.

Thus, I consider this to be "fixed". A special implementation is risky on multiple fronts as we explained, but you can make your own template and strip stuff away you don't like. That's a good idea.

**Comment by rugk** [comment]
BTW this information now lives in the FAQ: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-link-to-a-real-rawread-only-mode-that-strips-create-paste-buttons-etc

**Comment by seblu** [comment]
I'm aware that clients need to understand _javascript_ to decrypt the data. So, unfortunately `curl` or `wget` cannot be used. But, fortunately, most of the users directly click on the link and expect either a website or a file to download. I was hoping there is a way in _javascript_ to replace the content of the decrypt page with the decrypted content, like an `exec`.

I realize that what I requested as _real raw mode_, could be achieved with an automated click on the `download attachment` button. As when I push a pdf (or image) through Privatebin, I had never written a text, I (wrongly) considered that  the attachment has replaced the text and became the pasted content. That's why I requested a real raw mode, to get the pasted content as it is. But I was talking of the attachment, not the text.

So, maybe I had been unclear but i'm looking for a way to automate the click to the download button. This is even better because it let me add a text when needed, and offer a direct access to the content of the users is looking for. _Privatebin_ is already able to download attachments, by clicking on the `Download attachment ` button. It even displays a preview in case of images. So I guess there is no security problem to allow a way to trigger the dowload with a `&download=1` parameter?

I finally find time to read the paper you pointed out about whatsapp and telegram. I understood that the issue is because they execute in some way the crafted vcard, or because they display a preview of a vcard and offer to download the vcard with an extension which make the system consider it as executable.

@elrido Thanks for taking time to suggest workarounds! I don't want HTTP auth, all users should be able to add paste or strip some part of the current website.

**Comment by r4sas** [comment]
curl / wget cant decrypt data, that's reason why it cant be used.
And adding such functional like getting paste information via plaintext is direct security leak.
But you can use API based clients: https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients

> &download=1

Better add one more instance of PBin with cleaned from page output template (as said before @elrido).
Make it like `raw.privatebin.com`, handle separated config file and use same data dir/mysql database.

**Comment by rugk** [comment]
Indeed [the "adjust the template" is the way-to-go here](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-link-to-a-real-rawread-only-mode-that-strips-create-paste-buttons-etc). You can add some JS there very likely that just then clicks the download button…

**Comment by seblu** [comment]
@r4sas I never suggested to use curl and I was pretty clear that I know we can't use wget/curl/http. I also explained why I'm not looking to display the pasted text without pastebin UI. I feel you didn't read my last comment.

@rugk Could it makes sense to add the JS which click on the download to the main template? There is no security issues to do that, right?

**Comment by rugk** [comment]
No, because this is an edge-case feature that not everybody wants.

**Comment by seblu** [comment]
Ok. Thanks.

**Comment by janmaroto** [comment]
I think this would be a really useful feature, at least for plain text.

I find myself constantly wanting to curl various things from servers or to use with some scripts.

Is it like this for anybody else?

**Comment by Dari4sho** [comment]
> I think this would be a really useful feature, at least for plain text.
> 
> I find myself constantly wanting to curl various things from servers or to use with some scripts.
> 
> Is it like this for anybody else?

I even went to quickly and installed it on my lab because I specifically need it for curl, just to end up disappointed and finding this issue because it doesn't work :D 

I use the raw feature on pastebin to curl and pipe contents into files on my linux machines, e.g. for initial ssh setup where copy paste is not viable.

**Comment by rugk** [comment]
Well it's a technical limitation as explained. Your cannot decrypt in an e2e way on the server so curl cannot just get it.

As said, just use one third party cli tool: https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients
