### ISSUE TITLE
Paste creation/expire dates: Reduce saved metadata/exactness?

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#391]
Keep in mind ["We kill people based on metadata"](https://youtu.be/UdQiz0Vavmc?t=27) so I thought that actually the paste creation date (and expire date) are some "valuable" meta data.

Thread model: You are a three-letter agency/some government or similar and know who created a paste and got the paste ID (but possibly not the encryption key/password). Thus, you cannot look at the content, but you can send a NSL and get the server admin to return you paste metadata. Assuming the server operator has no webserver logs or similar, the only information they get is from the PrivateBin meta data.
Now with an exact time, they can prove that to this exact time (3am in the morning) the user was using the PC and sending this paste. This may then correlate to events or just prove that they ware awake. In a trail, this can be helpful evidence (for whatever side…).

Thinking over https://github.com/PrivateBin/PrivateBin/issues/390 I got a few more ideas:
* Does it actually matter that the paste is deleted in the exactly in the exact time?
* Would not it make sense to reduce the exactness, probably when you select "30days" e.g. we can "round" to days, as it does not matter if it is deleted after 30,1 or 30,9 days…
* Or, if set to "never expire" could not we even just _not_ store the dates at all?
* We store an expiration date. Why do we actually "collect" (and store) a creation date separately? For verifying on the server that the expiration date (provided by paste creator on JS client) is not fake? Is this actually a real risk… the paste creator can choose these dates anyway as they wish…
   Okay, maybe we want to let the server admin restrict the dates they can choose and clients should not be able to circumvent that; but can't we just calculate the "correctness" of the data at the time we receive the paste on the server? After that, we do not necessarily need to store it.

This boils down to three ways of what to do:
* Leave it as it is, currently. AFAIK the exact time stamp is saved.
* Reduce the exactness, so the information saved is not too detailed
* Remove dates as much as possible. (would of course affect the UI, see https://github.com/PrivateBin/PrivateBin/issues/390)

What way to choose?

**Comment by elrido** [comment]
Eve is certainly not a passive attacker and actively undermining crypto standards and has also access to root CAs and can easily decrypt HTTPS on the fly via creation of signed server certs so you don't notice this. This isn't hypothetical, I am talking from personal experience, having worked in several corporate environments that routed all HTTP(S) traffic through blue coats for AV / blocking / logging - they had just deployed their own CA cert on all clients. Countries don't need to do that, they already have a root CA in your browsers trust store right now.

Granted, Alice' worst case scenario is not to obfuscate the creation time. But the point is that the creation time isn't leaked to Alice, but from her to the other actors.

I am not arguing with the trustworthy admins (probably most), which don't log and don't look up the creation time in the data store. Mallory represents the worst an admin could do. Even if our software wouldn't keep the time precise, they had the precise time in other sources.

On that note: When you say "round it", do you mean by several thousand seconds? Just rounding it by seconds or minutes would make it worthless to protect Alice. And with comments you can't do that be even seconds or the comments will be displayed in the wrong order (we currently order them by creation time stamp, we would need to introduce a sequence property to order them by which would need to be incremented every time and introduces yet another potential information leak).

I get the impression that you just feel unsure about that one property and instead of the obvious solution of just not leaking it in the API, you propose a solution that will cause so many side effects and require such an increase in complexity that it wouldn't be worth the benefit.

The point I try to make is: Not returning the creation time for the paste prevents the information leak to Bob. Eve and Mallory would have other ways of getting the data in ways we can't protect against, as long as we agree that our application is running on the current technology stack (TCP/IP, HTTP(S), DNS, PHP, JS).

We know that there are areas we can't defend against, as they require a radically different stack (end-to-end encryption using software installed through trustworthy, digitally signed sources on top of TOR or other internet overlays).

**Comment by elrido** [comment]
This was resolved in 9348cbe by just no longer exposing this meta data property in the API. Only the server retains that information via it's logs and by calculating the expiration timestamp minus the expiration setting (the latter isn't exposed in the API either, so visitors can't deduce this that way).
