### ISSUE TITLE
Hacker misused pastebin to publish adresses and private information

### ISSUE THREAD

**Issue by Solidarity16** [PrivateBin/PrivateBin#393]
Hello guys, 

someone has published the adresses, private photos and emails of hundreds of people he has hacked on a Pastebin site. He's targeted musicians and politicians who advocate for social justice and change. The data is humiliating, painful and above that a direct threat to the personal security of the targeted people. Please delete the Pastebin and all Pastebins connected to it. The address is:

[*link removed*]

**Comment by rugk** [comment]
It is very likely not a good idea to spread that link further in public issue trackers. Thus I've removed the link.

Also note that the link points to a server, we do not control. Thus, please contact the server admin of that server – they can remove the paste. A authorized party may have a look at the WHOIS data, to find out who is the server admin.
This is just the software and @elrido runs https://privatebin.net/. So if you find a paste on https://privatebin.net/, you can contact @elrido and let it be removed. Otherwise, there is nothing we can do.
