### ISSUE TITLE
Implement data storage method for storing traffic limiter, salt etc. in DB, not data dir

### ISSUE THREAD

**Issue by eddiemoto** [PrivateBin/PrivateBin#419]
**Why would we bother using the data directory when using a database?**

Is there a reason from a security standpoint to manage the traffic limiter from a file and not a table in the database?  

If this was managed via a table, there would be no need for a write access on any directory after installation.  I would think this would make installation easier and more secure.  I'm not expert, but I am curious.

**Comment by elrido** [comment]
There are multiple classes that extend "AbstractPersistence" and store their data in the data directory:
- traffic limiter
- the server salt (generated once per installation, used in delete tokens and other things)
- purge limiter (to ensure the purge cycle isn't triggered on every request)

All of these could be migrated into a database table of course (i.e. by using the existing "config" table), we would just have to do a similar abstraction like in the AbstractData classes to be able to handle both cases. At that point we probably want to refactor the table upgrade and creation mechanisms into a shared base class that we reuse in both places to provide the different interfaces for "AbstractData" and "AbstractPersistence".

So in other words: There is no reason (that I know) not to do that, just that no-one has bothered to implement that. Pull requests as usual are highly welcome.

Reg. making installation simple: One of the reason most installs prefer the file storage is that it has less requirements than the database one (requires having access to and creating a database plus credentials). Depending on your use case and your specific environment it may be simpler to install without database.

Reg. security: As long as both the database is inaccessible from the web and only by the PHP environment (via packet filtering or (docker/kubernetes/SDN) networking design) and the data folder is moved outside of the webroot (as described in the installation docs or using one of the container images that are designed that way), both of these methods are equally secure. The application has write/read access to both solutions, so if someone manages to execute arbitrary code i.e. via a PHP bug in your install, they can access and manipulate both of these solutions. Fortunately we do store only a minimum of data that isn't publicly accessible anyway.

**Comment by elrido** [comment]
There was a related discussion on this topic in #803 - I've created a branch "persistence-into-data" to work on. Please raise an merge requests related to this topic on that branch instead of master. I'll try to get a mockup of the new methods to handle generic key/value storage added into AbstractData this weekend. I'll keep this issue updated with the progress.

**Comment by rugk** [comment]
Just as a brainstorming idea: If you rewrote it to be generic, one could use Redis instead of a SQL db or so for the traffic limiter then. Redis is much simpler and faster as far as I heart and it's actually built for what exactly you'd want to do here, i.e. store key/values and quick access them.

(commented copied from https://github.com/PrivateBin/PrivateBin/issues/803#issuecomment-855419874)

**Comment by elrido** [comment]
Our paste and comment storage are essentially key/value as well (filenames as keys, json as the value), so really, that should just be a separate storage class for Redis. Any takers with php/redis know-how?

**Comment by elrido** [comment]
The scaffolding of the two methods is now in place:
https://github.com/PrivateBin/PrivateBin/blob/7bdcc2ae157036965268c429423b31de5a9ea6bf/lib/Data/AbstractData.php#L133-L152

The intent of having a namespace and optional key is for the traffic limiter array: We need to lookup or store a specific hash in it, but the other two persistence elements only store one value. It's up to the implementation (`Filesystem, Database, GoogleCloudStorage`) if they store all key/values in a namespace as one entity or can use the two components to speed up lookup and storage.

I'll focus on the `Persistence` classes (which need to be extended to allow the data storage class to be injected) and `Filesystem` first, `Database` second (since we store it all in files ATM, a migration of file into DB needs to be added). @mvanholsteijn, if you could look at the `GoogleCloudStorage`, please?

**Comment by mvanholsteijn** [comment]
@elrido Yes I will do that.

**Comment by mvanholsteijn** [comment]
I was wondering whether storing this data in a persistent backend is really essential? As far as I can see, the serversalt could be renewed  every restart without adverse effect on the operations of PrivateBin.  The delete tokens are stored with the paste and compared with the token given by the client. So deleting will still work even if the serversalt changes between two calls.

The purge limiter and traffic limiter may not work as precisely as when the state is centrally stored, but they will still work with state  stored locally. When running multiple servers, the purge limiter may just run slightly more often and  the traffic limiter may allow you to perform a few more pastes inside the time limit. Both would be acceptable behaviour to me.

Just my suggestion in an attempt to keep things as simple as possible.

**Comment by r4sas** [comment]
But anyways, isn't limits must be stored locally neither remotely to speedup rejecting pastes? In other case for every paste creation flood you must connect to DB/GCS/Redis to check state of lock. Just simple server overload...

**Comment by mvanholsteijn** [comment]
@r4sas If I understand you will, so you are in favour of keeping this server state locally too. right?

**Comment by elrido** [comment]
In a scaled out PrivateBin cluster, all instances in the cluster need to use the same shared storage for the server salt (which is really unique per cluster, not per instance), traffic limiter and delete token to work as intended. I checked the use of these items and the server salt is used in the following ways:
- in the latest server-side format of the paste, a unique salt per paste is generated upon creation. With these, indeed the shared storage isn't used and the delete token will work without a shared salt.
- Depending on the age of the setup in question, it may still contain older pastes that don't contain a unique salt, but require the shared server salt for the delete token to work. These pastes can't be deleted using the token, once the shared server salt is lost or changes.
- the traffic limiter uses the shared, stored server salt to generate an hmac of the IP, so leaking the traffic limiter file (and the server salt) doesn't risk exposing the IPs of the paste creators (even if these are normally only stored for a few seconds). If the server salt isn't shared, the traffic limiter won't work. On the other hand in that scenario you likely already use a load balancer and can use IP based sticky sessions to ensure the same visitor usually ends up on the same instance - so you could just turn off the traffic limiter (set it to 0 as documented) and handle any rate limiting on the load balancer.
- posted comments gets an icons (enabled by default), generated out of the traffic limiters hmac, added server side. Although the commenter name can be left blank or filled randomly, the icons make it visually easy to recognize if multiple comments got created by the same sender. Since this hmac relies on the server salt not to change, even across several days, load balancer sticky sessions won't be sufficient to guarantee that these will keep looking the same for the same IP.

If you want to avoid having to share the state, then I would recommend to disable the traffic limiter and icons. For a fresh installation the old paste format is not relevant and at least the delete token will work.

Just be aware that is not a recommended setup and the software is designed in the assumption that even in a distributed environment the storage, be that an NFS share or a relational or NoSQL database is able to scale as horizontally as the PrivateBin instances themselves.

Status of the branch:
- I had to add another method for storage implementation specific handling if the traffic limiter purge, done on each paste creation.
- Purge and Traffic Limiter got folded into the Filesystem storage

Still to be done: Server Salt, as well as the Database storage implementation - I realize that this change will require a migration of existing files into the database, at least for the server salt. It's probably acceptable for the traffic limiter and purge limiter to be lost, as they have a very high turnover rate.

**Comment by r4sas** [comment]
> @r4sas If I understand you will, so you are in favour of keeping this server state locally too. right?

I'm about more extended solution, where on first run that file would be created from data in GCM/DB/Redis, and later only checked for update periodically. Also when someone get blocked, update data in local file and in GCM/DB/Redis storage.

**Comment by elrido** [comment]
> I'm about more extended solution, where on first run that file would be created from data in GCM/DB/Redis, and later only checked for update periodically. Also when someone get blocked, update data in local file and in GCM/DB/Redis storage.

Ok, a local cache, that makes a lot of sense. I would suggest one of the in-memory caching solutions, and make use of them if available, for example [APCu](https://www.php.net/manual/de/book.apcu.php) or Memcache(d) (the latter two modules require configuration / APCu be detected and used automatically). And you're right, it would ideally be implemented on the storage layer, so it is transparent to the Persistence classes. I'd say that would be another task/ticket then this one.

**Comment by rugk** [comment]
As for caching usually Redis is used as a cache? At least Nextcloud does use it like this, as an option together with APCu etc
And I doubt saving a cache locally in a file would be a performance benefits.

These just as site-notes though I did not follow the whole discussion, so just take it as random input :stuck_out_tongue_winking_eye:
