### ISSUE TITLE
[Q] Issue Changing PrivateBin Display on Homepage

### ISSUE THREAD

**Issue by XXXTentacion** [PrivateBin/PrivateBin#420]
I've been attempting to change the area on the paste submission page. I've edited all of my language files found in /it8n folder with no luck. Any suggestions?

**Comment by r4sas** [comment]
Which one area?

**Comment by XXXTentacion** [comment]
The main page where a user can submit a paste.
I'm attempting to replace the "PrivateBin - Because ignorance is bliss."

**Comment by r4sas** [comment]
And how you changed it?

For example:
https://github.com/PrivateBin/PrivateBin/blob/0e18b5d0c1572a818df27811c8f0cb3e4bc549da/i18n/de.json#L5-L6

Here you must change only second line. All your text must be in quotes.

**Comment by XXXTentacion** [comment]
I've changed the quote in all of the /it8n/*.json files with quotations around them. For some reason, they still display the original text.

**Comment by elrido** [comment]
Sorry for the late reply. Did you really name that folder `it8n` instead of `i18n` (that is a _number one_, not a _letter T_). Not that all your issues are just caused due to a typo...

If the translation system doesn't find or can't parse the translation files, it will display it all in the default fallback, which is in English. Also make sure to only change the value (second quoted string, after the colon), not the key of the message, or it won't be found. (I think r4sas already mentioned that).

Finally, make sure your editor isn't messing up the quotes or breaking the text files otherwise by inserting incorrect character encoding or similar. These are UTF-8 JSON files, so the quotes need to be a "double tick" symbol ("quotation mark" or character 34 in ASCII) and not any other (unicode) character. Some editors change them depending on your language settings (Word for example, but surely you use a different tool to edit simple text files). Some editors (i.e. Notepad.exe) also mess with UTF-8 files and change it to some other text encoding that can't be interpreted as JSON by PHP or browsers.

**Comment by elrido** [comment]
closing this for now due to inactivity, feel free to reopen, when you had time to review the suggestions
