### ISSUE TITLE
Proper data format and structure of attachment

### ISSUE THREAD

**Issue by smsimeonov** [PrivateBin/PrivateBin#448]
I've been trying to put a POST to my internal PrivateBin instance, taking the information of the structure from:

[the official entry](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format)
I think this is incomplete, as this may be what it should be before it gets encrypted.
Examining the POST's thorugh the web interface, I can see its structure and the one for attachmentname is the same as data.

Now, looking at the form of the url, I have the following, which seems to work for the most part:

`'data:' + {{ mimetype }} + ';base64,' + {{ atchencoded }}`

And that all POST's fine, it is in the same format when I check it via a web browser, but on attempting to download the file, I get a significantly larger filesize than the one put in.

atchencoded just encodes the file, read in binary, as base64.

What am I missing here?

**Comment by elrido** [comment]
You are only looking at the encryption format. The full JSON REST API used is described in the [API docs](https://github.com/PrivateBin/PrivateBin/wiki/API#as-of-version-022). Note that this changes significantly with the release of 1.3 in the next few days.

**Comment by BigWax** [comment]
I have looked at the API page as well, but there wasn't anything specifying an attachment can be present there, as I saw in the source of r4sas's Python CLI [here](https://github.com/r4sas/PBinCLI/blob/master/pbincli/format.py).
I think I got it working anyway. Ansible was just adding data type to the binary string, malforming the resulting base64 string, as decrypting it included that type definition at the start of the file. I passed a plaintext file as an attachment in order to figure that one out. Once I stripped that, everything worked perfectly. Well, so far, at least.
And yeah, I read about the 1.3 changes and I am expecting it. I don't mind having to rewrite my logic. It seems like a more convenient API system anyway!

**Comment by cryptomilk** [comment]
The attachment format for v2 pastes: `data:[<mediaType>][;base64],<data>` is not fully desribed in the `paste_data_json` in the [Encryption Format](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format).

@elrido could you please update it?

**Comment by elrido** [comment]
I clarified the docs to state that it is a "data URI as per RFC 2397".
