### ISSUE TITLE
File upload : Data too long for column 'data'

### ISSUE THREAD

**Issue by Salokyn** [PrivateBin/PrivateBin#456]
## Steps to reproduce
1. Activate file upload
2. Use database model (I use mariadb 10.3 and the instructions of INSTALL.md to create the tables)
2. Upload a file greater than 64kB

### What happens
Error : `SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'data' at row 1`

### What should happen
I'd like the file to be stored in DB

## Additional information
As far as I noticed, attachments are stored in `data` column (BLOB(64kB)). So I wonder what is the use of `attachment` column (MEDIUMBLOB(16MB)).

## Basic information
**Server address**: Private
**Server OS:** Debian 9
**Webserver:** nginx
**DB server:** MariaDB 10.3
**Browser:** Chrome 75
**PrivateBin version:** 1.3

I can reproduce this issue on <https://privatebin.net>: No since fileupload is not activated.

**Comment by elrido** [comment]
The `attachment` column is no longer used with the version 2 format pastes, but still is used by your older uploaded files before the migration to 1.3 (if there are any). The unit tests use relatively small texts, so the `blob` limitation hadn't been noticed.

My suggestion for your use case is to `ALTER TABLE` the `data` column to a `MEDIUMBLOB` as well.

**Comment by Salokyn** [comment]
Ok, thank you for the information. So eventually, since I do not have old pastes, could I `DROP` the `attachment` and `attachmentname` tables without breaking anything?
Is there any other useless fields in the current version?

**Comment by Salokyn** [comment]
> So eventually, since I do not have old pastes, could I `DROP` the `attachment` and `attachmentname` fields without breaking anything?

I tested this and that's not a good idea since it breaks the `INSERT` in `paste` table.

**Comment by elrido** [comment]
If we want to remove columns, then we need to provide an upgrade path in the servers database migrations. I could not think of a way to do it in this case, since that would require the server to decrypt and re-encrypt the data with the attachment included, in the new paste format. As the server doesn't know the key, that isn't possible.

There is also no gain in dropping the column, as it will not use much space (a DBMS may store a NULL byte to mark empty columns or have some other short marker to describe a NULL entry) and won't slow down queries as it isn't indexed and not used as a `WHERE` condition. It would be purely OCD - which I do fully understand, but unfortunately I see no easy way in removing it without breaking legacy paste support.
