### ISSUE TITLE
Fix missing translation of 'Decrypting paste…' with now loaded language fr

### ISSUE THREAD

**Issue by Salokyn** [PrivateBin/PrivateBin#462]
## Steps to reproduce
1. Go to a privatebin instance
2. Check browser console 

### What happens
Console message : Fix missing translation of 'Preparing new paste…' with now loaded language fr (privatebin.js?1.3:510).
Though, the phrase is well translated ...

### What should happen
This console message should not appear since everything seems to be fine.

## Basic information
**Server OS:** Debian 9
**Webserver:** ngnix
**Browser:** Chrome 75, fr localization
**PrivateBin version:** 1.3

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment]
Indeed, it seems to be translated:
https://github.com/PrivateBin/PrivateBin/blob/ae456bf7a1330d833686f062bbf1e84b4f91f517/i18n/fr.json#L160

Does it happen witha ny other language, too?

**Comment by elrido** [comment]
This is a `console.info` from the async translation system that got introduced in 1.1 - have been seeing these ever since - happens in any language except English.

I'd consider this to be a debug statement. Missing translations will show up as `console.errors` instead. I wouldn't mind if we get rid of those debug statements.

**Comment by rugk** [comment]
Ah yes, it says "Fix missing translation of " - maybe that wording is a little confusing since the translation was only "temporarily" "missing". (And I've added this system, so bad I don't even remember that message. Clearly shows it's a bad one. 😜)

So at least the wording should be corrected. Or we drop that message altogether.
