### ISSUE TITLE
PHP Coding Style / PSR-4

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#47]
When adding some [code style guides](https://github.com/PrivateBin/PrivateBin/wiki/Development#code-style) I noticed we do not have any PHP style fixer yet.

I would recommend http://cs.sensiolabs.org/, which can also automatically clean up your files.

**Comment by elrido** [comment]
If we go for PSR-1 or PSR-4 compliance, we definitely should also start to look into namespaces. Which would then also push the minimum requirements up to PHP 5.3, which would be completely fine by me, as mentioned previously.

**Comment by rugk** [comment]
Apropos PHP version: You forgot to transfer [this issue](https://github.com/elrido/ZeroBin/issues/100), so I have done it now: https://github.com/PrivateBin/PrivateBin/issues/48

**Comment by rugk** [comment]
Well [PSR-4](http://www.php-fig.org/psr/psr-4/) would certainly be nice. You could also drop the custom autoloader in this case.

**Comment by elrido** [comment]
Ok, I'll start to look into PSR-4 and hope to know enough on it to implement it around the weekend (I'll self assign this issue when I start working on it).

**Comment by Sobak** [comment]
I can do this, go for PSR-4 (using composer). This could be done painless if we decide to use `/lib` as a directory for our sources, but other way it means changing names of many files... What is going to happen anyway, if we're going for PSR_2 as well and we should do this as a part of this issue as well.

Once again, it  means huge diffs, making `git blame` completely unusable at this moment, but IMO we should absolutely go for it - the sooner the better.

**Comment by elrido** [comment]
That would be very kind of you @Sobak.

Regarding namespaces: Please use `PrivateBin` as the vendor namespace prefix and `lib/` as the base directory. We can of course rename all the classes to UpperCaseFirstLetter form:

- Configuration
- Filter
- I18n
- Model
- Model_Abstract
- Model_Comment
- Model_Paste
- Persistence
- PrivateBin
- PrivateBin_Abstract
- PrivateBin_Data
- PrivateBin_Db
- PurgeLimiter
- Request
- ServerSalt
- Sjcl
- TrafficLimiter
- View
- VizHash16x16

**Comment by Sobak** [comment]
Hello @elrido!

I'm already working on the patch. `lib/` is the base directory and `PrivateBin` is a main namespace, so I'm glad that think alike.

The only difference in my approach and list you have proposed are classes using underscore in their names. Accordingly to PSR-4 they need to be under subnamespace in order to load them from subdirectory. So, there is `Model/Paste`, `Model/Comment` etc. 

The thing is - we cannot create `Model/Abstract` because of the collision with PHP keyword (it would be possible in PHP 7.0, I think, but it's irrelevant). I named them `AbstractModel` and `AbstractData` - it of course can be changed to some other naming convention, but I think it should be discussed when I send Pull Request.

Last question - do you preffer PSR-4 (autoloading) and PSR-2 (coding style) in one Pull Request or two separate? I plan to base the former on the latter (because for know, I have FQN like `PrivateBin/data/AbstractData` or `PrivateBin/configuration` in PSR-4 patch), but they can be separated for the sake of separation.

**Comment by elrido** [comment]
That sounds great! Didn't know you could map namespace to paths. I don't mind if it takes longer if it makes it easier to do both in one pull request. We are not in a hurry. Let me know if we can support you in any way.

**Comment by elrido** [comment]
I just finished renaming all the classes n' stuff regarding the PSR-2 rules. Would be glad if you could have a look and let me know if there is anything else to do to fulfil this task.

**Comment by rugk** [comment]
Please also note that this issue originally was about something else and PSR-4 is only one aspect...

**Comment by elrido** [comment]
I just tested `php-cs-fixer fix lib/ --level=psr2` and had only found one small missing linebreak which I committed to identicons branch.

Level `symfony` wants to change really odd things, though. I don't like the readability when spaces get removed between concatenated strings or in mathematical operations. But those are just my personal style preferences.

**Comment by rugk** [comment]
That's why you can configure it with a PHP file. You

> I don't like the readability when spaces get removed between concatenated strings or in mathematical operations.

I too. Use `concat_with_spaces` and `ternary_spaces` e.g. Here is an [example file](https://github.com/rugk/threema-msgapi-webui/blob/master/.php_cs).
You should just use PSR-2 and select the symphony (and user submitted) rules, which match your coding style.

**Comment by rugk** [comment]
So when you add the config file we can close this issue.
