### ISSUE TITLE
Bumping minimal required PHP version?

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#48]
Continuing https://github.com/elrido/ZeroBin/issues/100

----

Version overview:

Description                                                               | PHP version
---------------------------------------------------------------- | ----------------
Current minimal version | 5.2.6
Confirmed working | 5.3
Oldest Travis test | 5.5
Oldest official PHP release with security fixes | 5.6 (soon)
Oldest Debian version with security fixes | 5.4.4 (Wheezy)
Oldest version @elrido wants to support | 5.5
Latest version @elrido considers a "safe change" | 5.5
Oldest version required for PSR-4 (see #47) | 5.3

**Comment by rugk** [comment]
@elrido Maybe doing one bump with "Next release", or rather later?

**Comment by rugk** [comment]
BTW if I compare these two lines it is quite clear to me to what version we should switch:
* Oldest version @elrido wants to support
* Latest version @elrido considers a "safe change"

There is some overlap... :laughing: 

However this means we do not support Debian Wheezy anymore. (I mean it is outdated anyway...)

**Comment by elrido** [comment]
I think we need to talk about two separate things here:

In what way does it hurt us, if we keep the **hard coded limit** as low as it is known to work? If some admin runs it on an old non-supported PHP version it is risky, but that is none of our business to decide.

This is free (in the sense of freedom) software after all. The hard coded limit IMHO is just there so a server admin gets a clear error message if he or she tries to run the software on a host that is incompatible with PrivateBin. This will soon be PHP 5.3 if we implement #47.

I agree that we should clearly communicate that we strongly suggest to use at least the lowest PHP version that we regularly run tests on and hence can honestly be called **supported** by us. And there I agree we should communicate that PrivateBin **supports** PHP 5.5 upwards (and HHVM too, if Xdebug would work in it for unit testing).

**Comment by rugk** [comment]
So we should have an "hard coded limit" where technically everything should work and advertise another minimum version (in the Readme and so on) where everything is confirmed to be working (= which Travis tests)?


#### So this is how you would do it?

Version decription                                                     | PHP version
---------------------------------------------------------------- | ----------------
hard-coded limit (technical working) | 5.3
advertised limit | 5.5

If so I think that's okay. Now we just have to adjust the doc and the code a bit...

**Comment by pozzo-balbi** [comment]
Hi, my 2 cents from the point of view of an admin is really the chicken or egg problem. I personally am switching to php 7.0 where possible due to the increase in speed over any older php version available. Some claim up to 100% speed improvement of php 7.0 over php 5.6.  From a compatibility view there are quite a few modules available in php 5.6 missing in php 7.0 most notably memcache when running on Red Hat 7 / CentOS 7 / Scientific Linux 7 with Webtatic repo. Php 7.0 is also available for Red Hat 6 and clones. I don't know about Debain / Ubuntu / etc. but it should be similar in the sense that an upgrade of php to 5.6 or 7 should not be too painful. So if increasing to php 5.6 helps improve the quality of the code, go ahead and see it as an incentive to the admin to upgrade php as well. Speed and security will thank.

**Comment by elrido** [comment]
Just a short update on this: It was bumped to PHP 5.3, due to the namespace introduction in 5d7003e.

I therefore consider this closed for now, but of course feel free to open it again later, i.e. when new important PHP features require raising the level or simply when down the line version 5.3 gets out of use even on the most ancient stable distros.

**Comment by rugk** [comment]
So, do we officially advertised 5.5 now as a requirement?

**Comment by elrido** [comment]
In any documentation we should of course correctly state 5.3. But I don't mind if we add in brackets something like "we strongly suggest to use PHP 7 or at least 5.5 for best security and performance".

**Comment by rugk** [comment]
I think to suggest PHPv7 is a bit too much, but if you want... :smile:
