### ISSUE TITLE
DB IDs: Get rid of MD5

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#49]
I am surprised to see how much [MD5 is used in PrivateBin](https://github.com/PrivateBin/PrivateBin/search?utf8=%E2%9C%93&q=md5&type=Code).

Especially why on hell is the the paste id derived from the (presumably) plain text content?
I mean it may be difficult but it basically means that 

And also [this comment](https://github.com/PrivateBin/PrivateBin/blob/002046cc6283ce62b2850a70f29f096cf29a66c8/lib/model/abstract.php#L106-L107) is really ridiculous:

> // We just want a small hash to avoid collisions:
> // Half-MD5 (64 bits) will do the trick

Wait, no! MD5 is not collision resistant at all and fundamentally broken.

I mean completely irrespective of the security impact of MD5 used there, there should not be a single MD5 hashing in a security product. Even if there would be no impact (which I highly doubt) it is a bad image...

**Comment by rugk** [comment]
So as for [the part with the comment](https://github.com/PrivateBin/PrivateBin/blob/002046cc6283ce62b2850a70f29f096cf29a66c8/lib/model/abstract.php#L106) it seems the data is already encrypted. However - in this case - it is unclear why we need a hash there at all.

There might be one problem: You should never trust the user input, so you can imagine an attacker crafting a special data, which is valid encrypted data (according to `sjcl::isValid`), but which begins with a string (or which is MD5 hashed begins with a string) which is already existent in the database. Could not he then overwrite the existent data?

**Comment by elrido** [comment]
The usage of MD5 in PrivateBin is uncritical. Its only used to generate UIDs. Its not used in the crypto.
And nope, it checks if the paste already exists and would never let you overwrite an existing paste. And no, the ID is never generated based on clear text.

This is not a security issue, closing this.

**Comment by rugk** [comment]
Hmm, okay. But in this case why do we need MD5 hashing at all? I'd rather remove it then as it has no influence on the security (which is wrongly claimed by the one comment I pointed out) and is only bad advertisement.

So, okay, let's call this a "code style" issue.

**Comment by elrido** [comment]
Dude, no offense, but please do you read the codes surroundings before making such claims as in your original post.

Of course we all agree, that md5 should no longer be used for _digital signatures_ due to the known collision attacks and neither as a _one way encryption_, as by now it is absolutely feasible to use existing or generate your own rainbow tables to get some matching content for any given md5 hash.

What do we use md5s for? We mainly use it in the [setData methods of the paste and comment models](https://github.com/PrivateBin/PrivateBin/blob/002046cc6283ce62b2850a70f29f096cf29a66c8/lib/model/abstract.php#L93) to quickly and cheaply generate an ID. The paste and comment IDs are 8 bytes (64bits) long, stored and displayed in hexadecimal notation, which makes them 16 character long strings (This means that on one install of PrivateBin you are limited to a maximum of 18'446'744'073'709'551'616 simultaneously stored pastes). We could also use some other way to generate the IDs, e.g. `bin2hex(mcrypt_create_iv(8, MCRYPT_DEV_URANDOM))`. Changing this mechanism has a low risk of breaking the service and should not cause any backwards incompatibilities, as long as it still results in a 16 character long (lower case) hexadecimal string.

Collisions can still happen, regardless of the mechanism to generate the ID. That's why there is [this check](https://github.com/PrivateBin/PrivateBin/blob/002046cc6283ce62b2850a70f29f096cf29a66c8/lib/model/paste.php#L79), leading to the infamous "You are unlucky. Try again." error message. This could once be triggered quite easily by simply double-clicking on the "Send" button, before [we patched that](https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L970).

Regarding [vizhash](https://github.com/PrivateBin/PrivateBin/blob/38ab755733f6c5828eac8a1ecaea9708263430e3/lib/vizhash16x16.php#L92): There it uses md5 (and sha1 and even strrev) to generate a long string as input to draw the image. This might be dangerous if we would not send it a [sha256 based HMAC](https://github.com/PrivateBin/PrivateBin/blob/002046cc6283ce62b2850a70f29f096cf29a66c8/lib/trafficlimiter.php#L100) as an [input](https://github.com/PrivateBin/PrivateBin/blob/002046cc6283ce62b2850a70f29f096cf29a66c8/lib/model/comment.php#L184).

You can experiment if the resulting PNGs still look acceptable, if you replace the hashing in vizhash with stronger algorithms. But there you can't switch from hashing it to random data. Otherwise the same input will no longer generate the same output image.

**Comment by rugk** [comment]
> but please do you read the codes surroundings before making such claims as in your original post.

Well... my idea was based on one comment:

```php
// We just want a small hash to avoid collisions:
// Half-MD5 (64 bits) will do the trick
```

And I think we agree that this (MD5 = "avoid collisions") is non-sense. :smiley: 

> We mainly use it in the setData methods of the paste and comment models to quickly and cheaply generate an ID. The paste and comment IDs are 8 bytes (64bits) long, stored and displayed in hexadecimal notation, which makes them 16 character long strings (This means that on one install of PrivateBin you are limited to a maximum of 18'446'744'073'709'551'616 simultaneously stored pastes).

Yeah, okay. But why do we need MD5 for that?

This should basically do the same:
```php
$this->setId(substr($data, 0, 16));
```

And yeah to choose them randomly would maybe be better, I agree.

> Changing this mechanism has a low risk of breaking the service and should not cause any backwards incompatibilities, as long as it still results in a 16 character long (lower case) hexadecimal string.

Really? But old pastes must still be recognized after an update and if the ID is different.
If this is right, there is not much which speaks against changing it. (whether we just remove the MD5 or use another way

----

So vizhash...
It is quite much related to https://github.com/PrivateBin/PrivateBin/issues/50.

Here again the same question: If the data is already hashed strongly, why do we need to hash it again at all? It only decreases the length and AFAIK vizhash should look nice even with long strings. (At least it was okay, when I [tested it](https://jsfiddle.net/2nYsg/3/embedded/result/))

**Comment by rugk** [comment]
> and even strrev

Yeah, it "even" reverses the string. :laughing: 
The comment says "more data to make graphics". If that's true it is okay, I am just not sure why reversing a string would make "more graphics". I just tested it with a random SHA256 hashed string and it looks like this (the above is the reversed string):
![reversestring](https://cloud.githubusercontent.com/assets/11966684/17017635/67db43ae-4f34-11e6-80ee-90d95d5095bc.png)

**Comment by rugk** [comment]
Live example here: https://jsfiddle.net/2nYsg/12/

This are just some strange design decision, and - as said - you're right it is not security-related. That's also why I tagged this with "code style"/"code quality".

**Comment by rugk** [comment]
So, I've concretized the titles, so we can discuss VizHash and DB Ids separately. #50 is now especially about VizHash and this about the DB ids.

**Comment by elrido** [comment]
> And I think we agree that this (MD5 = "avoid collisions") is non-sense.

You are misunderstanding the comment: Here it is not meant that the md5 would not contain collisions. It is talking about the range of possible IDs. Less risk of collisions within the space of the IDs, hence we use 64bit ID. It is irrelevant if any collisions happens (because it will not overwrite pastes), it is just important that these happen only very rarely. And yes, that is a problem that you have with any GUUID generation mechanism.

> This should basically do the same: $this->setId(substr($data, 0, 16));

Not at all. Have you ever looked at a stored paste? [Here is one](https://github.com/PrivateBin/PrivateBin/blob/002046cc6283ce62b2850a70f29f096cf29a66c8/tst/bootstrap.php#L27). The first 16 Characters are `{"iv":"EN39/wd5`. These are not in hexadecimal notation and the first 7 are always the same. Random data would clearly be better.

> But old pastes must still be recognized after an update and if the ID is different.

The IDs of the old paste never change. The ID is only generated once, when a paste is stored. Afterwards they are immutable. As long as the format stays the same (16 Characters in lower case hexadecimal notation, well, [this check](https://github.com/PrivateBin/PrivateBin/blob/002046cc6283ce62b2850a70f29f096cf29a66c8/lib/model/abstract.php#L155) to be precise) it will still work.

> vizhash

The library needs to have some amount of data to produce various random effects, colors, geometric shapes for the vizhash. The given string might not be long enough (was especially true with the IPv4 addresses that were originally used (which actually was a security issue)).

When you test, always the same string into the function, but change the lines [92 and 93](https://github.com/PrivateBin/PrivateBin/blob/38ab755733f6c5828eac8a1ecaea9708263430e3/lib/vizhash16x16.php#L92). The output will of course be different, the question is, is the complexity of the image the same or not?

**Comment by rugk** [comment]
> and the first 7 are always the same.

Well... these could be skipped.

> These are not in hexadecimal notation

Ah all right. That's an issue. But still no reason for MD5, Base64 would do the job too.

> The IDs of the old paste never change.

Yeah, that's what I though too. Thanks for confirming it.

> The given string might not be long enough

Reply coming soon in #50.

**Comment by elrido** [comment]
Ok, lets just generate random IDs on the server then. I don't like the idea to use something sent by the client unchanged. It would be better if the paste ID returned by the server is unpredictable to the client and not connected to any client input at all.

Thumbs up for:

    bin2hex(mcrypt_create_iv(8, MCRYPT_DEV_URANDOM))

**Comment by rugk** [comment]
> I don't like the idea to use something sent by the client unchanged.

I too! :+1:
However that is what basically happens. You cannot see MD5 as any change of the client values. At least not an unpredictable change. It might even be only merely some obfuscation.
The issue is: I don't like using something for the client **at all**.

> It would be better if the paste ID returned by the server is unpredictable to the client and not connected to any client input at all.

Indeed and with the current solution this is not the case.

You just say all I am arguing for. It's just that MD5 is predictable (you need to use some processing power, but it is possible). MD5 is broken and therefore we cannot consider it's output unpredictable. (Practically it may be hard, but we should see it in a theoretical way.)

**Comment by elrido** [comment]
Don't mix the two arguments: Creating a hash from user content and just returning content as given by the user unchanged are two very different things.

I don't mind to change it. But I do care about doing it for the right reasons. I got the impression from your previous posts that we should just get rid of md5 on principle, because md5 is "broken" for any possible use case. And this just isn't true.

**Comment by rugk** [comment]
> Creating a hash from user content and just returning content as given by the user unchanged are two very different things.

Okay, then not completely remove it, but BAse64 encode it. This now makes no difference to MD5.

> I got the impression from your previous posts that we should just get rid of md5 on principle, because md5 is "broken" for any possible use case. And this just isn't true.

It is true. Where we use MD5 we could e.g. at least use SHA-1.
Because MD5 provides a false sense of security, because when you just want to make a string DB-compatible (where MD5 is used here obviously) you can use Base64.
Or just make it random as you already said. This also has the advantage of being more unpredictable and causing less errors.

**Comment by nitmir** [comment]
md5 must only not be used for crypto. For any other use case, it is steel a good hash algorithm, as CRC can be.
md5, as a hash algorithm ensure that few change in the user input cause a completely different id to be generated (with CRC  too). This is obviously not ensured by using the bas64 of the start of the user returned answer.

There is no sense of security to have just to generate id that are checked anyway before using them.

However, I see a case where using a randomly generated id is better: if the id computed collide with a previous id, we could just try to generate a random new one until we find one that is not in use (with a fail-safe like only try a most the generate 10 ids). Hence the message "You are unlucky. Try again." would virtually be never displayed to the user (al least not before the id space is used at more than 99.9% with 10 ids generation try, on average).

**Comment by rugk** [comment]
> md5, as a hash algorithm ensure that few change in the user input cause a completely different id to be generated (with CRC too). This is obviously not ensured by using the base64 of the start of the user returned answer.

Hmm, yeah. Good argument.

The on-fail use random string, might be a good idea indeed. 

So maybe we really keep MD5. Or we Base64 the current6 time e.g. instead of pad content, which would also result in quite unpredictable results.

**Comment by elrido** [comment]
Addendum: I noticed that PHP supports [fnv1a64 hash algorithm](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function), which produces exactly 64 bits as output (which is the length of our paste/comment keys). We could avoid [cutting the md5 in half](https://github.com/PrivateBin/PrivateBin/blob/master/lib/Model/AbstractModel.php#L117) and it would be [slightly faster](https://stackoverflow.com/questions/10070293/choosing-a-hash-function-for-best-performance#answer-43464438). Using a non-cryptographic hash function would also avoid any misinterpretation of the use of md5 as a GUUID source.

Or we get rid of the protection against creating duplicate pastes, provided by the checksumming of the received paste and just [generate a totally random ID as suggested earlier](https://github.com/PrivateBin/PrivateBin/issues/49#issuecomment-234224302). It mainly is intended to protect against overflowing the servers diskspace by a malicious client that sends the exact same paste over and over again. Using a checksum at least forces such an attacker to increment its content before resending it.

**Comment by rugk** [comment]
> Using a checksum at least forces such an attacker to increment its content before resending it.

Well… that is not really hard… :thinking: 

A real brute-force protection or so would likely help more, here. :smile:

**Comment by elrido** [comment]
Can you be more specific on what you consider a "real brute-force protection", please? Also, what do you prefer: Leaving the md5 as is, switching to another checksum algo in the hash function or creating a random ID?

Apart from this mechanism we also have the rate-limiting which prevents posting more then one paste/comment every 10 seconds, based on the IP of the sender.

The idea here is that its a one liner in bash to curl the same content over and over, while it requires an additional command to generate a different payload every time, when checking the content. The rate-limiting forces the attacker to add a "pause 10" and/or have multiple IPs at her/his disposal.

Then again, in most setups it will be much easier to just overflow the webserver offering the service with requests or by [opening several thousand simultaneous connections](https://idiallo.com/blog/c10k-2016). I doubt that many folks run PB on a load-balanced, auto-scaling cloud setup. The current mechanisms are supposed to make it a tad bit more difficult for the wanna-bees.

**Comment by rugk** [comment]
Yeah, just thought about rate-limiting.
So that said, I like the idea.

Or, as you said, generate it randomly/just count it.

> The idea here is that its a one liner in bash to curl the same content over and over, while it requires an additional command to generate a different payload every time

I am just saying that this is not that effective. I mean, okay, no one-liner possibly now, but two lines (i.e. append a new character or count one number up). We cannot even force the attacker to use encryption (which could slow-down an attack) this way, as they can just change the ciphertext.

It does not hurt though, if the hashing is fast. (Or maybe a random number generation is faster? As a DOS attack could of course not only aim at disk space, but also CPU usage...)

**Comment by elrido** [comment]
We do have the [rate limiting](https://github.com/PrivateBin/PrivateBin/blob/master/lib/Persistence/TrafficLimiter.php#L20), it's even [configurable](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#trafficlimit). And yes, we do [force](https://github.com/PrivateBin/PrivateBin/blob/master/lib/Sjcl.php#L96) the attacker to send encrypted or otherwise high entropy data. They can generate random data, but then have to compress and base64 encode it every time, to ensure it passes the checks and actually gets stored on disk.

Do I understand you correctly that you do prefer a hash over a random ID? I assume the random ID is faster then hashing the paste, but I would choose added security over performance.

**Comment by rugk** [comment]
> And yes, we do force the attacker to send encrypted or otherwise high entropy data. They can generate random data, but then have to compress and base64 encode it every time, to ensure it passes the checks and actually gets stored on disk.

Our check only checks the entrophy somewhat. So when you have a high-entrophy (i.e. random) text, you can just change one char, it will likely still pass the check.
So no, the attacker does not have to do any base64 or so.

> Do I understand you correctly that you do prefer a hash over a random ID?

I don't care.

> I assume the random ID is faster then hashing the paste, but I would choose added security over performance.

The thing is what threat is more serious:
* added CPU load due to slower hash algo instead of random ID -> could lead to CPU DOSes
* attackers throwing lots of the same paste to the server -> could lead to disk space problems

**Comment by elrido** [comment]
> So no, the attacker does not have to do any base64 or so.

Yes, [we do](https://github.com/PrivateBin/PrivateBin/blob/master/lib/Sjcl.php#L64).

> > Do I understand you correctly that you do prefer a hash over a random ID?

> I don't care.

Ok, so what do you suggest to do? Close the issue and leave as is?

**Comment by rugk** [comment]
Okay, so at least one has to craft a valid base64... (but it does not matter what it decodes to... one char difference is still one char difference decoded)

I don't care [whether we use random IDs or this hash algo]. It ends in the same: one way or another, there are advantages or disadvantages with both approaches. I don't think anyone is particularly better, so feel free to implement anyone. 😄

**Comment by elrido** [comment]
Ok, thank you, that is what I wanted to know.
