### ISSUE TITLE
Request Landing Page for Automated Email Scanning of Links 

### ISSUE THREAD

**Issue by SethBodine** [PrivateBin/PrivateBin#529]
Not sure if this is captured somewhere else - or is available via a different feature, but several automated DLP/IDS/EPP services pre-load and validate content of URLs sent via email.

I cannot, and do not want to enforce a passphrase for every password (going to be used internally), however these scanners will invalidate burn after accessing the payload.

onetimesecret does this simply by presenting a "once you view this, it's gone" page before showing the actual message.

**Comment by rugk** [comment]
The landing page thing is basically a dupe of https://github.com/PrivateBin/PrivateBin/issues/347

However, the current solution for your problem is a bit detection, which is already implemented. Do you e.g. have a user agent string, which could be detected and the bot thus blocked and stopped from autp-deleting a paste?

**Comment by elrido** [comment]
In addendum: As long as these services don't execute the JS and therefore retrieve the paste, they won't trigger a deletion of the burn-after-reading paste. For any examples of services that do, please do provide the user agent header as suggested by @rugk, to be included in the existing bot detection mechanisms, denying these services the access.

**Comment by SethBodine** [comment]
thanks for the fast response - apologies for not taking more time to review previous bugs/requests

**Comment by rugk** [comment]
I don't see how the issue is closed yet. As said, can't you provide a user agent? (Or does it not execute JS?)

This would solve that problem once for your and for all others with the same software.

**Comment by SethBodine** [comment]
User agents aren't always fixed, and could easily be circumvented. Unfortunately as there are so many scanning services, I'm sure some are already sandboxing the website (preempting when all things scan all of the things for badness).

**Comment by rugk** [comment]
okay, so…

That said, let us know when you (or someone else) knows a way to detect a bot/these bots, and we can add it. It's theoretically not limited to UAs, we could add additional logic.

**Comment by rugk** [comment]
As an additional note from the future:
> User agents aren't always fixed, and could easily be circumvented

That is obvious and also is not the aim here. Our bot detection **is not a security feature**. It's merely a c

It may depending on your thread-model, but usually, of course, security-wise, you never want to have such a thing as unauthorized software accessing your paste anyway, because that means there is basically an (active) "man-in-the-middle" (MITM) attack. So the security issue happens already when you share the link via some insecure or publicly accessible medium respectively via some medium, where it can be accessed by bots or so.
We also [repeatedly address](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#if-i-use-privatebin-and-post-the-link-in-a-forum-in-social-media-etc-is-my-content-secure) that [in our FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#the-url-is-so-long-cant-i-just-use-an-url-shortener). Please refer to these for more information.
