### ISSUE TITLE
the motto "Ignorance is bliss" can't be translated litterally (in French at least)

### ISSUE THREAD

**Issue by Murazaki** [PrivateBin/PrivateBin#540]
## Steps to reproduce
1. Open PrivateBin in another language (Fr)
2. Read the motto

### What happens

It's traduced litterally, and doesn't mean much
In French it gives : "Parce que l'ignorance c'est le bonheur", which means something like "Because being ignorant is happiness" which sounds more like Dumb and Dumber motto than a security oriented product one.

### What should happen

use a localized expression, for instance : "Vivons heureux, vivons cachés" which means quite litterally this time "live happy, live hidden"

**Comment by Hexalyse** [comment]
Why not just keep the original motto, "Because ignorance is bliss" ? 

Most of French people have a basic level on English, and would understand it. If they don't, it doesn't change a lot of the experience of using PrivateBin (and people are used to seeing short English sentences linked to products and services they use everyday, it "sounds cool" to the public).

And it would avoid weird literal translations that doesn't convey the same idea as the original sentence, or using other mottos like "Vivons heureux, vivons cachés", that IMO, don't convey the same idea either.

**Comment by elrido** [comment]
FYI: Seems like this has now gotten addressed by a translator using Crowdin and will get merged when abaa9eca355cdfd8d24c177b5dc196e681acf1a1 goes in.
