### ISSUE TITLE
PrivateBin requires a modern browser to work (Only in Chrome, not Firefox)

### ISSUE THREAD

**Issue by crunchprank** [PrivateBin/PrivateBin#572]
## Steps to reproduce

1. Install CentOS Linux release 7.7
2. Install Apache/2.4.6
3. Install PHP 7.3.14
4. Install libsodium 2.0.22
5. Install the latest PrivateBin from GitHub (ed590ee)
6. Don't use SSL 

### What happens

The web application works properly in Firefox 72.0.1 (64-bit) on Ubuntu.

The web application shows the following error when using Chrome Version 79.0.3945.117 (Official Build) (64-bit) on Ubuntu and Fedora.

    PrivateBin requires a modern browser to work. Firefox, Opera, Chrome...

And there is no text box to paste content in.

### What should happen

No error should be present.

## Additional information

I cannot reproduce this issue on <https://privatebin.net>

This was supposedly already addressed in #446 via 67b9b5f.

```
# php -i "(command-line 'phpinfo()')" | grep -i sodium
sodium
sodium support => enabled
sodium compiled version => 2.0.22
libsodium headers version => 1.0.18
libsodium library version => 1.0.18
```

**Comment by r4sas** [comment]
That happens because usage without SSL is now prohibited due to switching to webcrypto. But why it returns message about modern browser - seems like bug.

**Comment by elrido** [comment]
When used without HTTPS, Chrome just disables the Webcrypto API. Hence the legacy browser detection shows the "modern browser" message. We chose not to do browser detection, but use feature detection instead.

**Comment by elrido** [comment]
duplicates #446, got discussed and changed to the current warning in #508

**Comment by crunchprank** [comment]
I had opted to not utilize SSL as this is hosted in an internal, closed off network - but it looks like just doing a self signed certificate will address the issue. I appreciate the responses.

**Comment by rugk** [comment]
See https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-it-show-me-an-error-about-an-insecure-connection

BTW, @elrido, is the error message quoted in the FAQ still the correct one? Or maybe we should just add another FAQ for the other error message here ("PrivateBin requires a modern browser to work."), as that issue comes up quite frequently.

**Comment by elrido** [comment]
The FAQ scenario for no-https is different from this one. There isn't an FAQ for the modern browser one, but it should be self-explanatory, except for the no-https + Chrome case (which I see that someone did document on that no-https-FAQ entry).

**Comment by rugk** [comment]
Yeah well, so what do you suggest now?

I would very well write a new FAQ and reference the old one - just to explain _that one_ case, we have here.

**Comment by rugk** [comment]
Also duplicate of https://github.com/PrivateBin/PrivateBin/issues/567, https://github.com/PrivateBin/PrivateBin/issues/441, https://github.com/PrivateBin/PrivateBin/issues/441, https://github.com/PrivateBin/PrivateBin/issues/454, https://github.com/PrivateBin/PrivateBin/issues/537

So we definitively need a FAQ, I am writing one.

**Comment by rugk** [comment]
BTW no the FAQ was explicitly written for this error case, see https://github.com/PrivateBin/PrivateBin/issues/441#issuecomment-504656735, where I announced that I wrote it.

The error message was just different/an additional one.

**Comment by elrido** [comment]
I think the FAQ entry that you linked to already documents the problem, don't you?

Edit: A, ok, so you did write it. So all fine then?

**Comment by rugk** [comment]
Yeah I documented it in a better way now again...

No wait, we have to diffeenciate:
* WebCrypto disabled - in the case of Chrome+HTTP e.g. -> this results in that PrivateBin can neither decrypt nor encrypt pastes, i.e. does not work at all
* WebAssembly for compression - this is the case for Tor and should makes pastes unreadable in Tor, since https://github.com/PrivateBin/PrivateBin/pull/508 one should be able to _create_ _uncompressed_ pastes though (and _read_ uncompressed ones?)

So the "no HTTPS" error should _always_ be shown, if HTTP or so is used, independent of whether it breaks any funcationality.
The "requires modern browser" should only do so when a feature we need is not there, i.e. the _whole_ feature detection fails.

**Comment by rugk** [comment]
And let's not forget Edge that also does show this error, because of missing WebCrypto that is not implemented.

https://github.com/PrivateBin/PrivateBin/issues/563, https://github.com/PrivateBin/PrivateBin/issues/528, https://github.com/PrivateBin/PrivateBin/issues/515, https://github.com/PrivateBin/PrivateBin/issues/546, https://github.com/PrivateBin/PrivateBin/issues/468

And I currently tested it and the error handling is broken. I'll create a new issue...

**Comment by rugk** [comment]
done: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-it-show-me-the-error-privatebin-requires-a-modern-browser-to-work

**Comment by elrido** [comment]
Did reword the first paragraph. It also tests for async and await and ES6 support in the feature detection.

**Comment by rugk** [comment]
Okay, did change some minor things too, also adjusted the first bullet point to match the paragraphs.

**Comment by rugk** [comment]
Question: Just like with the [loading message](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-not-the-loading-message-go-away), we could also link the error directly to our FAQ entry. Do you think this makes sense?

**Comment by elrido** [comment]
Yes, why not - safes us from having to answer the questions and users don't have to spend time to wondering what's going on, writing issues, etc.

**Comment by rugk** [comment]
Okay, created new issue: https://github.com/PrivateBin/PrivateBin/issues/577
