### ISSUE TITLE
How to upgrade for Yunohost ?

### ISSUE THREAD

**Issue by webafrancois** [PrivateBin/PrivateBin#602]
I'd like to try to update the Privatebin Yunohost version from 1.1.1 to 1.3.4

Is there some technical insctructions to help us to do that ?
I see the install instructions, but no to upgrade.

Or changes are minors, so we just compare the diff to see it ?

Thanks a lot.

**Comment by qol3m** [comment]
Yunohost seems to be a control panel for self-hosting a couple of useful scripts/CMS's.

So ideally they will update PrivateBin for all their users, because only 1.3.4 is supported. You could ask here https://yunohost.org/#/help

I have only installed PrivateBin manually, but it was as simple as copying the files, so upgrading to a newer version might be just as easy. You could make a backup of the folder and try it.

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
