### ISSUE TITLE
add download link for paste

### ISSUE THREAD

**Issue by qol3m** [PrivateBin/PrivateBin#604]
I think a download link for the paste would be very useful for larger pastes.

pastebin . com also has a "print" button, which I would never need in my life, but perhaps someone else might find it useful.

**Comment by rugk** [comment]
You can use the raw text -> ctrl+a and copy all the text, could not you?

What is your exact use case?

Also printing a document is a very different use case than saving it as a file.

**Comment by qol3m** [comment]
I guess I could do that. Perhaps sometimes it is necessary to adjust it anyway (e.g. add a <html> or <?php ).

It's just that I like downloading most of the pastes that are shared with me. They expire, but I keep them on my hard drive for later use, not actually knowing whether I will need them later. Saving them manually would be abit tedious.

The more I think about the printing, the less I think anyone would ever use it. It was just an idea that I saw on pastebin . com

If downloading a paste gets implemented, it may be useful to have the description/title (which I think I saw is also a feature request) as the file name.

**Comment by rugk** [comment]
> It's just that I like downloading most of the pastes that are shared with me. They expire, but I keep them on my hard drive for later use, not actually knowing whether I will need them later. 

Well… this is not actually the use-case that we intend for PrivateBin. The sender has some reason to send them to you in a kind of _ephemeral way_ and wants it be deleted.
Of course, we cannot technically prevent you from saving the content (that's why we also don't try to block right-click etc. – you have to trust the receiver), but we also should not encourage saving the data either via such a button, especially if there is no good use case behind that feature.

As such, I'd tend to decline this feature request.
