### ISSUE TITLE
Open links in new tab

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#61]
What about automatically adding `target="_blank"` to links in PrivateBins so they are opened in a new tab?

**Comment by elrido** [comment]
Personally I like the idea, especially because after clicking on a link in a burn after reading paste the back button will not work as expected (it will return you to the message "this paste does not exist or was deleted).

But... I have encountered strong opposition against using `target="blank"` because different users have different workflows and some folks are really annoyed if a website forces them to use their browser in a certain way.

If we would consider it, we should watch out for this issue:
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

TL;DR: Also add a `rel="noopener noreferrer"`.

**Comment by rugk** [comment]
Starting with Firefox 52 `noreferrer` [is not necessary anymore](https://bugzilla.mozilla.org/show_bug.cgi?id=1222516). ([German source](https://www.soeren-hentzschel.at/firefox/firefox-52-erhaelt-unterstuetzung-fuer-relnoopener/)) However `noreferrer` also won't hurt as we do not allow referrers anyway.

I've know these arguments against `target="_blank"`, but in our case there seems to be a legitimate reason to use it (as you said). This is quite similar to when [media is playing](https://css-tricks.com/use-target_blank/#article-header-id-7), you might not really want to interrupt this.

**Comment by elrido** [comment]
Resolved in #630

**Comment by rugk** [comment]
FYI: [Firefox 79 now also implies `rel=noopener`](https://hacks.mozilla.org/2020/07/firefox-79/), i.e. one does not have to set it manually now.
(Just a note for the future, of course, for now, we keep it – for older Firefox versions and other browsers.)
