### ISSUE TITLE
Chrome 83.0.4103. download issue

### ISSUE THREAD

**Issue by vmazyliukTW** [PrivateBin/PrivateBin#634]
## Steps to reproduce
1. Update chrome
2. Try to download attached file from privatebin

### What happens
You will receive such error:

_Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details._

### What should happen
Download should work.

## Additional information
I have found such tread in google bug tracker:
https://issuetracker.google.com/issues/157368720

So there is no workaround right now. 

## Basic information

**Server address**: -
**Server OS:** Ubuntu 18.04
**Webserver:** nginx
**Browser:** Chrome 83.0.4103+
**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: No (Because it doesn't support file upload)

**Comment by elrido** [comment]
Thank you for the additional research.

**Comment by candrews** [comment]
I reported this issue to Chrome at https://bugs.chromium.org/p/chromium/issues/detail?id=1106906 `Content Security Policy standard does not define "allow-downloads" for the sandbox directive`

**Comment by rugk** [comment]
As they say there and as we also said, it is actually defined, so it's not a bug as far as I see/IMHO. I'll guess the Chromeium devs will close the issue, too…

**Comment by elrido** [comment]
Well, it does have a bit of weird taste: The Chrome developer in question introduced this new standard into the WHATWG draft and immediately implement it, leaving the other browser no choice in either implementing it as well, before the standard is discussed and agreed upon or not support a feature to protect users from drive-by-downloads. This is very reminiscent of Microsofts behaviour of forcing new "standards" into existence and having the only browser that allows to benefit from it, during the browser wars in the 90ies.

In this one case, I do see a benefit of this feature and assume it is well intended - it would just have been more polite to wait till the flag would have been agreed upon in the standard committee instead of just unilaterally implementing it, running the risk that if WHATWG changes the flags name and we all end up having to change it twice or adding two flags instead of one, to support all browser versions. Let's see.
