### ISSUE TITLE
safe or not

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#660]
By demo : In PrivateBin, Data is encrypted/decrypted in the browser using 256 bits AES. Encrypt/decrypt in the browser is not safe.

https://forum.duniter.org/t/privatebin-pour-la-monnaie-libre/7416/9

**Comment by elrido** [comment]
This very much depends on the use case and what you consider to be safe. In short, if your life depends on state actors finding out that you shared a certain message via PrivateBin and what it contains, then no, this is not the tool for you. But if you use your own instance or one that is hosted by someone that you trust, then you might consider using this tool for sharing content with the public. If the content is not intended for everyone, do use a password that is only known to the recipient(s).

The main use case is that _everyone getting the link_ can read the link _as if it was unencrypted_. The point of the encryption is not to hide the message from third parties, as you typically want to share your paste with the whole world. **The encryption is intended to protect the server from having to moderate the content actively.** In many countries it is now prohibitively risky to run a public forum or a comment section on a blog, as this requires you to actively moderate every message, in some cases even before publishing it, or you can be held accountable for the content published there. PrivateBin addresses this, by giving the person running the service the possibility to argue that they couldn't have known the contents, until they got reported to them by a third party.

The technical answer is, that for many users HTTPS is safe enough to do e-Banking, even though it doesn't encrypt the communication end-to-end - you have to trust that the server of your bank doesn't act maliciously or was broken into and that your browser uses safe crypto (say, not from an outdated library, because you didn't update your OS for a few months) and wasn't been infected by some malware. Similarly, PrivateBin uses the browsers Web Crypto API to do it's encryption and so is dependent on the browsers security and the servers.

In addition, as you already pointed out in another issue, you also have to trust the server not to send you some malicious javascript. This is indeed a fundamental issue that is out of the scope of this project (see [point 4.1 in our report on measures taken after the 2014 audit](https://privatebin.info/reports/zerobin-audit.html)).

Your best protection from this is to run your own instance. Your second best is to use an instance run by someone or some entity that you trust. But in the end, you would ideally use a local client that doesn't rely on code sent to you by the server. This is what the third party command line clients already do offer.

Maybe, in the future, we might add a feature to use one PrivateBin instance to store pastes on another one. You might spin up the first instance locally via docker or such and use it to store pastes on another instance on the internet, not having to trust code sent by that server, as you would only use it's API.

**Comment by rugk** [comment]
No need to explain this again and again, @elrido. We do have a FAQ for this.

This should answer the question:
https://github.com/PrivateBin/PrivateBin/wiki/FAQ#but-javascript-encryption-is-not-secure

(Anyone feel free to expand this with the information above though.)

So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
