### ISSUE TITLE
Asking for a php-fpm only Docker image

### ISSUE THREAD

**Issue by purerosefallen** [PrivateBin/PrivateBin#706]
In some cases we may have our own Nginx container running a bunch of other services, while we need only a php-fpm image for PrivateBin, for better performance. Could you take a little time to consider this? thanks.

**Comment by elrido** [comment]
The webserver you use needs to serve static files as well. For a php-fpm only image to work with a webserver in another container (or outside the container), you would need to share both a volume containing the static files (css, js, i18n, etc.) with the webserver process and also either switch the php-fpm process to use a network socket instead of a unix socket (which will make requests slightly slower) and expose that port or share the unix socket with the webserver in a read/write volume. To avoid having such a fragile setup, it seemed more secure, robust and easie to use a webserver inside the one container, so it is limited to only read and write to what is inside that image.

Could you describe what benefit you expect from having a php-fpm only docker image?

**Comment by purerosefallen** [comment]
Many benefits. I may use `set_real_ip_from` in my own webserver and track the users' IP address. Also, I may also heavily customize my own webserver for better performance.
In addition, many DockerHub application images, such as phpMyAdmin, WordPress, has php-fpm only images. It could also be another choice for users with those needs.
For the issue of security, I don't think it could be a problem, as php-fpm port would be exposed only in Docker network instead of in the whole network.

**Comment by elrido** [comment]
So the intent with the current image is that you do run it behind your hardened external facing webserver that provides TLS termination and does the log collection with the "real" IPs on one central place. In a k8s environment that would probably be a load balancer. So the tracking of user IPs is already possible and external to the image and offering a php-fpm only doesn't make this easier.

That said, if we do get a merge request with a second Dockerfile for such a stripped down second image, I'll see to it that it is produced in the github action, along side the regular one.

**Comment by elrido** [comment]
I think this question has been answered and I am closing the issue. Please feel free to reply if you have follow-up questions or create a separate issue for different topics.
