### ISSUE TITLE
Sentence isn't in i18n

### ISSUE THREAD

**Issue by Cellophile** [PrivateBin/PrivateBin#715]
Hello,
I'm new here, and I don't know how help by resolving directly a problem. So I share you something to correct on the 1.3.4 version : 

The sentence "URL shortener may expose your decrypt key in URL." isn't present in any file of i18n folder. 

I correct it localy for me, but the problem persists here.
In french, we could traduct this sentence by "Raccourcir l'URL peut exposer votre clé de déchiffrement dans l'URL".

I take advantage of being here to question about this sentence : URL shortener may expose your... But expose to what ? I see two things : 
- loose decrypt key if the short URL doesn't work anymore ;
- Save the original URL in the acount of the used Shortener (bitly, ....), where the account owner can see all original URLs. And if those URLs aren't protected by password, this person has access to them.

But which exposition were you talking about ? Maybe it's useful to speficy it in the sentence ?

Personnally, I say that : "Raccourcir l'Url cache la clé de déchiffrement (ça c'est bien) mais peut compromettre la lecture ou la confidentialité du message (ça c'est bof). Nous vous conseillons de mettre un mot de passe à votre message, et de conserver l'URL d'origine, au cas où l'URL raccourcie viendrait à ne plus fonctionner (valable surtout pour les messages avec une durée de vie très longue)."

"URL shortener hide th decrypt key (that is good) but may also compromise reading or confidentiality of the paste (that's blah). We advise you to put a password to your past, and to keep securely the original URL, in case of malfunction of the shortened URL (especially valid for messages with a very long lifespan)."

It's only a proposition ! :)

**Comment by rugk** [comment]
Thanks for your report.
First of all, translation questions should be asked on POEditor AFAIK.
However, if the code misses a translation, that is of course a code problem.

Feel free to send PRs to fix that problem.

**Comment by elrido** [comment]
Sorry for the very late reply. The problem with URL shorteners is that you always expose the decryption key to these services, if you use them. At that point your message is no longer private. If you intend to share your link publicly, this does not matter to you, but if you intend to share it with a limited number of people, it would be counterproductive.

Furthermore, if you host both the privatebin instance and the url shortener, then you gain knowledge about your users decryption keys, so you can't really claim to have zero knowledge about the pastes contents if the authorities come knocking at your door (if that is why you use privatebin over other pastebin services).

You are right that it would be better if one uses a password when using a URL shortener, so that the decryption key alone is not enough to decrypt the pastes.

We could consider to enable the URL shortener function only if the paste was created using a password and always disable it for burn-after-reading pastes.

On the other hand, I assume that people that do use URL shorteners either intentionally want to track by whom and when the paste gets viewed (for statistics, for example in social media posts, newsletters or other "broadcast" media) or just dislike the long URLs with non-human-readable strings at the end. In either case they just want to use privatebin like a generic pastebin and seem less interested in it's privacy protection and security features. :-/ Or I may simply not fully understand the use case for URL shorteners.
