### ISSUE TITLE
Setup default password or restrict the temporary URL to a single IP

### ISSUE THREAD

**Issue by pitogas** [PrivateBin/PrivateBin#718]
Is there any way to setup a default password, which is pre-defined in PrivateBin configuration when user submits the paste?
Otherwise is it possible to restrict the access to URL that is generated to a single IP?

Basically we want to use the PrivateBin to share passwords internally in the company, and also allow users to send us the passwords, or sensitive information securely.

So there is two possible options:
1- Setup a default password which is set by us, the usersubmits the data without forcing any password, and only we're able to open the link with our password;
2- Setup webserver (Nginx in this case) to restrict the access to the temporary links generated by users ("GET /?pasteid=xpto123xpto123xpto123 HTTP/2.0") only from the IP of our company;

Thanks!

**Comment by elrido** [comment]
1. Not currently a configuration option (I wouldn't think it makes sense, UI wise, as it is IMO an anti-pattern to provide a "commonly known" default password. Now, you could try changing the template you use to have a value-attribute filled in with that password - note that this will be visible to any visitor in the source view, but I guess that's why you ask for point 2. If that doesn't work, you'd have to resort to finding and setting it in the JS logic. Location of the password input in the bootstrap template:
https://github.com/PrivateBin/PrivateBin/blob/c7bff204f90b729c250796516b0393060959b6dc/tpl/bootstrap.php#L358
2. Absolutely, but that is more of an [nginx question and not specific to this tool](https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-tcp/).

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
