### ISSUE TITLE
Directory in the Wiki keeps getting vandalized

### ISSUE THREAD

**Issue by TheAssassin** [PrivateBin/PrivateBin#737]
Not sure whether you're aware of this (haven't found any other issues related to this), but there's some folks who keep vandalizing your Wiki, and especially the [Directory](https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Directory):

![screenshot_2021-01-15_03-47-18](https://user-images.githubusercontent.com/4503202/104674717-66133880-56e4-11eb-86b9-eb7ca723bf4f.png)

The last good revision: https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Directory/0418849fb6f512f0e0a134879179ecf66d91d4c8

It's a shame that this is happening more and more on GitHub, requiring people to restrict write access to members. I would suggest you do the same. The directory is a very important page, and should be available.

If you do not want to do so, consider moving the directory to another location, e.g., your website.

**Comment by rugk** [comment]
Thanks for the report.

It's really sad to see people doing this.
However, the linked wiki is an outdated site anyway. The up-to-date wiki is in https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Instances-Directory, i.e. a new name.
Maybe people get to the old wiki from old links pointing there etc.

Anyway, I've disabled editing the wiki for now and we'll discuss the following plan…

**Comment by rugk** [comment]
Also note a new directory service is in development, however. See https://github.com/PrivateBin/Directory :smiley: 
So yeah, the replacement may come soon.

**Comment by elrido** [comment]
Looking through the [history of the renamed page](https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Instances-Directory/_history) (see @rugk post above), I couldn't spot any obvious vandalism. Is the old page still linked somewhere?

Should we get such defacing activity, the simplest is to report and/or ban accounts from the project or organization to mute them. According to our org's moderation settings, we so far only had to ban one account.

On the subject of the self-updating directory, it got [published end of March](https://github.com/PrivateBin/privatebin.info-pelican/commit/2fb30990ad1c95e9e185907cc770de56341a10e6) last year and is linked on the info page of the project as well: https://privatebin.info/directory/ - I haven't suggested removing the wiki page so far, but did link the new tool on there. While the new service includes the popular SSL ratings and updates them daily, it doesn't offer a free form comment like the wiki, only data that can be collected in an automated fashion from the given URLs, so that manual intervention should rarely be necessary.

**Comment by TheAssassin** [comment]
This create-delete-create-delete looks quite like the typical pattern. If you move/rename stuff, I'd suggest to always add a link to the new page. It makes no sense that there's the page with just a dot.

Anyway, I consider this resolved then. I think a link to that page will solve all the issues, and end this pattern. The wiki page is what people know and are used to, so adding a link will do the business.

I like the new page on your homepage by the way.

**Comment by rugk** [comment]
> If you move/rename stuff, I'd suggest to always add a link to the new page. It makes no sense that there's the page with just a dot.

Well… we've removed it. The downside of the link is that this will appear in GitHub's sidebar as a new Wiki page. Anyway, given we have a lot of pages anyway and the search feature needs to be used. And apparently many old links point to that wiki page, I've added a link.

Also, I've made the Wiki editable again. Let's hope people behave.
Again thanks for the notice and help! :blush:

**Comment by rugk** [comment]
Also given that the Directory was hardly findable (IMHO – you also did not seem to find that new one), I've opened another issue for making it more visible: https://github.com/PrivateBin/privatebin.info-pelican/issues/21

**Comment by TheAssassin** [comment]
@rugk I consider it best practice to set up some redirection (or to leave a link at least) when you're moving stuff around. That's all I wanted to say. For Dokuwiki, for instance, I use https://www.dokuwiki.org/plugin:pageredirect in a few instances to make sure old links still work. For Sphinx, I use https://pypi.org/project/sphinxext-rediraffe/.

To be able to share links more safely, I started to use [redirector](https://github.com/TheAssassin/redirector). Adding a level of abstraction allows for changing the targets afterwards, while keeping the links static. (I wrote my own since all the ones I found didn't work as well). You can see it in action [here](https://go.blue-nebula.org/). Perhaps you want to set up something like that, too?

**Comment by TheAssassin** [comment]
By the way, given that you have this custom sidebar, it's no surprise people don't discover other pages any more:

![screenshot_2021-01-17_20-28-13](https://user-images.githubusercontent.com/4503202/104853665-9801e600-5902-11eb-8819-5a9b5d95a2b9.png)

You should consider adding your page there, too.

**Comment by rugk** [comment]
I am not aware of any method that actually works in GitHub's Wiki's. It's obviously not Dokuwiki or so, it's just Markdown. If you find one, feel free to add it to that page (maybe some weird hack with some HTML tags works, but otherwise there is not a lot you can do in Markdown).

As for the sidebar, I personally agree with you. We should maybe make it a proper index…

**Comment by TheAssassin** [comment]
Yeah, GitHub's "wiki" is very very limited. I don't really like it that much. That's why I suggested to insert links.
