### ISSUE TITLE
How to modify English strings without triggering CSP fail?

### ISSUE THREAD

**Issue by xxxmicrobexxx** [PrivateBin/PrivateBin#802]
## Steps to reproduce

1. Modify /js/privatebin.js and change an English language string e.g. "Your paste is" to something a little more meaningful for people who are using the service but don't understand the jargon.
2.

### What happens
Edit is successful (obviously) but then pastebin "loading..." message does not go away and there is a link to https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-the-loading-message-not-go-away which gives a hint to problem "the CSP header (a security feature deployed by PrivateBin) prevented the JS files to load as they seemed to be modified".

### What should happen

I should be able to modify strings.  Perhaps the English language should be split off to an editable language file like other languages.

**Comment by r4sas** [comment]
You already got link with information: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-the-loading-message-not-go-away.

But in your case, you must make changes in `i18n/en.json`:
https://github.com/PrivateBin/PrivateBin/blob/93138cbbae6d1ada37f3dcb5cba6a4b77a71d0f4/i18n/en.json#L129

**Comment by elrido** [comment]
One slight correction: The en.js had to be added for the Crowdin service as a baseline for new translations. It isn't used by PrivateBins translation libraries.

**Comment by r4sas** [comment]
Maybe we must add english translation to library too, to make possible override default values?

**Comment by rugk** [comment]
> https://gist.github.com/rugk/71cadef3b8a8f18909c4f3f4e649121e

IMHO a good idea.

**Comment by r4sas** [comment]
> IMHO a good idea.

huh?

**Comment by rugk** [comment]
Uups lol, accidentially pasted the wrong stuff…

I meant:
> Maybe we must add english translation to library too, to make possible override default values?

IMHO a good idea.

**Comment by xxxmicrobexxx** [comment]
Yes, that is what I was suggesting "Perhaps the English language should be split off to an editable language file like other languages."

Without that, English phrases can't be edited, correct?

**Comment by elrido** [comment]
Ugh, I really don't get why everyone wants to duplicate the English IDs. Reasons that IMO speak against doing so:
1. The main benefit of replicating the [GNU gettext approach](https://www.gnu.org/software/gettext/manual/gettext.html#Why) of message IDs being the English phrase is that the developer writing the source code always must already understand and write English (even if non-natively, as in my case) and it therefore is easy for them to understand the context of the message as well as understand the code without comments when reading it later on: "here we check for some error, oh and it says in the message 'can't decrypt your paste'" - it's just much easier to maintain that way
2. So, if we use the message IDs as full sentences for reasons outlined in 1., handling a en.json introduces duplication and inefficient code, if we have to still look up the "translation" of the phrase into the same phrase. Especially since in all published releases, it won't contain any differences to the message ID, it only allows for changing the English phrase without changing the message ID in all translations.
3. I don't understand the use case for having a local translation of English that is _different_ from the message ID in the source code.
  1. If you want to change the messages displayed on the template, do that in a custom template.
  2. If you there is an error or an improvement to be done in the English message ID, then please do let us know and we can get that fixed in all the places that message ID is used.
  3. If you would like to propose a different message to be used, again, I'd like to fix this in the project - it will be different in that a new message ID should be added to all translations, the old one removed, so that we don't provide mistranslated messages.

@xxxmicrobexxx - if you would like to fix an English translation, please do let us know and I am happy to apply it for you into all the relevant places, including updating the SRI hashes, if needed.

> Without that, English phrases can't be edited, correct?

Yes, they can be edited: Change the message ID in the source code and all the i18n/??.json files (using sed or such). If you had to change the js/privatebin.js file, you need to either regenerate the SRI hash of it or remove the SRI hash from your template. See this [FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-i-have-changed-some-javascript-files) on that subject.

**Comment by xxxmicrobexxx** [comment]
@elrido the reason I suggested to duplicate the English IDs is because the method of editing phrases is not intuitive and the fact that it is possible for users to regenerate the SRI hash themselves is obscure, to say the least.

Thanks for describing what was needed.

**Comment by rugk** [comment]
For everyone following here, yo0u may want to look at https://github.com/PrivateBin/PrivateBin/issues/514
