### ISSUE TITLE
Allow unencrypted short links built in so PrivateBin can be used like Pastebin (Enhancement)

### ISSUE THREAD

**Issue by Lewis8379** [PrivateBin/PrivateBin#856]
While this script is brilliant overall, it could also double as a Pastebin alternative. 

There is a Pastebin script called Paste, but is is based off of the original paste and hasn't been updated since 2018, so lacks many basic features, including the paste ID that it outputs being an incremental number starting at 1. Google also brings up a PasteShr script on Codecanyon that looked decent, but sadly is no longer available. I cannot find any other PHP pastebin style scripts.

Yet PrivateBin basically is a Pastebin alternative. I am aware that Pastes can be used with an external URL shortener, but that still isn't ideal.

I feel PrivateBin would work really well with an additional setting when creating a paste to NOT encrypt it, or at least to use a shorter URL, which I know would provide reduced/no security, but that wouldn't be the point in this feature. All of the other settings would still be there, but checking this new box would simply save the paste (which could still be encrypted service side?) using a randomly generated 5 character URL, so instead of:

https://privatebin.net/?d685c4fcac1a4058#7LWheB2bDxRcaT1hd7ApHDoiRZkrcQocoZ25xVqgL39l

You would get

https://privatebin.net/?d685c

This would then be a viable pastebin alternative combined with the legendary privacy based one it is now.

**Comment by elrido** [comment]
I don't think such a feature makes sense for privatebin, since it counteracts the goals of our two main user groups:
- users creating pastes on privatebin use it over other pastebin services, because it let's them encrypt the paste contents from being visible to the server operator - offering an option to turn this off, would:
  - a) put them at risk of accidentally storing a paste unencrypted
  - b) void the unique selling point of this software
- server operators choose privatebin because it ensures they don't have knowledge of the pastes contents, until the link with credential in the hash is revealed to them. In some jurisdiction that let's them offer the service without being at risk of being accused of knowingly hosting malicious content or being expected to review every paste before it is published
  - again, to these users including such an option would void the unique selling point of this software

**Comment by Lewis8379** [comment]
While I understand what you're saying, you could cater for those two user groups while enabling the additional one from my suggestion by implementing options. In the first case, I disagree that offering the user an option to have their paste unencrypted and with an easy link would impact the service, as long as the default option is to have the security enabled. As for server operators, there would simply be another setting alongside the others that would enable my suggestion, with it defaulting to disabled. Enabling the setting later would not impact the existing encrypted pastes.

**Comment by rugk** [comment]
I also disagree that introducing an option to disable *the* essential security feature of this software is a good idea.
Even if, this is very very dangerous and basically a "totally insecure" button. It is hard to communicate the impact of doing this, ux wise. See how browsers handle and hide dangerous things like this.

So ux wise and implementation-wise this is not really easy.

Also note that you can never, without a lot of implementation work, use it "like pastebin", because e.g. the paste content is loaded only after PrivateBin via another request, so e.g. cURL requests don't work.

Also, what is the use case for this actually? Just convenience?
I.e. **why** do you want it to work like PasteBin?

You already have a way with the URL shorter to have an easy way to simplify links. Note this is already an optional security compromise we are making.

I am very reluctant to weaken the security for just some convenience, even if it is optional.

**Comment by rugk** [comment]
and sidenote: server-side emcryption is a pointless concept that does not really provide much security in out case, because the key must be saved on the server.

**Comment by elrido** [comment]
I think we have documented why such a change would not be a good fit for this project and therefore consider this request to be resolved.
