### ISSUE TITLE
dnssec record contains errors, resulting in host not found on some dns servers.

### ISSUE THREAD

**Issue by hboetes** [PrivateBin/PrivateBin#860]
Yesterday I pasted something and the recipient said the site was down, my cogwheels started turning, and I checked the DNSSEC records, and lo and behold:
 
https://dnssec-analyzer.verisignlabs.com/privatebin.net
https://dnsviz.net/d/privatebin.net/dnssec/

**Comment by elrido** [comment]
Could you explain the issue you are having with your instance a bit more in detail? Do you have issues reaching your instance of PrivateBin? The links you provide seem to relate to our demo instance, not your own one.

Is our software somehow not compatible with your sites DNSSEC setup? AFAIK the DNS setup should not affect this project, but maybe if you could provide us the errors the user is getting from the browsers console or such to better understand how it does?

**Comment by hboetes** [comment]
- Some dns-servers refuse forwarding dns-entries, if the dnssec record is not in order.
- The dnssec records for pastebin.net are not in order.

**Comment by elrido** [comment]
pastebin.net is none of our domains, please get in touch with it's domain holder.

privatebin.net's DNS servers are not set up for DNSSEC, nor publish DNSSEC records, since the management software in use for it's DNS server doesn't support the required new record types and there have been no plans (or time) to add that to it. For now, I'd recommend to use a different instance or host the software yourself, if you need it to work with that particular DNS setup.

**Comment by elrido** [comment]
I think the question has been answered and the issue can be closed.

**Comment by hboetes** [comment]
Ah, thanks for the heads-up. This isn't intuitive, of course.

**Comment by hboetes** [comment]
And... all your base are belong to us!
