### ISSUE TITLE
Change "Send" button label by "Save" to have better user understanding

### ISSUE THREAD

**Issue by felag** [PrivateBin/PrivateBin#946]
First things first: Thanks for this piece of software !

Using it, we have a lot of users that are misunderstanding "Send" button: they believe that this button directly sends created URL to our IT support crew.

I think that a minor change can avoid this misunderstanding: changing "Send" button label to "Save".

**Comment by r4sas** [comment]
I prefer usage of "Send" in context "Send text/data for paste"

**Comment by rugk** [comment]
Hmm, I don't really like "Save" either as it is unclear where the data is saved (local draft?, browser?). It should be clear its send to the server, even though its e2e encrypted.

However I get that users may be confused by "Send" as there its also unclear where its send to, as you have (both actually) explained, that could be inyerepreyed differently.

Now, the string shpipd stay short of course though.

So what about "Create"? It's the create paste page and it creates a paste when you click that button. Is not that the best?

If we wanted to be extra sure maybe " Create paste", bit really, what else is supposed to be created here? (Animals, a mail out of nowhere?, …).
So all in all I would be fine with changing it to "Create".

**Comment by elrido** [comment]
The OG Pastebin calls the button "Create". It's called "Send" presumably because we send a message to the server, but as got explained, that may not be clear to a not-so-technical user of where it gets sent.

I don't mind changing it, so here is a poll (first time I try this service, hope it works - note that clicking these stores your IP):

[![](https://api.gh-polls.com/poll/01G6PWRG1F97Y2RVDVWDF3DJDB/Send)](https://api.gh-polls.com/poll/01G6PWRG1F97Y2RVDVWDF3DJDB/Send/vote)
[![](https://api.gh-polls.com/poll/01G6PWRG1F97Y2RVDVWDF3DJDB/Save)](https://api.gh-polls.com/poll/01G6PWRG1F97Y2RVDVWDF3DJDB/Save/vote)
[![](https://api.gh-polls.com/poll/01G6PWRG1F97Y2RVDVWDF3DJDB/Create)](https://api.gh-polls.com/poll/01G6PWRG1F97Y2RVDVWDF3DJDB/Create/vote)

Technical details: If we do end up changing this, then we need to change the ID as well as message in the json and of course the bit of code that displays this in both templates.
https://github.com/PrivateBin/PrivateBin/blob/9b132f405498e909c49ce10e0a85c21fc572e04c/tpl/bootstrap.php#L202
https://github.com/PrivateBin/PrivateBin/blob/9b132f405498e909c49ce10e0a85c21fc572e04c/tpl/page.php#L128

**Comment by EDIflyer** [comment]
Poll now closed but my vote would have been for `Create` if that helps with the tiebreak 😂

**Comment by lolcabanon** [comment]
Hey! I was looking for an already raised issue because the "Send" button ("Envoyer" in french) is causing a lot of confusion to our users too...


I see you rejected "Save" and I kinda agree on that, but may I suggest using "Generate" instead? On fact, the action of the button (at least to the end user) does *generate* the link they have then to send us.

What do you think about it?

**Comment by r4sas** [comment]
No, I think `generate` is the worst idea, because it can be interpreted as "generating of the content", not only link.

**Comment by lolcabanon** [comment]
To me "Send" feels like the worst, since you need to send the link somewhere for the tool to make sense! 

I guess Privatebin is not oriented to non-technical users? 😂

Anyway, thanks for your answer! ✌️😎

**Comment by EDIflyer** [comment]
It look likes a change to 'Create' (which I think sounds like a sensible choice) has already been made and is just awaiting the next release cycle?

**Comment by lolcabanon** [comment]
> It look likes a change to 'Create' (which I think sounds like a sensible choice) has already been made and is just awaiting the next release cycle?

Ahh yeah I just saw that!

Imo anything but "Send" lol so "Create" is perfect!

**Comment by rugk** [comment]
Yep, see https://github.com/PrivateBin/PrivateBin/pull/1245. Next release will name the button Create.

Note that translations may (still) need updates, though. See https://github.com/PrivateBin/PrivateBin/wiki/Translation for how to contribute to translations. We use Crowdin for that.
