### ISSUE TITLE
Drop own plural rules and use browser feature for i18n

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#963]
There seems to be a new API for getting the plural localisation right in all languages:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules

We currently do it in our code, which is not really necessary given we can just use that API.

**Comment by elrido** [comment]
So how would you pick the plural case from the one we have (singular, 1st plural, 2nd plural, 3rd plural, etc.) based on a string like "zero", "two", "few" or "many"? Would you have to redesign the translation file format for this to work? Can you also be replicate this in PHP, so that the server side translation still work or how would you handle those? Will you also want to migrate all existing translation files to this new design and update the crowdin integration to work with this new format?

**Comment by rugk** [comment]
Hmm yeah… good questions.
I found https://v8.dev/features/intl-pluralrules and they have some code-examples for that, but uff… yeah… they also say that libraries will likely just implement it, because it's a very low level API etc.

So yeah, maybe not worth the effort for now.

**Comment by elrido** [comment]
Fair enough, thank you for suggesting and reviewing!
