### ISSUE TITLE
burn after reading question

### ISSUE THREAD

**Issue by meanssaddles** [PrivateBin/PrivateBin#974]
## Steps to reproduce

1. tick 'burn after reading' and 'use a password' option on privatebin
2. access the paste and input wrong password

### What happens
the paste get burned anyway regardless of user read them (due to input the wrong password) or not

### What should happen
paste with burn after reading and wrong password shouldn't get burned, since that make password protection pointless 

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:** firefox

**PrivateBin version:** 1.4

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by UlyC** [comment]
same problem

**Comment by timaschew** [comment]
Maybe it makes sense to configure a max attempts number, if that is reached, then the paste is burned

**Comment by elrido** [comment]
This request duplicates the discussion in #245 - I had attempted to address this with the changes in #447, but abandoned it due to security concerns this raises.

In a nutshell, you can either guarantee that burn after reading function really deletes the message immediately upon first reading, regardless of who opened it, or you risk showing it to third parties when sending it multiple times, which undermines the privacy of the message, or you weaken the zero-knowledge design by introducing an authentication mechanism for the server to recognize "legitimate" users.
