### ISSUE TITLE
Docker Image with SQLite support?

### ISSUE THREAD

**Issue by kkoellner-shl** [PrivateBin/PrivateBin#989]
Does one of your official Docker images still supports SQLite as storage engine (as listed in your sample config)?
The documentation of the nginx-fpm-alpine image at least mentions sqlite once while the documentation of the pdo image doesn't.

I tried both but I'll get the following error:

> PHP message: PHP Fatal error:  Uncaught PDOException: could not find driver in /srv/lib/Data/Database.php:110
privatebin  | Stack trace:
privatebin  | #0 /srv/lib/Data/Database.php(110): PDO->__construct()
privatebin  | #1 [internal function]: PrivateBin\Data\Database::getInstance()
privatebin  | #2 /srv/lib/Model.php(86): forward_static_call()
privatebin  | #3 /srv/lib/Controller.php(199): PrivateBin\Model->getStore()
privatebin  | #4 /srv/lib/Controller.php(125): PrivateBin\Controller->_create()
privatebin  | #5 /var/www/index.php(18): PrivateBin\Controller->__construct()
privatebin  | #6 {main}

Using your sample config:

> [model]
; example of DB configuration for SQLite
class = Database
[model_options]
dsn = "sqlite:" PATH "data/db.sq3"
usr = null
pwd = null
opt[12] = true	; PDO::ATTR_PERSISTENT

**Comment by elrido** [comment]
As was [recently discussed](https://github.com/PrivateBin/PrivateBin/discussions/975#discussioncomment-3560130), these don't support SQLite (and likely haven't done so since at least [the switch to the alpine base image](https://github.com/PrivateBin/docker-nginx-fpm-alpine/commit/dba458cad96c2d0480289e4767f962c801605ec9)). If you don't want to use it with MariaDB, MySQL or Postgres, I highly recommend using the filesystem storage as it has similar requirements as SQLite (storage attached to the image), but less limitations. Further details are explained in this comment: https://github.com/PrivateBin/PrivateBin/discussions/975#discussioncomment-3560059

I've [raised a PR to address the misleading wording in the README](https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/112) and updated the [description on docker hub](https://hub.docker.com/r/privatebin/nginx-fpm-alpine).
