### ISSUE TITLE
Official Docker 

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#99]
Continuing https://github.com/PrivateBin/PrivateBin/issues/55#issuecomment-244592899

Make https://hub.docker.com/r/wonderfall/zerobin/ official.

Files: https://github.com/Wonderfall/dockerfiles/tree/master/privatebin

/cc @Wonderfall (we've already contacted you, just for you to track the progress)

**Comment by Wonderfall** [comment]
https://hub.docker.com/r/wonderfall/privatebin/ (renamed)
I've made some changes recently, including the use of tagged releases instead of using master. But is it necessary to keep this issue open? It seems you already have a [Dockerfile](https://github.com/PrivateBin/PrivateBin/blob/master/Dockerfile). It sounds right to me to keep an official image based on Debian, at least for development (as Alpine uses its own libc implementation, for instance), and let the community build more optimised images. Or maybe you'd like to advertise some?

**Comment by rugk** [comment]
> Or maybe you'd like to advertise some?

Yeah, why not? You could create a wiki page with a "list".

**Comment by tomas-samot** [comment]
I have made a docker file setup which also installs certbot and sets it all up.
https://github.com/tomas-samot/PrivateBin-docker

**Comment by k0nsl** [comment]
Very good, @tomas-samot. I would have preferred Alpine Linux (latest `3.6.2`?) coupled with Caddy (see [this link](https://caddyserver.com/) for details) for better performance :)

**Comment by elrido** [comment]
We have now (finally) an official docker image release, in addition to the Dockerfile currently included. It is found at:
https://hub.docker.com/r/privatebin/nginx-fpm-alpine/
https://github.com/PrivateBin/docker-nginx-fpm-alpine

This one is Alpine based, but uses Nginx instead of Caddy. I am very familiar with Nginx, while Caddy is still a very new kid on the block. So far I have not encountered any real-life scenarios where an Nginx was "too slow". :-)

Pull requests are of course always welcome, as long as they don't bloat the image up. We can of course ship more then one flavour of image to suit different needs.
